#include "bodyprog/bodyprog.h"

s_EventData MAP_EVENTS[28] = {
    {
        .disabledEventFlag  = EventFlag_M2S01_HealthDrink,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 25,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800CED44`
    },
    {
        .disabledEventFlag = EventFlag_181,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_Fmv,
        .eventParam      = 12,
        .flags_8_13          = 2,
    },
    {
        .requiredEventFlag = EventFlag_181,
        .disabledEventFlag = EventFlag_179,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_EventCallback,
        .eventParam      = 3, // `func_800CED88`
    },
    {
        .disabledEventFlag  = EventFlag_M2S01_PickupFlauros,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 1,
        .sysState         = SysState_EventCallback,
        .eventParam       = 4, // `func_800CF798`
    },
    {
        .disabledEventFlag  = EventFlag_M2S01_PickupDrawbridgeKey,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 1,
        .sysState         = SysState_EventCallback,
        .eventParam       = 5, // `func_800CF7C4`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 8,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 37,
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 9,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 37,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_OldTown_BalkanChurchCheck,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 5,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 7,
        .sfxPairIdx_8_19 = SfxPairIdx_2,
        .mapIdx   = MapIdx_MAP2_S00,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 10,
        .sysState         = SysState_SaveMenu1,
        .eventParam       = 7,
    },
    {
        .disabledEventFlag  = EventFlag_180,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 2,
        .sysState         = SysState_EventCallback,
        .eventParam       = 1, // `func_800CEC30`
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 2,
        .sysState         = SysState_EventCallback,
        .eventParam       = 1, // `func_800CEC30`
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 3,
        .sysState         = SysState_EventCallback,
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 4,
        .sysState         = SysState_EventCallback,
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 11,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 40,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 12,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 41,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 13,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 42,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 14,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 42,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 15,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 42,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 16,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 42,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 17,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 42,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 18,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 42,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 19,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 43,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 20,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 43,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 21,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 43,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 22,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 43,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 23,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 43,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 24,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 43,
    },
    {
        .triggerType = TriggerType_EndOfArray,
    },
};
