#include "bodyprog/bodyprog.h"

s_EventParam D_800D1EC0[21] = {
    {
        .disabledEventFlag_2 = EventFlag_237,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_EventCallFunc,
        .eventData_8_5       = 5, // `func_800D0608`
    },
    {
        .requiredEventFlag_0 = EventFlag_237,
        .disabledEventFlag_2 = EventFlag_238,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_LoadRoom,
        .eventData_8_5       = 1,
        .mapOverlayIdx_8_25  = MapOverlayId_MAP0_S02,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 6,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 7,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 8,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 9,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 10,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 12,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 13,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_233,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 4,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 3,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 4,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 4,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 3,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_234,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 11,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_236,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 5,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 11,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_236,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 11,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 5,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_235,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 5,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 11,
        .flags_8_13           = 2,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag_0 = EventFlag_235,
        .disabledEventFlag_2 = EventFlag_236,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_EventCallFunc,
        .eventData_8_5       = 4, // `func_800D03FC`
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 14,
        .sysState_8_0         = SysState_LoadOverlay,
        .eventData_8_5        = 15,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP3_S03,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 1,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 15,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 2,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 15,
    },
    {
        .triggerType_4_0 = TriggerType_EndOfArray,
    },
};
