#include "bodyprog/bodyprog.h"

s_EventData MAP_EVENTS[72] = {
    {
        .disabledEventFlag_2 = EventFlag_1,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_EventCallFunc,
        .eventParam_8_5      = 2, // `MapEvent_OpeningCutscene`
        .flags_8_13          = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_2,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 7,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800D9D98`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_2,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 8,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 4, // `func_800DA028`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_2,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 9,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 5, // `func_800DA254`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_2,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 5,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 5, // `func_800DA254`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0 = EventFlag_2,
        .disabledEventFlag_2 = EventFlag_3,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_Fmv,
        .eventParam_8_5      = 16,
    },
    {
        .requiredEventFlag_0 = EventFlag_3,
        .disabledEventFlag_2 = EventFlag_4,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_EventCallFunc,
        .eventParam_8_5      = 6, // `func_800DA5A0`
    },
    {
        .requiredEventFlag_0  = EventFlag_4,
        .disabledEventFlag_2  = EventFlag_12,
        .triggerType_4_0      = TriggerType_TouchObb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 10,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .requiredEventFlag_0  = EventFlag_12,
        .disabledEventFlag_2  = EventFlag_13,
        .triggerType_4_0      = TriggerType_TouchObb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 11,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 7, // `func_800DAA68`
    },
    {
        .requiredEventFlag_0  = EventFlag_4,
        .disabledEventFlag_2  = EventFlag_12,
        .triggerType_4_0      = TriggerType_TouchObb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 12,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 8, // `func_800DAB8C`
    },
    {
        .requiredEventFlag_0  = EventFlag_4,
        .disabledEventFlag_2  = EventFlag_12,
        .triggerType_4_0      = TriggerType_TouchObb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 13,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 9, // `func_800DACB0`
    },
    {
        .requiredEventFlag_0  = EventFlag_4,
        .disabledEventFlag_2  = EventFlag_12,
        .triggerType_4_0      = TriggerType_TouchObb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 14,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 10, // `func_800DADD4`
    },
    {
        .disabledEventFlag_2  = EventFlag_7,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 15,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 11, // `func_800DAEFC`
    },
    {
        .disabledEventFlag_2  = EventFlag_7,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 16,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 11, // `func_800DAEFC`
    },
    {
        .disabledEventFlag_2  = EventFlag_7,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 17,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 12, // `func_800DB26C`
    },
    {
        .disabledEventFlag_2  = EventFlag_13,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 18,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 19,
        .field_8_19           = 4,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 19,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 24,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_14,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 20,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 22,
        .field_8_19           = 4,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 22,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 21,
        .field_8_19           = 4,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 21,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 22,
        .field_8_19           = 4,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 23,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 24,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 25,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0 = EventFlag_15,
        .disabledEventFlag_2 = EventFlag_17,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_EventCallFunc,
        .eventParam_8_5      = 13, // `func_800DB514`
    },
    {
        .requiredEventFlag_0  = EventFlag_14,
        .disabledEventFlag_2  = EventFlag_19,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 27,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 14, // `func_800DB870`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_19,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 69,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 26,
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_19,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 70,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 26,
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_16,
        .disabledEventFlag_2  = EventFlag_24,
        .triggerType_4_0      = TriggerType_TouchObb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 26,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 15, // `MapEvent_CutsceneAlleyNightmare`
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 28,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 29,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 29,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 29,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 30,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 29,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 31,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 29,
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0 = EventFlag_25,
        .disabledEventFlag_2 = EventFlag_26,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_EventCallFunc,
        .eventParam_8_5      = 16, // `func_800DBE00`
        .flags_8_13          = 1,
    },
    {
        .requiredEventFlag_0 = EventFlag_26,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_LoadOverlay,
        .eventParam_8_5      = 4,
        .mapOverlayIdx_8_25  = MapOverlayId_MAP0_S01,
    },
    {
        .disabledEventFlag_2  = EventFlag_20,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 32,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag_2  = EventFlag_21,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 33,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag_2  = EventFlag_22,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 34,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag_2  = EventFlag_23,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 35,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 36,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 31,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 37,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 31,
    },
    {
        .requiredEventFlag_0  = EventFlag_24,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 38,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 32,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 39,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 33,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 40,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 33,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 41,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 33,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 42,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 34,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 43,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 34,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 44,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 34,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 45,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 34,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 46,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 34,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 47,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 34,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 48,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 34,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 49,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 34,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 50,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 34,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 51,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 34,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 52,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 37,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 53,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 37,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 54,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 37,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 55,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 35,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 56,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 35,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 57,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 35,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 58,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 35,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 59,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 35,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 60,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 35,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 61,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 35,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 62,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 35,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 63,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 35,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 64,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 35,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 65,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 35,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 66,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 35,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 67,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 35,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_OldTown_BachmanRdTopCross,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 68,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .triggerType_4_0 = TriggerType_EndOfArray,
    },
};
