    {
        .positionX = Q12(-6.2f),
        .paperMapIdx = PaperMapIdx_OldTown,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_PlayerRun,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 0,
        .positionZ = Q12(160.5f),
    },
    {
        .positionX = Q12(-58.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 0,
        .positionZ = Q12(47.0f),
    },
    {
        .positionX = Q12(-37.1f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 0,
        .positionZ = Q12(124.4f),
    },
    {
        .positionX = Q12(-252.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 0,
        .positionZ = Q12(222.0f),
    },
    {
        .positionX = Q12(2.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 0,
        .positionZ = Q12(271.4f),
    },
    {
        .positionX = Q12(30.1f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 12,
        .positionZ = Q12(154.0f),
    },
    {
        .positionX = Q12(-6.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 4,
        .triggerParam1 = 4,
        .positionZ = Q12(160.5f),
    },
    {
        .positionX = Q12(-10.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 8,
        .triggerParam1 = 4,
        .positionZ = Q12(144.0f),
    },
    {
        .positionX = Q12(4.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 48,
        .triggerParam1 = 4,
        .positionZ = Q12(144.0f),
    },
    {
        .positionX = Q12(21.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 20,
        .triggerParam1 = 4,
        .positionZ = Q12(144.0f),
    },
    {
        .positionX = Q12(-62.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 96,
        .positionZ = Q12(90.0f),
    },
    {
        .positionX = Q12(-62.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 96,
        .positionZ = Q12(100.0f),
    },
    {
        .positionX = Q12(-67.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 104,
        .positionZ = Q12(115.0f),
    },
    {
        .positionX = Q12(-21.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 200,
        .positionZ = Q12(120.0f),
    },
    {
        .positionX = Q12(-62.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 224,
        .triggerParam1 = 128,
        .positionZ = Q12(126.0f),
    },
    {
        .positionX = Q12(-56.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 4,
        .triggerParam1 = 24,
        .positionZ = Q12(126.0f),
    },
    {
        .positionX = Q12(-57.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 4,
        .triggerParam1 = 16,
        .positionZ = Q12(116.0f),
    },
    {
        .positionX = Q12(-57.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 4,
        .triggerParam1 = 16,
        .positionZ = Q12(108.0f),
    },
    {
        .positionX = Q12(-57.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 16,
        .positionZ = Q12(47.0f),
    },
    {
        .positionX = Q12(-96.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 16,
        .positionZ = Q12(247.0f),
    },
    {
        .positionX = Q12(-110.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 16,
        .positionZ = Q12(224.2f),
    },
    {
        .positionX = Q12(-190.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 16,
        .positionZ = Q12(224.4f),
    },
    {
        .positionX = Q12(-270.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 16,
        .positionZ = Q12(256.0f),
    },
    {
        .positionX = Q12(-256.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 16,
        .positionZ = Q12(244.0f),
    },
    {
        .positionX = Q12(-260.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 16,
        .positionZ = Q12(234.0f),
    },
    {
        .positionX = Q12(-255.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 16,
        .positionZ = Q12(218.5f),
    },
    {
        .positionX = Q12(-252.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 16,
        .positionZ = Q12(222.0f),
    },
    {
        .positionX = Q12(-185.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 4,
        .triggerParam1 = 4,
        .positionZ = Q12(227.0f),
    },
    {
        .positionX = Q12(-257.27f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 38,
        .triggerParam1 = 6,
        .positionZ = Q12(244.53f),
    },
    {
        .positionX = Q12(-257.77f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 102,
        .triggerParam1 = 14,
        .positionZ = Q12(243.68f),
    },
    {
        .positionX = Q12(-258.73f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 166,
        .triggerParam1 = 6,
        .positionZ = Q12(243.47f),
    },
    {
        .positionX = Q12(-258.23f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 230,
        .triggerParam1 = 14,
        .positionZ = Q12(244.32f),
    },
    {
        .positionX = Q12(-261.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 6,
        .positionZ = Q12(245.0f),
    },
    {
        .positionX = Q12(-259.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 6,
        .positionZ = Q12(237.0f),
    },
    {
        .positionX = Q12(-258.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 6,
        .positionZ = Q12(229.0f),
    },
    {
        .positionX = Q12(-252.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 6,
        .positionZ = Q12(228.0f),
    },
    {
        .positionX = Q12(-249.75f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 182,
        .triggerParam1 = 4,
        .positionZ = Q12(217.9f),
    },
    {
        .positionX = Q12(-249.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 229,
        .triggerParam1 = 4,
        .positionZ = Q12(218.35f),
    },
    {
        .positionX = Q12(-259.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 24,
        .positionZ = Q12(241.0f),
    },
    {
        .positionX = Q12(-268.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 8,
        .positionZ = Q12(245.8f),
    },
    {
        .positionX = Q12(-267.9f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 58,
        .triggerParam1 = 6,
        .positionZ = Q12(245.4f),
    },
    {
        .positionX = Q12(-268.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 112,
        .triggerParam1 = 8,
        .positionZ = Q12(244.8f),
    },
    {
        .positionX = Q12(-94.1f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 10,
        .positionZ = Q12(246.8f),
    },
    {
        .positionX = Q12(-94.1f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 10,
        .positionZ = Q12(246.8f),
    },
    {
        .positionX = Q12(-93.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 5,
        .positionZ = Q12(246.6f),
    },
    {
        .positionX = Q12(-93.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 5,
        .positionZ = Q12(246.6f),
    },
    {
        .positionX = Q12(-94.1f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 10,
        .positionZ = Q12(246.4f),
    },
    {
        .positionX = Q12(-94.1f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 10,
        .positionZ = Q12(246.4f),
    },
    {
        .positionX = Q12(-94.1f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 5,
        .positionZ = Q12(246.6f),
    },
    {
        .positionX = Q12(-94.1f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 5,
        .positionZ = Q12(246.6f),
    },
    {
        .positionX = Q12(-94.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 5,
        .positionZ = Q12(246.6f),
    },
    {
        .positionX = Q12(-94.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 5,
        .positionZ = Q12(246.6f),
    },
    {
        .positionX = Q12(-12.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 28,
        .triggerParam1 = 19,
        .positionZ = Q12(205.0f),
    },
    {
        .positionX = Q12(-13.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 143,
        .triggerParam1 = 24,
        .positionZ = Q12(203.5f),
    },
    {
        .positionX = Q12(-11.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 96,
        .triggerParam1 = 16,
        .positionZ = Q12(203.4f),
    },
    {
        .positionX = Q12(-9.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 8,
        .positionZ = Q12(220.0f),
    },
    {
        .positionX = Q12(-8.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 146,
        .triggerParam1 = 9,
        .positionZ = Q12(219.8f),
    },
    {
        .positionX = Q12(-7.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 16,
        .positionZ = Q12(219.5f),
    },
    {
        .positionX = Q12(-5.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 141,
        .triggerParam1 = 16,
        .positionZ = Q12(219.1f),
    },
    {
        .positionX = Q12(-2.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 109,
        .triggerParam1 = 35,
        .positionZ = Q12(219.8f),
    },
    {
        .positionX = Q12(1.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 143,
        .triggerParam1 = 17,
        .positionZ = Q12(220.4f),
    },
    {
        .positionX = Q12(2.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 100,
        .triggerParam1 = 9,
        .positionZ = Q12(220.4f),
    },
    {
        .positionX = Q12(5.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 155,
        .triggerParam1 = 9,
        .positionZ = Q12(220.4f),
    },
    {
        .positionX = Q12(7.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 120,
        .triggerParam1 = 16,
        .positionZ = Q12(220.2f),
    },
    {
        .positionX = Q12(10.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 150,
        .triggerParam1 = 36,
        .positionZ = Q12(219.2f),
    },
    {
        .positionX = Q12(13.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 16,
        .positionZ = Q12(218.0f),
    },
    {
        .positionX = Q12(15.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 109,
        .triggerParam1 = 17,
        .positionZ = Q12(218.5f),
    },
    {
        .positionX = Q12(17.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 16,
        .positionZ = Q12(219.0f),
    },
    {
        .positionX = Q12(4.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 60,
        .triggerParam1 = 36,
        .positionZ = Q12(220.0f),
    },
    {
        .positionX = Q12(-184.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 2,
        .triggerParam1 = 4,
        .positionZ = Q12(227.0f),
    },
    {
        .positionX = Q12(-185.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 16,
        .positionZ = Q12(227.0f),
    }
