#include "bodyprog/bodyprog.h"

s_EventData MAP_EVENTS[21] = {
    {
        .requiredEventFlag_0 = EventFlag_337,
        .disabledEventFlag_2 = EventFlag_338,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_EventCallFunc,
        .eventParam_8_5      = 3, // `func_800D1910`
    },
    {
        .requiredEventFlag_0 = EventFlag_338,
        .disabledEventFlag_2 = EventFlag_308,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_LoadOverlay,
        .eventParam_8_5      = 11,
        .mapOverlayIdx_8_25  = MapOverlayId_MAP4_S01,
    },
    {
        .requiredEventFlag_0 = EventFlag_339,
        .disabledEventFlag_2 = EventFlag_340,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_EventCallFunc,
        .eventParam_8_5      = 4, // `func_800D23E4`
    },
    {
        .requiredEventFlag_0 = EventFlag_340,
        .disabledEventFlag_2 = EventFlag_341,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_LoadRoom,
        .eventParam_8_5      = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 10,
        .sysState_8_0         = SysState_SaveMenu1,
        .eventParam_8_5       = 10,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltHospital1F_WomensBathroomBroken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 4,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 8,
        .field_8_19           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltHospital1F_WomensBathroomBroken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 8,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 4,
        .field_8_19           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1472,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 5,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_339,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 1,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 6,
        .field_8_19           = 20,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 6,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 1,
        .field_8_19           = 12,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 1,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 6,
        .field_8_19           = 12,
    },
    {
        .requiredEventFlag_0  = EventFlag_340,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 2,
        .sysState_8_0         = SysState_LoadOverlay,
        .eventParam_8_5       = 9,
        .field_8_19           = 2,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP4_S05,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 2,
        .sysState_8_0         = SysState_LoadOverlay,
        .eventParam_8_5       = 9,
        .field_8_19           = 2,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP4_S02,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltHospital1F_StairsArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 3,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1476,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 7,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 12,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 80,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 13,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 80,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 14,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 80,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 15,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 80,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 16,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 81,
    },
    {
        .triggerType_4_0 = TriggerType_EndOfArray,
    },
};
