#include "bodyprog/bodyprog.h"

s_EventParam D_800D3614[21] = {
    {
        .requiredEventFlag_0  = EventFlag_337,
        .disabledEventFlag_2  = EventFlag_338,
        .triggerType_4_0      = TriggerType_None,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 0,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 3, // `func_800D1910`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_338,
        .disabledEventFlag_2  = 308,
        .triggerType_4_0      = TriggerType_None,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 0,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadOverlay,
        .eventData_8_5        = 11,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP4_S01,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_339,
        .disabledEventFlag_2  = EventFlag_340,
        .triggerType_4_0      = TriggerType_None,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 0,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 4, // `func_800D23E4`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_340,
        .disabledEventFlag_2  = 341,
        .triggerType_4_0      = TriggerType_None,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 0,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 1,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 10,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_SaveMenu1,
        .eventData_8_5        = 10,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1475,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 4,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 8,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1475,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 8,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 4,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1472,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 5,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 0, // `MapEvent_DoorJammed`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_339,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 1,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 6,
        .flags_8_13           = 0,
        .field_8_19           = 20,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 6,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 1,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 1,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 6,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_340,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 2,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadOverlay,
        .eventData_8_5        = 9,
        .flags_8_13           = 0,
        .field_8_19           = 2,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP4_S05,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 2,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadOverlay,
        .eventData_8_5        = 9,
        .flags_8_13           = 0,
        .field_8_19           = 2,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP4_S02,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1468,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 3,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 0, // `MapEvent_DoorJammed`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1476,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 7,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 0, // `MapEvent_DoorJammed`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 12,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 80,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 13,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 80,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 14,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 80,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 15,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 80,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 16,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 81,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_EndOfArray,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 0,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_Gameplay,
        .eventData_8_5        = 0,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
};
