#include "bodyprog/bodyprog.h"

s_EventData MAP_EVENTS[52] = {
    {
        .disabledEventFlag  = EventFlag_M5S00_ShotgunShells,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 38,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `MapEvent_CommonItemTake`
    },
    {
        .disabledEventFlag  = EventFlag_M5S00_HealthDrink0,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 39,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `MapEvent_CommonItemTake`
    },
    {
        .disabledEventFlag  = EventFlag_M5S00_HandgunBullets0,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 40,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `MapEvent_CommonItemTake`
    },
    {
        .disabledEventFlag  = EventFlag_M5S00_RifleShells,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 41,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `MapEvent_CommonItemTake`
    },
    {
        .disabledEventFlag  = EventFlag_M5S00_FirstAidKit0,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 42,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `MapEvent_CommonItemTake`
    },
    {
        .disabledEventFlag  = EventFlag_M5S00_FirstAidKit1,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 43,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `MapEvent_CommonItemTake`
    },
    {
        .disabledEventFlag  = EventFlag_M5S00_HealthDrink1,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 44,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `MapEvent_CommonItemTake`
    },
    {
        .disabledEventFlag  = EventFlag_M5S00_HandgunBullets1,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 45,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `MapEvent_CommonItemTake`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 34,
        .sysState         = SysState_SaveMenu1,
        .eventParam       = 21,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 35,
        .sysState         = SysState_SaveMenu1,
        .eventParam       = 21,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 36,
        .sysState         = SysState_SaveMenu1,
        .eventParam       = 21,
    },
    {
        .disabledEventFlag = EventFlag_355,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_EventCallFunc,
        .eventParam      = 6, // `func_800D732C`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 22,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 19,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 23,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 7, // `func_800D75FC`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 24,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 7, // `func_800D75FC`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 25,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 7, // `func_800D75FC`
    },
    {
        .requiredEventFlag = EventFlag_356,
        .disabledEventFlag = EventFlag_357,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_LoadRoom,
        .eventParam      = 26,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 26,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 8, // `func_800D7940`
    },
    {
        .requiredEventFlag = EventFlag_357,
        .disabledEventFlag = EventFlag_356,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_LoadRoom,
        .eventParam      = 23,
    },
    {
        .requiredEventFlag = EventFlag_360,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_EventCallFunc,
        .eventParam      = 10, // `func_800D7F88`
    },
    {
        .requiredEventFlag = EventFlag_359,
        .disabledEventFlag = EventFlag_358,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_LoadRoom,
        .eventParam      = 27,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 27,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 9, // `func_800D7C84`
    },
    {
        .requiredEventFlag = EventFlag_358,
        .disabledEventFlag = EventFlag_359,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_LoadOverlay,
        .eventParam      = 31,
        .mapIdx  = MapIdx_MAP5_S01,
    },
    {
        .disabledEventFlag  = EventFlag_M5S00_PickupSewerKey,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 29,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 4, // `MapEvent_SewerKeyTake`
    },
    {
        .disabledEventFlag  = EventFlag_354,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 30,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 5, // `func_800D6B00`
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_FogSewer1F_RightMidArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 5,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 6,
        .sfxPairIdx_8_19 = SfxPairIdx_8,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_FogSewer1F_RightMidArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 6,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 5,
        .sfxPairIdx_8_19 = SfxPairIdx_8,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSewer1F_RightMidArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 6,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 2, // `func_800D69DC`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSewer1F_RightMidLocked,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 5,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 1, // `func_800D6888`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_FogSewer1F_MidArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 10,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 9,
        .sfxPairIdx_8_19 = SfxPairIdx_8,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_FogSewer1F_MidArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 9,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 10,
        .sfxPairIdx_8_19 = SfxPairIdx_8,
    },
    {
        .requiredEventFlag  = EventFlag_M5S00_PickupSewerKey,
        .disabledEventFlag  = EventFlag_MapMark_FogSewer1F_MidArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 10,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 2, // `func_800D69DC`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_M5S00_PickupSewerKey,
        .disabledEventFlag  = EventFlag_MapMark_FogSewer1F_MidArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Item,
        .pointOfInterestIdx = 10,
        .requiredItemId     = InventoryItemId_SewerKey,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 2, // `func_800D69DC`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSewer1F_MidLocked,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 10,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 1, // `func_800D6888`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_527,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 14,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 15,
        .sfxPairIdx_8_19 = SfxPairIdx_8,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_527,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 15,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 14,
        .sfxPairIdx_8_19 = SfxPairIdx_8,
    },
    {
        .requiredEventFlag  = EventFlag_354,
        .disabledEventFlag  = EventFlag_MapMark_527,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 14,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 2, // `func_800D69DC`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_354,
        .disabledEventFlag  = EventFlag_MapMark_527,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Item,
        .pointOfInterestIdx = 14,
        .requiredItemId     = InventoryItemId_SewerExitKey,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 2, // `func_800D69DC`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_1390,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 14,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 1, // `func_800D6888`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_M5S00_PickupMap,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 32,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 11, // `MapEvent_MapTake`
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSewer1F_RightTopArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 3,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 4,
        .sfxPairIdx_8_19 = SfxPairIdx_8,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSewer1F_RightTopArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 4,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 3,
        .sfxPairIdx_8_19 = SfxPairIdx_8,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSewer1F_RightBotArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 7,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 8,
        .sfxPairIdx_8_19 = SfxPairIdx_8,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSewer1F_RightBotArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 8,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 7,
        .sfxPairIdx_8_19 = SfxPairIdx_8,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSewer_BigCross,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 16,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 17,
        .sfxPairIdx_8_19 = SfxPairIdx_8,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSewer_BigCross,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 17,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 16,
        .sfxPairIdx_8_19 = SfxPairIdx_8,
    },
    {
        .disabledEventFlag  = EventFlag_1395,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 18,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 19,
        .sfxPairIdx_8_19 = SfxPairIdx_8,
    },
    {
        .disabledEventFlag  = EventFlag_1395,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 19,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 18,
        .sfxPairIdx_8_19 = SfxPairIdx_8,
    },
    {
        .disabledEventFlag  = EventFlag_1397,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 20,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 21,
        .sfxPairIdx_8_19 = SfxPairIdx_8,
    },
    {
        .disabledEventFlag  = EventFlag_1397,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 21,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 20,
        .sfxPairIdx_8_19 = SfxPairIdx_8,
    },
    {
        .disabledEventFlag  = EventFlag_1398,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 37,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .triggerType = TriggerType_EndOfArray,
    },
};
