    {
        .positionX = Q12(18.0f),
        .paperMapIdx = PaperMapIdx_FogSewer1F,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 0,
        .positionZ = Q12(52.0f),
    },
    {
        .positionX = Q12(-92.0f),
        .paperMapIdx = PaperMapIdx_FogSewer2F,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(7.0f),
    },
    {
        .positionX = Q12(58.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 8,
        .positionZ = Q12(12.5f),
    },
    {
        .positionX = Q12(54.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 8,
        .positionZ = Q12(-48.0f),
    },
    {
        .positionX = Q12(54.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 8,
        .positionZ = Q12(-48.0f),
    },
    {
        .positionX = Q12(49.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 8,
        .positionZ = Q12(-48.0f),
    },
    {
        .positionX = Q12(49.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 8,
        .positionZ = Q12(-48.0f),
    },
    {
        .positionX = Q12(45.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 8,
        .positionZ = Q12(-49.5f),
    },
    {
        .positionX = Q12(45.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 8,
        .positionZ = Q12(-49.5f),
    },
    {
        .positionX = Q12(0.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 8,
        .positionZ = Q12(-14.5f),
    },
    {
        .positionX = Q12(0.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 8,
        .positionZ = Q12(-14.5f),
    },
    {
        .positionX = Q12(-57.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 8,
        .positionZ = Q12(-92.5f),
    },
    {
        .positionX = Q12(-89.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 16,
        .positionZ = Q12(-92.0f),
    },
    {
        .positionX = Q12(-89.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 16,
        .positionZ = Q12(-92.0f),
    },
    {
        .positionX = Q12(-89.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 8,
        .positionZ = Q12(-96.0f),
    },
    {
        .positionX = Q12(-89.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 8,
        .positionZ = Q12(-96.0f),
    },
    {
        .positionX = Q12(-89.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 8,
        .positionZ = Q12(-76.0f),
    },
    {
        .positionX = Q12(-89.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 8,
        .positionZ = Q12(-76.0f),
    },
    {
        .positionX = Q12(-89.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 8,
        .positionZ = Q12(-40.0f),
    },
    {
        .positionX = Q12(-89.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 8,
        .positionZ = Q12(-40.0f),
    },
    {
        .positionX = Q12(-95.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 8,
        .positionZ = Q12(-16.0f),
    },
    {
        .positionX = Q12(-95.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 8,
        .positionZ = Q12(-16.0f),
    },
    {
        .positionX = Q12(16.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 6,
        .positionZ = Q12(52.0f),
    },
    {
        .positionX = Q12(-29.0f),
        .paperMapIdx = PaperMapIdx_FogSewer1F,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 6,
        .positionZ = Q12(-5.4f),
    },
    {
        .positionX = Q12(-29.38f),
        .paperMapIdx = PaperMapIdx_FogSewer1F,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 182,
        .triggerParam1 = 2,
        .positionZ = Q12(-5.17f),
    },
    {
        .positionX = Q12(-28.62f),
        .paperMapIdx = PaperMapIdx_FogSewer1F,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 201,
        .triggerParam1 = 2,
        .positionZ = Q12(-5.17f),
    },
    {
        .positionX = Q12(-46.0f),
        .paperMapIdx = PaperMapIdx_FogSewer2F,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(-6.0f),
    },
    {
        .positionX = Q12(-87.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 6,
        .positionZ = Q12(-103.6f),
    },
    {
        .positionX = Q12(41.7f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 4,
        .positionZ = Q12(-49.0f),
    },
    {
        .positionX = Q12(42.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 8,
        .positionZ = Q12(-48.1f),
    },
    {
        .positionX = Q12(-92.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 16,
        .positionZ = Q12(8.0f),
    },
    {
        .positionX = Q12(-60.1f),
        .paperMapIdx = PaperMapIdx_ResortTown,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 0,
        .positionZ = Q12(2.5f),
    },
    {
        .positionX = Q12(41.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 6,
        .positionZ = Q12(-49.0f),
    },
    {
        .positionX = Q12(-56.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 6,
        .positionZ = Q12(-92.0f),
    },
    {
        .positionX = Q12(40.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 4,
        .positionZ = Q12(-49.0f),
    },
    {
        .positionX = Q12(-86.31f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 254,
        .triggerParam1 = 5,
        .positionZ = Q12(-103.31f),
    },
    {
        .positionX = Q12(-86.69f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 198,
        .triggerParam1 = 5,
        .positionZ = Q12(-103.67f),
    },
    {
        .positionX = Q12(-79.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 60,
        .triggerParam1 = 18,
        .positionZ = Q12(-12.0f),
    },
    {
        .positionX = Q12(58.37f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(13.13f),
    },
    {
        .positionX = Q12(56.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(13.55f),
    },
    {
        .positionX = Q12(57.3f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(13.71f),
    },
    {
        .positionX = Q12(47.37f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(13.91f),
    },
    {
        .positionX = Q12(-29.09f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(-17.39f),
    },
    {
        .positionX = Q12(-42.41f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(-6.59f),
    },
    {
        .positionX = Q12(-58.97f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(-96.17f),
    },
    {
        .positionX = Q12(-60.89f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(-96.28f),
    }

