    {
      .lim_sw_0 = {
        .min_hx = Q4(16.0f),
        .max_hx = Q4(23.0f),
        .min_hz = Q4(48.0f),
        .max_hz = Q4(55.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(17.0f),
        .max_hx = Q4(23.0f),
        .min_hz = Q4(49.0f),
        .max_hz = Q4(54.5f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-3.6f),
      .lim_rd_min_hy_13 = Q4(-3.6f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(17.0f),
        .max_hx = Q4(23.0f),
        .min_hz = Q4(33.0f),
        .max_hz = Q4(51.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(20.0f),
        .max_hx = Q4(20.0f),
        .min_hz = Q4(31.7f),
        .max_hz = Q4(54.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-2.4f),
      .lim_rd_min_hy_13 = Q4(-2.4f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(17.0f),
        .max_hx = Q4(23.0f),
        .min_hz = Q4(31.5f),
        .max_hz = Q4(35.5f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(20.0f),
        .max_hx = Q4(20.0f),
        .min_hz = Q4(20.0f),
        .max_hz = Q4(45.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_EVENT,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-1.8f),
      .lim_rd_min_hy_13 = Q4(-1.8f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(17.0f),
        .max_hx = Q4(23.0f),
        .min_hz = Q4(-9.0f),
        .max_hz = Q4(33.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(20.0f),
        .max_hx = Q4(20.0f),
        .min_hz = Q4(-11.0f),
        .max_hz = Q4(45.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.6f),
      .lim_rd_min_hy_13 = Q4(-1.6f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(14.0f),
        .min_hz = Q4(-16.0f),
        .max_hz = Q4(-8.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(1.0f),
        .max_hx = Q4(17.3f),
        .min_hz = Q4(-14.6f),
        .max_hz = Q4(-9.4f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.9f),
      .lim_rd_min_hy_13 = Q4(-1.9f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(16.0f),
        .max_hx = Q4(23.5f),
        .min_hz = Q4(-10.0f),
        .max_hz = Q4(-8.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(6.0f),
        .max_hx = Q4(34.0f),
        .min_hz = Q4(-11.4f),
        .max_hz = Q4(-9.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.9f),
      .lim_rd_min_hy_13 = Q4(-1.9f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(25.0f),
        .max_hx = Q4(50.0f),
        .min_hz = Q4(-16.0f),
        .max_hz = Q4(-8.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(22.3f),
        .max_hx = Q4(52.0f),
        .min_hz = Q4(-14.6f),
        .max_hz = Q4(-9.4f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.9f),
      .lim_rd_min_hy_13 = Q4(-1.9f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(23.0f),
        .max_hx = Q4(27.0f),
        .min_hz = Q4(-16.0f),
        .max_hz = Q4(-13.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(22.3f),
        .max_hx = Q4(52.0f),
        .min_hz = Q4(-14.6f),
        .max_hz = Q4(-9.4f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_EFFECT,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.9f),
      .lim_rd_min_hy_13 = Q4(-1.9f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-31.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(-18.0f),
        .max_hz = Q4(-6.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-25.6f),
        .max_hx = Q4(-4.0f),
        .min_hz = Q4(-15.0f),
        .max_hz = Q4(-9.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-4.1f),
      .lim_rd_min_hy_13 = Q4(-4.1f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-31.0f),
        .max_hx = Q4(-28.0f),
        .min_hz = Q4(-8.0f),
        .max_hz = Q4(-5.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-27.6f),
        .max_hx = Q4(-27.6f),
        .min_hz = Q4(-8.9f),
        .max_hz = Q4(-8.9f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_EVENT,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-0.8f),
      .lim_rd_min_hy_13 = Q4(-0.8f),
      .ofs_watch_hy_14 = Q4(-0.9f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(49.0f),
        .max_hx = Q4(58.0f),
        .min_hz = Q4(-22.2f),
        .max_hz = Q4(14.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(52.0f),
        .max_hx = Q4(52.0f),
        .min_hz = Q4(-47.0f),
        .max_hz = Q4(8.7f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-3.1f),
      .lim_rd_min_hy_13 = Q4(-3.1f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(46.0f),
        .max_hx = Q4(58.0f),
        .min_hz = Q4(-47.9f),
        .max_hz = Q4(-22.2f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(51.1f),
        .max_hx = Q4(51.1f),
        .min_hz = Q4(-47.0f),
        .max_hz = Q4(8.7f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-3.1f),
      .lim_rd_min_hy_13 = Q4(-3.1f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(55.0f),
        .max_hx = Q4(58.0f),
        .min_hz = Q4(11.5f),
        .max_hz = Q4(14.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(55.0f),
        .max_hx = Q4(55.0f),
        .min_hz = Q4(11.4f),
        .max_hz = Q4(11.4f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_EVENT,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-3.1f),
      .lim_rd_min_hy_13 = Q4(-3.1f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(45.1f),
        .max_hx = Q4(58.0f),
        .min_hz = Q4(-57.5f),
        .max_hz = Q4(-48.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(52.0f),
        .max_hx = Q4(57.3f),
        .min_hz = Q4(-53.2f),
        .max_hz = Q4(-53.2f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-4.3f),
      .lim_rd_min_hy_13 = Q4(-4.3f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(40.0f),
        .max_hx = Q4(58.0f),
        .min_hz = Q4(-62.0f),
        .max_hz = Q4(-57.5f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(47.2f),
        .max_hx = Q4(57.8f),
        .min_hz = Q4(-59.3f),
        .max_hz = Q4(-59.3f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-4.3f),
      .lim_rd_min_hy_13 = Q4(-4.3f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(40.0f),
        .max_hx = Q4(45.0f),
        .min_hz = Q4(-60.5f),
        .max_hz = Q4(-48.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(43.0f),
        .max_hx = Q4(43.0f),
        .min_hz = Q4(-60.5f),
        .max_hz = Q4(-50.7f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.4f),
      .lim_rd_min_hy_13 = Q4(-1.4f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-51.0f),
        .max_hx = Q4(-44.2f),
        .min_hz = Q4(-16.0f),
        .max_hz = Q4(-5.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-47.0f),
        .max_hx = Q4(-41.3f),
        .min_hz = Q4(-18.0f),
        .max_hz = Q4(-8.7f),
      },
      .flags_10 = VC_RD_WARP_IN_OUT_FS | VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-3.0f),
      .lim_rd_min_hy_13 = Q4(-3.0f),
      .ofs_watch_hy_14 = Q4(-0.4f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-73.0f),
        .max_hx = Q4(-51.0f),
        .min_hz = Q4(-23.0f),
        .max_hz = Q4(-1.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-71.2f),
        .max_hx = Q4(-58.2f),
        .min_hz = Q4(-15.1f),
        .max_hz = Q4(-9.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-2.9f),
      .lim_rd_min_hy_13 = Q4(-2.9f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-63.0f),
        .max_hx = Q4(-57.0f),
        .min_hz = Q4(-1.0f),
        .max_hz = Q4(7.5f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-60.3f),
        .max_hx = Q4(-60.3f),
        .min_hz = Q4(-10.0f),
        .max_hz = Q4(9.0f),
      },
      .flags_10 = VC_RD_WARP_OUT_F | VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.4f),
      .lim_rd_min_hy_13 = Q4(-1.4f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-63.0f),
        .max_hx = Q4(-57.0f),
        .min_hz = Q4(7.5f),
        .max_hz = Q4(12.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-59.6f),
        .max_hx = Q4(-59.6f),
        .min_hz = Q4(12.4f),
        .max_hz = Q4(12.4f),
      },
      .flags_10 = VC_RD_WARP_IN_OUT_FS,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-4.2f),
      .lim_rd_min_hy_13 = Q4(-4.2f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-63.0f),
        .max_hx = Q4(-57.0f),
        .min_hz = Q4(-72.5f),
        .max_hz = Q4(-24.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-60.3f),
        .max_hx = Q4(-60.3f),
        .min_hz = Q4(-67.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_WARP_IN_OUT_FS,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.4f),
      .lim_rd_min_hy_13 = Q4(-1.4f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-64.0f),
        .max_hx = Q4(-56.0f),
        .min_hz = Q4(-96.0f),
        .max_hz = Q4(-72.5f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-60.0f),
        .max_hx = Q4(-60.0f),
        .min_hz = Q4(-92.0f),
        .max_hz = Q4(-74.3f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-2.5f),
      .lim_rd_min_hy_13 = Q4(-2.5f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-70.0f),
        .max_hx = Q4(-56.0f),
        .min_hz = Q4(-96.0f),
        .max_hz = Q4(-88.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-74.0f),
        .max_hx = Q4(-59.0f),
        .min_hz = Q4(-92.0f),
        .max_hz = Q4(-92.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-2.5f),
      .lim_rd_min_hy_13 = Q4(-2.5f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-74.0f),
        .max_hx = Q4(-70.0f),
        .min_hz = Q4(-95.0f),
        .max_hz = Q4(-89.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-89.5f),
        .max_hx = Q4(-59.0f),
        .min_hz = Q4(-92.0f),
        .max_hz = Q4(-92.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_EVENT,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-1.8f),
      .lim_rd_min_hy_13 = Q4(-1.8f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-91.2f),
        .max_hx = Q4(-74.0f),
        .min_hz = Q4(-95.0f),
        .max_hz = Q4(-89.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-94.8f),
        .max_hx = Q4(-59.0f),
        .min_hz = Q4(-92.0f),
        .max_hz = Q4(-92.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.6f),
      .lim_rd_min_hy_13 = Q4(-1.6f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-96.0f),
        .max_hx = Q4(-88.0f),
        .min_hz = Q4(-95.9f),
        .max_hz = Q4(-76.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-94.8f),
        .max_hx = Q4(-89.5f),
        .min_hz = Q4(-95.9f),
        .max_hz = Q4(-76.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-2.5f),
      .lim_rd_min_hy_13 = Q4(-2.5f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-96.0f),
        .max_hx = Q4(-88.0f),
        .min_hz = Q4(-76.0f),
        .max_hz = Q4(-40.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-94.5f),
        .max_hx = Q4(-89.5f),
        .min_hz = Q4(-76.0f),
        .max_hz = Q4(-40.0f),
      },
      .flags_10 = VC_RD_WARP_IN_OUT_FS | VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-3.1f),
      .lim_rd_min_hy_13 = Q4(-3.1f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-96.0f),
        .max_hx = Q4(-88.0f),
        .min_hz = Q4(-40.0f),
        .max_hz = Q4(-16.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-94.5f),
        .max_hx = Q4(-89.5f),
        .min_hz = Q4(-40.0f),
        .max_hz = Q4(-18.0f),
      },
      .flags_10 = VC_RD_WARP_IN_OUT_FS | VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-3.1f),
      .lim_rd_min_hy_13 = Q4(-3.1f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-96.0f),
        .max_hx = Q4(-88.0f),
        .min_hz = Q4(-16.0f),
        .max_hz = Q4(-1.5f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-92.0f),
        .max_hx = Q4(-92.0f),
        .min_hz = Q4(-13.0f),
        .max_hz = Q4(8.0f),
      },
      .flags_10 = VC_RD_WARP_IN_OUT_FS | VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-3.1f),
      .lim_rd_min_hy_13 = Q4(-3.1f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-96.0f),
        .max_hx = Q4(-88.0f),
        .min_hz = Q4(-1.5f),
        .max_hz = Q4(8.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-91.6f),
        .max_hx = Q4(-91.6f),
        .min_hz = Q4(-13.0f),
        .max_hz = Q4(8.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-7.5f),
      .lim_rd_min_hy_13 = Q4(-7.5f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_FIX_ANG,
      .fix_ang_x_16 = Q8_ANGLE(294.0f),
      .fix_ang_y_17 = Q8_ANGLE(346.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-93.5f),
        .max_hx = Q4(-90.5f),
        .min_hz = Q4(6.5f),
        .max_hz = Q4(8.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-91.6f),
        .max_hx = Q4(-91.6f),
        .min_hz = Q4(-13.0f),
        .max_hz = Q4(8.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_EFFECT,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-6.0f),
      .lim_rd_min_hy_13 = Q4(-6.0f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_FIX_ANG,
      .fix_ang_x_16 = Q8_ANGLE(294.0f),
      .fix_ang_y_17 = Q8_ANGLE(346.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-98.0f),
        .max_hx = Q4(-86.0f),
        .min_hz = Q4(-102.2f),
        .max_hz = Q4(-96.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-91.8f),
        .max_hx = Q4(-91.8f),
        .min_hz = Q4(-100.7f),
        .max_hz = Q4(-100.7f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-3.4f),
      .lim_rd_min_hy_13 = Q4(-3.4f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-98.0f),
        .max_hx = Q4(-86.0f),
        .min_hz = Q4(-103.0f),
        .max_hz = Q4(-102.2f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-88.8f),
        .max_hx = Q4(-88.8f),
        .min_hz = Q4(-102.4f),
        .max_hz = Q4(-100.4f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_EVENT,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-3.0f),
      .lim_rd_min_hy_13 = Q4(-3.0f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_END_DATA_F,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
