name: The MAP1_S05 map overlay (MAP1_S05)
sha1: 9ef2c38d11b229648a12ef5d730a02ee6f21635d
options:
  basename: MAP1_S05.BIN
  target_path: assets/VIN/MAP1_S05.BIN
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/maps/map1_s05
  src_path: src/maps/map1_s05
  build_path: build

  ld_script_path: linkers/maps/map1_s05.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/symbol_addrs.txt
    - configs/maps/symbol_addrs.map1_s05.txt
  reloc_addrs_path:
    - configs/maps/reloc_addrs.map1_s05.txt

  undefined_funcs_auto_path: linkers/maps/undefined_funcs_auto.map1_s05.txt
  undefined_syms_auto_path: linkers/maps/undefined_syms_auto.map1_s05.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map1_s05
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x1558, asm, map1_s05]
      - [0xC10C, data, map1_s05]
  - [0xF200]
