name: The MAP2_S03 map overlay (MAP2_S03)
sha1: ccca5fc42275356361c4ed22ecb217ff35573d95
options:
  basename: MAP2_S03.BIN
  target_path: assets/VIN/MAP2_S03.BIN
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/maps/map2_s03
  src_path: src/maps/map2_s03
  build_path: build

  ld_script_path: linkers/maps/map2_s03.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/symbol_addrs.txt
    - configs/maps/symbol_addrs.map2_s03.txt
  reloc_addrs_path:
    - configs/maps/reloc_addrs.map2_s03.txt

  undefined_funcs_auto_path: linkers/maps/undefined_funcs_auto.map2_s03.txt
  undefined_syms_auto_path: linkers/maps/undefined_syms_auto.map2_s03.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map2_s03
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x138C, asm, map2_s03]
      - [0x35C4, data, map2_s03]
  - [0x4a00]
