name: The MAP5_S03 map overlay (MAP5_S03)
sha1: 864d2b40500c045af610a8bc31ec11ead0274657
options:
  basename: MAP5_S03.BIN
  target_path: assets/VIN/MAP5_S03.BIN
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/maps/map5_s03
  src_path: src/maps/map5_s03
  build_path: build

  ld_script_path: linkers/maps/map5_s03.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/symbol_addrs.txt
    - configs/maps/symbol_addrs.map5_s03.txt
  reloc_addrs_path:
    - configs/maps/reloc_addrs.map5_s03.txt

  undefined_funcs_auto_path: linkers/maps/undefined_funcs_auto.map5_s03.txt
  undefined_syms_auto_path: linkers/maps/undefined_syms_auto.map5_s03.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map5_s03
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x237C, asm, map5_s03]
      - [0x9B18, data, map5_s03]
  - [0xDC00]
