name: The MAP7_S00 map overlay (MAP7_S00)
sha1: 170fdbef21f21993c113924da58ab407c8157d99
options:
  basename: MAP7_S00.BIN
  target_path: assets/VIN/MAP7_S00.BIN
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/maps/map7_s00
  src_path: src/maps/map7_s00
  build_path: build

  ld_script_path: linkers/maps/map7_s00.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/sym.main.txt
    - configs/sym.bodyprog.txt
    - configs/maps/sym.map7_s00.txt
  reloc_addrs_path:
    - configs/maps/rel.map7_s00.txt

  undefined_funcs_auto_path: linkers/maps/undefined_funcs_auto.map7_s00.txt
  undefined_syms_auto_path: linkers/maps/undefined_syms_auto.map7_s00.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map7_s00
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x20AC, c, map7_s00]
      - [0x959C, data, map7_s00]
  - [0xAF00]
