    {
      .positionX = -55,
      .positionZ = 10,
      .sizeX = 1,
      .sizeZ = 3,
      .height = 3,
    },
    {
      .positionX = -61,
      .positionZ = 5,
      .sizeX = 4,
      .sizeZ = 1,
      .height = 3,
    },
    {
      .positionX = -54,
      .positionZ = -129,
      .sizeX = 5,
      .sizeZ = 2,
      .height = 2,
    },
    {
      .positionX = -32,
      .positionZ = -25,
      .sizeX = 8,
      .sizeZ = 5,
      .height = 3,
    },
    {
      .positionX = -18,
      .positionZ = -62,
      .sizeX = 5,
      .sizeZ = 3,
      .height = 2,
    },
    {
      .positionX = -23,
      .positionZ = -145,
      .sizeX = 1,
      .sizeZ = 5,
      .height = 2,
    },
    {
      .positionX = -21,
      .positionZ = -147,
      .sizeX = 10,
      .sizeZ = 1,
      .height = 2,
    },
    {
      .positionX = -22,
      .positionZ = -146,
      .sizeX = 2,
      .sizeZ = 2,
      .height = 2,
    },
    {
      .positionX = -33,
      .positionZ = -149,
      .sizeX = 1,
      .sizeZ = 1,
      .height = 2,
    },
    {
      .positionX = 28,
      .positionZ = -49,
      .sizeX = 3,
      .sizeZ = 1,
      .height = 2,
    },
    {
      .positionX = 32,
      .positionZ = -148,
      .sizeX = 1,
      .sizeZ = 1,
      .height = 1,
    },
    {
      .positionX = 31,
      .positionZ = -149,
      .sizeX = 1,
      .sizeZ = 1,
      .height = 1,
    },
    {
      .positionX = 23,
      .positionZ = -22,
      .sizeX = 10,
      .sizeZ = 15,
      .height = 3,
    },
    {
      .positionX = 30,
      .positionZ = -28,
      .sizeX = 1,
      .sizeZ = 4,
      .height = 1,
    },
    {
      .positionX = -66,
      .positionZ = -149,
      .sizeX = 4,
      .sizeZ = 1,
      .height = 1,
    },
    {
      .positionX = -3,
      .positionZ = -151,
      .sizeX = 1,
      .sizeZ = 1,
      .height = 2,
    },
    {
      .positionX = 16,
      .positionZ = -148,
      .sizeX = 11,
      .sizeZ = 4,
      .height = 2,
    },
    {
      .isEndOfArray = true,
    },
