    {
      .lim_sw_0 = {
        .min_hx = Q4(-52.0f),
        .max_hx = Q4(-28.0f),
        .min_hz = Q4(-160.0f),
        .max_hz = Q4(10.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-46.0f),
        .max_hx = Q4(-34.0f),
        .min_hz = Q4(-160.0f),
        .max_hz = Q4(10.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(6.0f),
      .lim_rd_min_hy_13 = Q4(-6.0f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(27.5f),
        .max_hx = Q4(45.0f),
        .min_hz = Q4(-160.0f),
        .max_hz = Q4(-40.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(33.5f),
        .max_hx = Q4(41.5f),
        .min_hz = Q4(-166.0f),
        .max_hz = Q4(-40.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(6.0f),
      .lim_rd_min_hy_13 = Q4(-6.0f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-40.0f),
        .max_hx = Q4(47.0f),
        .min_hz = Q4(-52.0f),
        .max_hz = Q4(-28.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-40.0f),
        .max_hx = Q4(47.0f),
        .min_hz = Q4(-46.0f),
        .max_hz = Q4(-34.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(6.0f),
      .lim_rd_min_hy_13 = Q4(-6.0f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-106.0f),
        .max_hx = Q4(41.0f),
        .min_hz = Q4(-172.0f),
        .max_hz = Q4(-148.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-106.0f),
        .max_hx = Q4(41.0f),
        .min_hz = Q4(-166.0f),
        .max_hz = Q4(-154.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(6.0f),
      .lim_rd_min_hy_13 = Q4(-6.0f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-71.4f),
        .max_hx = Q4(-65.3f),
        .min_hz = Q4(-176.0f),
        .max_hz = Q4(-173.5f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-61.2f),
        .max_hx = Q4(-61.2f),
        .min_hz = Q4(-175.2f),
        .max_hz = Q4(-175.2f),
      },
      .flags_10 = VC_RD_WARP_IN_OUT_FS,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_EVENT,
      .mv_y_type_11 = VC_MV_FIX_ANG,
      .lim_rd_max_hy_12 = Q4(3.4f),
      .lim_rd_min_hy_13 = Q4(-1.1f),
      .ofs_watch_hy_14 = Q4(1.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_FIX_ANG,
      .fix_ang_x_16 = Q8_ANGLE(346.0f),
      .fix_ang_y_17 = Q8_ANGLE(273.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-61.4f),
        .max_hx = Q4(-55.0f),
        .min_hz = Q4(6.1f),
        .max_hz = Q4(14.5f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-61.4f),
        .max_hx = Q4(-56.0f),
        .min_hz = Q4(6.1f),
        .max_hz = Q4(14.5f),
      },
      .flags_10 = VC_RD_WARP_IN_OUT_FS,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-2.7f),
      .lim_rd_min_hy_13 = Q4(-6.0f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-59.5f),
        .max_hx = Q4(-54.5f),
        .min_hz = Q4(0.2f),
        .max_hz = Q4(5.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-64.2f),
        .max_hx = Q4(-64.2f),
        .min_hz = Q4(2.63f),
        .max_hz = Q4(2.63f),
      },
      .flags_10 = VC_RD_WARP_IN_OUT_FS,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_EVENT,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-1.8f),
      .lim_rd_min_hy_13 = Q4(-1.8f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_FIX_ANG,
      .fix_ang_x_16 = Q8_ANGLE(346.0f),
      .fix_ang_y_17 = Q8_ANGLE(90.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-63.9f),
        .max_hx = Q4(-59.5f),
        .min_hz = Q4(0.2f),
        .max_hz = Q4(5.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-58.4f),
        .max_hx = Q4(-58.4f),
        .min_hz = Q4(1.2f),
        .max_hz = Q4(1.2f),
      },
      .flags_10 = VC_RD_WARP_IN_OUT_FS,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_EVENT,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-4.1f),
      .lim_rd_min_hy_13 = Q4(-4.1f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_FIX_ANG,
      .fix_ang_x_16 = Q8_ANGLE(311.0f),
      .fix_ang_y_17 = Q8_ANGLE(294.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-63.9f),
        .max_hx = Q4(-63.0f),
        .min_hz = Q4(5.0f),
        .max_hz = Q4(7.4f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-63.3f),
        .max_hx = Q4(-63.3f),
        .min_hz = Q4(1.4f),
        .max_hz = Q4(1.4f),
      },
      .flags_10 = VC_RD_WARP_IN_OUT_FS,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-2.0f),
      .lim_rd_min_hy_13 = Q4(-2.0f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_FIX_ANG,
      .fix_ang_x_16 = Q8_ANGLE(346.0f),
      .fix_ang_y_17 = Q8_ANGLE(359.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-54.5f),
        .max_hx = Q4(-40.0f),
        .min_hz = Q4(-0.4f),
        .max_hz = Q4(13.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-46.0f),
        .max_hx = Q4(-34.0f),
        .min_hz = Q4(-160.0f),
        .max_hz = Q4(10.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(6.0f),
      .lim_rd_min_hy_13 = Q4(-6.0f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-30.0f),
        .max_hx = Q4(-17.5f),
        .min_hz = Q4(-77.0f),
        .max_hz = Q4(-51.5f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-30.0f),
        .max_hx = Q4(-17.5f),
        .min_hz = Q4(-77.0f),
        .max_hz = Q4(-52.5f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(6.0f),
      .lim_rd_min_hy_13 = Q4(-6.0f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-8.5f),
        .max_hx = Q4(8.5f),
        .min_hz = Q4(-113.0f),
        .max_hz = Q4(-88.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-8.5f),
        .max_hx = Q4(8.5f),
        .min_hz = Q4(-113.0f),
        .max_hz = Q4(-88.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-2.5f),
      .lim_rd_min_hy_13 = Q4(-2.5f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-40.0f),
        .max_hx = Q4(-8.5f),
        .min_hz = Q4(-113.0f),
        .max_hz = Q4(-88.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-40.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(-109.0f),
        .max_hz = Q4(-91.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-2.5f),
      .lim_rd_min_hy_13 = Q4(-2.5f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(8.5f),
        .max_hx = Q4(40.0f),
        .min_hz = Q4(-113.0f),
        .max_hz = Q4(-88.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(40.0f),
        .min_hz = Q4(-109.0f),
        .max_hz = Q4(-95.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-2.5f),
      .lim_rd_min_hy_13 = Q4(-2.5f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-32.0f),
        .max_hx = Q4(-23.3f),
        .min_hz = Q4(-147.0f),
        .max_hz = Q4(-137.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-40.0f),
        .max_hx = Q4(-27.5f),
        .min_hz = Q4(-150.0f),
        .max_hz = Q4(-137.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-2.5f),
      .lim_rd_min_hy_13 = Q4(-2.5f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(46.5f),
        .max_hx = Q4(53.3f),
        .min_hz = Q4(-76.0f),
        .max_hz = Q4(-54.5f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(37.0f),
        .max_hx = Q4(45.0f),
        .min_hz = Q4(-67.0f),
        .max_hz = Q4(-51.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_EFFECT,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-1.1f),
      .lim_rd_min_hy_13 = Q4(-1.1f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(53.3f),
        .max_hx = Q4(56.0f),
        .min_hz = Q4(-76.0f),
        .max_hz = Q4(-69.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(50.5f),
        .max_hx = Q4(50.5f),
        .min_hz = Q4(-71.8f),
        .max_hz = Q4(-71.8f),
      },
      .flags_10 = VC_RD_WARP_OUT_F | VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_EFFECT,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-1.9f),
      .lim_rd_min_hy_13 = Q4(-1.9f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-16.0f),
        .max_hx = Q4(5.0f),
        .min_hz = Q4(-35.5f),
        .max_hz = Q4(-24.4f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-12.0f),
        .max_hx = Q4(39.0f),
        .min_hz = Q4(-45.0f),
        .max_hz = Q4(-24.2f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_EFFECT,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(6.0f),
      .lim_rd_min_hy_13 = Q4(-6.0f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(5.0f),
        .max_hx = Q4(39.0f),
        .min_hz = Q4(-31.5f),
        .max_hz = Q4(-24.2f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-12.0f),
        .max_hx = Q4(39.0f),
        .min_hz = Q4(-33.0f),
        .max_hz = Q4(-24.2f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_EFFECT,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.8f),
      .lim_rd_min_hy_13 = Q4(-1.8f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-18.0f),
        .max_hx = Q4(-6.0f),
        .min_hz = Q4(-22.0f),
        .max_hz = Q4(-6.3f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-18.0f),
        .max_hx = Q4(-6.0f),
        .min_hz = Q4(-33.0f),
        .max_hz = Q4(-6.3f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_EFFECT,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.8f),
      .lim_rd_min_hy_13 = Q4(-1.8f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(8.0f),
        .max_hx = Q4(22.0f),
        .min_hz = Q4(-22.0f),
        .max_hz = Q4(-4.5f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(8.0f),
        .max_hx = Q4(22.0f),
        .min_hz = Q4(-33.0f),
        .max_hz = Q4(-4.5f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_EFFECT,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.8f),
      .lim_rd_min_hy_13 = Q4(-1.8f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(32.5f),
        .max_hx = Q4(37.0f),
        .min_hz = Q4(-22.0f),
        .max_hz = Q4(-4.5f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(32.5f),
        .max_hx = Q4(37.0f),
        .min_hz = Q4(-33.0f),
        .max_hz = Q4(-4.5f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_EFFECT,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.8f),
      .lim_rd_min_hy_13 = Q4(-1.8f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(20.0f),
        .max_hx = Q4(34.5f),
        .min_hz = Q4(-4.2f),
        .max_hz = Q4(-7.8f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(17.0f),
        .max_hx = Q4(37.0f),
        .min_hz = Q4(-4.2f),
        .max_hz = Q4(-7.8f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_EFFECT,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.8f),
      .lim_rd_min_hy_13 = Q4(-1.8f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-174.0f),
        .max_hx = Q4(-153.0f),
        .min_hz = Q4(-21.5f),
        .max_hz = Q4(-10.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-174.0f),
        .max_hx = Q4(-153.0f),
        .min_hz = Q4(-21.5f),
        .max_hz = Q4(-10.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_EFFECT,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(6.0f),
      .lim_rd_min_hy_13 = Q4(-6.0f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_END_DATA_F,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
