
const char* g_MapMessages[] =
{
    #include "maps/shared/mapMsg_common.h"
    "~J0(5.5)\t",
    "~J0(2.8)\tDamn! ~N\n\t\t\tWhat's_that? ~E ",
    "~J0(1.2)\tHarry? ~E ",
    "~J1(2.6)\tLisa... ~N\n\t\t\tWhat's_the_matter_with_you? ",
    "~J1(1.8)\tI_get_it_now... ",
    "~J1(4.0)\tWhy_I'm_still_alive_even ~N\n\t\t\tthough_everyone_else's_dead. ",
    "~J1(4.0)\tI'm_not_the_only_one ~N\n\t\t\twho's_still_walking_around. ",
    "~J1(1.7)\tI'm_the_same_as_them. ",
    "~J1(2.8)\tI_just_hadn't_noticed_it_before. ~E ",
    "~J1(1.3)\tLisa? ",
    "~J1(3.6)\tStay_by_me,_Harry. ~N\n\t\t\tPlease. ",
    "~J1(3.3)\tI'm_so_scared. ~N\n\t\t\tHelp_me... ~E ",
    "~J0(2.4)\tSave_me_from_them. ",
    "~J0(4.0)\tPlease...__Harry... ~E ",
    "~J0(8.9)\t~E ",
    "\t\tSame_thing... ~E ",
    "~L4 ~C3 Investigation_stalled. ~N\n\t[PTV]_dealers_still_at_large. ~N\n\t~N\n\tSuspicious_deaths_continue. ~N\n\tLike_the_anti-drug_mayor, ~N\n\ta_narcotics_officer_dies_of ~N\n\ta_sudden_heart_failure_of ~N\n\tunknown_origin. ~E ",
    "\t\tAre_there_others? ~N\n\t\tIt's_pretty_old... ",
    "~L4 ~C3 Fire_broke_out_in_town. ~N\n\t6_homes_destroyed. ~N\n\t~N\n\tCharred_body ~N\n\tof_Alessa_Gillespie(7) ~N\n\tfound_in_aftermath. ~N\n\t~N\n\tCause_of_fire_currently_under ~N\n\tinvestigation. ",
    "~L4 ~C3 Investigations_show_source ~N\n\tas_basement_of_Gillespie_home. ~N\n\tBlaze_now_believed_caused_by ~N\n\tmalfunction_of_antiquated ~N\n\tboiler. ~E ",
    "\tThe_date_of_the_blaze... ",
    "\tit's_the_same_day ~N\n\twe_found_Cheryl! ~E ",
    "\tThere's_a_place_mark ~N\n\tin_the_book... ~E ",
    "~L4 ~C3 WHITE_CLAUDIA. ~N\n\t~N\n\tPerennial_herb_found_near_water. ~N\n\tReaches_height_of_10_to_15_in. ~N\n\tOblong_leaves,_white_blossoms. ",
    "~L4 ~C3 Seeds_contain_hallucinogen. ~N\n\tAncient_records_show_it_was ~N\n\tused_for_religious_ceremonies. ~N\n\tThe_hallucinogenic_effect ~N\n\twas_key. ~E ",
    "~L4 ~C3 Ask_doctor_to_let_me_quit_being ~N\n\tin_charge_of_that_patient. ~N\n\t~N\n\tIt's_too_weird. ~E ",
    "~L4 ~C3 The_room_is_filled_with_insects. ~N\n\t~N\n\tEven_with_doors ~N\n\tand_windows_shut ~N\n\tthey_get_in_to_spite_me. ~N\n\t~N\n\tTo_the_hospital... ~E ",
    "~L4 ~C3 Still_alive, ~N\n\tbut_with_wounds_that_won't_heal. ~E ",
    "~L4 ~C3 Blood_and_pus_flow_from ~N\n\tthe_bathroom_faucet. ~N\n\t~N\n\tI_try_to_stop_it, ~N\n\tbut_it_won't_turn_off. ~E ",
    "~L4 ~C3 Feeling_bad. ~N\n\tNeed_to_throw_up. ~N\n\tBut_nothing_comes_out. ~N\n\tVomiting_only_bile. ~E ",
    "~L4 ~C3\tNeed_drug. ~E ",
    "~L4 ~C3 Told_the_doctor_I_quit. ~N\n\tWon't_work_at_that ~N\n\thospital_anymore. ~E ",
    "~L4 ~C3\tHelp_me... ~E ",
    "\tUsed_the_ ~C2 Key_of_[Ophiel] ~C7 . ~E ",
    "\tUsed_the_ ~C2 Key_of_[Hagith] ~C7 . ~E ",
    "\tUsed_the_ ~C2 Key_of_[Phaleg] ~C7 . ~E ",
    "\tThere_is_a_ ~C2 Ring_of_contract ~C7 . ~N\n\tTake_it? ~S4 ",
    "\tThere_are_ ~C2 Pliers ~C7 . ~N\n\tTake_them? ~S4 ",
    "\tThere_is_a_ ~C2 Screwdriver ~C7 . ~N\n\tTake_it? ~S4 ",
    "\tThere_is_a_ ~C2 Bird_cage_key ~C7 . ~N\n\tTake_it? ~S4 ",
    "\tThere_is_a_ ~C2 Camera ~C7 . ~N\n\tTake_it? ~S4 ",
    "\tThere_is_a_ ~C2 Stone_of_time ~C7 . ~N\n\tTake_it? ~S4 ",
    "\tThere_is_a_ ~C2 Key_of_[Ophiel] ~C7 . ~N\n\tTake_it? ~S4 ",
    "\tThere_is_a_ ~C2 Key_of_[Hagith] ~C7 . ~N\n\tTake_it? ~S4 ",
    "\tThere_is_a_ ~C2 Key_of_[Phaleg] ~C7 . ~N\n\tTake_it? ~S4 ",
    "\tThere_is_an_ ~C2 Amulet_of_Solomon ~C7 . ~N\n\tTake_it? ~S4 ",
    "\tThere_is_a_ ~C2 Crest_of_Mercury ~C7 . ~N\n\tTake_it? ~S4 ",
    "~C3\tGo_home. ",
    "~C3\tThief. ",
    "~C3\tDrop_dead. ~E ",
    "\tOld_clock. ~N\n\tThere_is_a_square_hole ~N\n\tin_the_center_of_the_clock. ",
    "\tThe_hands_of_the_clock ~N\n\t...it's_a_key. ",
    "\tI_can't_get_to_it_because ~N\n\tof_the_glass_cover. ~E ",
    "\tThere_is_a_key_in_the_faucet, ",
    "\tbut_I_can't_get_it_out_no_matter ~N\n\thow_much_I_pull. ~E ",
    "\tThere_is_a_slate. ~E ",
    "~C3\tNames_engraved ~N\n\t\tOn_a_lithograph. ~N\n\t\tThe_Grim_Reaper's_list. ",
    "~C3\tYes,_the_headcount_is_set ~N\n\t\tYoung_and_old_lined_up ~N\n\t\tIn_order_of_age. ",
    "~C3\tThen,_the_pathway_opens ~N\n\t\tAwaiting_them,_the_frenzied ~N\n\t\tUproar,_the_feast_of_death! ~E ",
    "\tThere_is_a_key. ",
    "\tElectricity_is_flowing_to_the_key. ~N\n\tI'll_get_shocked_if_I_grab_it_now. ~E ",
    "~C3\tThe_light_to_the_future. ~E ",
    "~C3\tThe_light_illuminating ~N\n\tthe_darkness. ~E ",
    "\tThe_bird_cage_is_locked._~E ",
    "\tUsed_the_ ~C2 Bird_cage_key ~C7 . ~E ",
    "\tBird_cage._It's_empty. ~E ",
    "\tIt's_locked. ",
    "\tThe_word,_[Ophiel] ~N\n\tis_carved_on_the_door. ~E ",
    "\tIt's_locked. ",
    "\tThe_word,_[Hagith] ~N\n\tis_carved_on_the_door. ~E ",
    "\tIt's_locked. ",
    "\tThe_word,_[Phaleg] ~N\n\tis_carved_on_the_door. ~E ",
    "\tA_steel_plate ~N\n\tis_screwed_to_the_wall. ~E ",
    "\tThe_elevator_doesn't ~N\n\tappear_to_be_working. ~E ",
    "\tThere's_a_clock ~N\n\twith_a_broken_face. ~E ",
    "\tNone_of_this_stuff_is_of_any_use. ~E ",
    "\tJust_a_wall. ~E ",
    "\tThere_is_a_diary_on_the_floor. ~E ",
    "\tNothing_helpful. ~E ",
    "\tLooks_like_an_altar. ~N\n\tWonder_what_they_worship? ~E ",
    "\tA_body_is_laid_out_on_the_bed. ~N\n\tDon't_feel_like_checking_this_out. ~E ",
    "\tThere's_a_botanical ~N\n\treference_book. ~N\n\tDon't_need_to_read_it_now. ~E ",
};
