#include "bodyprog/bodyprog.h"
#include "bodyprog/math/math.h"
#include "maps/map7/map7_s01.h"
#include "maps/particle.h"
#include "maps/characters/player.h"
#include "maps/characters/bloody_lisa.h"
#include "maps/characters/ghost_child_alessa.h"
#include "maps/characters/lisa.h"
#include "maps/characters/puppet_nurse.h"

extern s_AnimInfo HARRY_M7S01_ANIM_INFOS[];

void (*g_LoadScreenFuncs[])() = {
    NULL,
    GameBoot_LoadScreen_PlayerRun,
    GameBoot_LoadScreen_BackgroundImg,
    GameBoot_LoadScreen_StageString
};

s_MapPoint2d MAP_POINTS[] = {
#include "map_points.h"
};

void (*g_MapEventFuncs[])() = {
    func_800D8230,
    func_800D82C4,
    func_800D8358,
    MapEvent_CommonItemTake,
    func_800D84AC,
    func_800D8540,
    func_800D85D4,
    MapEvent_KeyOfOphielUse,
    MapEvent_KeyOfHagithUse,
    MapEvent_KeyOfPhalegUse,
    func_800D889C,
    func_800D8958,
    MapEvent_BirdCageKeyUse,
    func_800D89D8,
    func_800D8A30,
    func_800D8A5C,
    func_800D8DB4,
    func_800D8FCC,
    func_800D8FF8,
    func_800D93BC,
    func_800D93E8,
    func_800D9414,
    func_800D9440,
    func_800D946C,
    func_800D94A4,
    func_800D94DC,
    func_800D99DC,
    func_800D725C,
    func_800D7A60,
    func_800D9A08,
    func_800D9C9C,
    func_800DAB64,
    func_800DAD7C,
    func_800DADA8,
    MapEvent_CutsceneCherylRedirect3,
    func_800DAE00,
    func_800DB13C,
    func_800DB1F0,
    func_800DB31C,
    func_800DB3D0,
    sharedFunc_800DB60C_7_s01,
    func_800DBDE0,
    func_800DC028,
    func_800DC080,
    sharedFunc_800D15F0_3_s01,
    func_800DCE20,
    func_800D8A04
};

const s_MapOverlayHeader g_MapOverlayHeader = {
    .mapInfo                        = &MAP_INFOS[MapType_ER2],
    .mapRoomIdxGet              = Map_RoomIdxGet,
    .field_8                          = NO_VALUE,
    .func_C                           = sharedFunc_800D929C_0_s00,
    .bgmEvent                      = func_800D6810,
    .bgmIdx                        = BgmTrackIdx_1,
    .ambientAudioIdx               = 37,
    .field_16                         = 2,
    .field_17                         = 6,
    .loadingScreenFuncs            = g_LoadScreenFuncs,
    .mapPoints           = MAP_POINTS,
    .mapEventFuncs                 = g_MapEventFuncs,
    .mapEvents                     = MAP_EVENTS,
    .field_28                         = &g_SysWork.npcBoneCoords[0],
    .loadableItems                 = LOADABLE_INVENTORY_ITEMS,
    .mapMessages                   = MAP_MESSAGES,
    .harryMapAnimInfos                     = HARRY_M7S01_ANIM_INFOS,
    .field_38                         = g_MapHeaderTable_38,
    .initWorldObjects              = Map_WorldObjectsInit,
    .updateWorldObjects            = Map_WorldObjectsUpdate,
    .func_44                          = NULL,
    .npcSpawnEvent                 = func_800DEDA4,
    .unkTable1_4C                     = sharedData_800DFB7C_0_s00,
    .unkTable1Count_50                = ARRAY_SIZE(sharedData_800DFB7C_0_s00),
    .bloodSplats                   = g_Effect_BloodSplats,
    .bloodSplatCount               = ARRAY_SIZE(g_Effect_BloodSplats),
    .field_5C                         = NULL,
    .func_60                          = NULL,
    .func_64                          = NULL,
    .func_68                          = NULL,
    .func_6C                          = NULL,
    .func_70                          = NULL,
    .func_74                          = NULL,
    .func_78                          = NULL,
    .field_7C                         = NULL,
    .func_80                          = NULL,
    .func_84                          = NULL,
    .func_88                          = sharedData_800DFB10_0_s01,
    .func_8C                          = sharedFunc_800CD1F8_0_s01,
    .func_90                          = NULL,
    .field_94                         = NULL,
    .func_98                          = NULL,
    .func_9C                          = NULL,
    .ptr_A0                           = NULL,
    .func_A4                          = NULL,
    .func_A8                          = NULL,
    .func_AC                          = NULL,
    .func_B0                          = NULL,
    .func_B4                          = NULL,
    .func_B8                          = sharedFunc_800CDAA8_0_s02,
    .func_BC                          = sharedFunc_800D1C38_0_s00,
    .func_C0                          = sharedFunc_800D209C_0_s00,
    .playerMatchArmAnimDisable     = Player_MatchArmAnimDisable,
    .playerControlFreeze           = Player_ControlFreeze,
    .playerControlUnfreeze         = Player_ControlUnfreeze,
    .func_D0                          = sharedFunc_800D23EC_0_s00,
    .func_D4                          = sharedFunc_800D2C7C_0_s00,
    .func_D8                          = sharedFunc_800D2D2C_0_s00,
    .playerAnimLock                = Player_AnimLock,
    .isPlayerAnimLocked            = Player_AnimIsLocked,
    .playerAnimUnlock              = Player_AnimUnlock,
    .func_E8                          = sharedFunc_800D2DAC_0_s00,
    .playerMoveDistIsZero          = Player_MoveDistanceIsZero,
    .playerMoveDistClear           = Player_MoveDistanceClear,
    .playerFallBackward            = Player_FallBackward,
    .func_F8                          = sharedFunc_800D2E7C_0_s00,
    .playerDamageFeetFront         = Player_DamageFeetFront,
    .func_100                         = sharedFunc_800D2E8C_0_s00,
    .func_104                         = sharedFunc_800D2E6C_0_s00,
    .func_108                         = sharedFunc_800D2E94_0_s00,
    .func_10C                         = sharedFunc_800D2EB4_0_s00,
    .func_110                         = sharedFunc_800D2EF4_0_s00,
    .func_114                         = sharedFunc_800D2EA4_0_s00,
    .func_118                         = sharedFunc_800D2E9C_0_s00,
    .func_11C                         = sharedFunc_800D88AC_0_s00,
    .func_120                         = sharedFunc_800D88C0_0_s00,
    .func_124                         = sharedFunc_800D8904_0_s00,
    .playerRunTimerReset                         = Player_RunTimerReset,
    .charaLock                         = Chara_Lock,
    .charaIsLockedCheck                         = Chara_IsLockedCheck,
    .charaUnlock                         = Chara_Unlock,
    .charaAnimPlaybackStateGet                         = Chara_AnimPlaybackStateGet,
    .func_13C                         = sharedFunc_800D8A00_0_s00,
    .charaVisibleSet                         = Chara_VisibleSet,
    .charaInvisibleSet                         = Chara_InvisibleSet,
    .func_148                         = sharedFunc_800D908C_0_s00,
    .func_14C                         = sharedFunc_800D9188_0_s00,
    .charaAnimStartKeyframeIdxGet      = Chara_AnimStartKeyframeIdxGet,
    .func_154                         = sharedFunc_800D923C_0_s00,
    .func_158                         = NULL,
    .func_15C                         = NULL,
    .func_160                         = NULL,
    .func_164                         = NULL,
    .particlesUpdate              = Particle_SystemUpdate,
    .enviromentSet                = sharedFunc_800D08B8_0_s00,
    .func_170                         = sharedFunc_800D0A60_0_s00,
    .func_174                         = sharedFunc_800D0B18_0_s00,
    .particleHyperBlasterBeamDraw = Particle_HyperBlasterBeamDraw,
    .particleBeamDraw             = Particle_BeamDraw,
    .particleSoundStop            = Particle_SoundStop,
    .windSpeedX                   = &g_Particle_SpeedX,
    .windSpeedZ                   = &g_Particle_SpeedZ,
    .data_18C                         = &sharedData_800DFB6C_0_s00,
    .data_190                         = &sharedData_800DFB70_0_s00,
    .charaUpdateFuncs             = {
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        Ai_PuppetNurse_Update, Ai_PuppetNurse_Update, Ai_PuppetDoctor_Update, Ai_PuppetDoctor_Update, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        Ai_Lisa_Update, Ai_BloodyLisa_Update, NULL, Ai_GhostChildAlessa_Update },
    .charaGroupIds = {},
    .charaSpawns   = {
#include "chara_spawns.h"
    },
    .cameraPaths = {
#include "vc_road_data.h"
    },
    .triggerZones = {
#include "header_field_D2C.h"
    },
};
