#include "bodyprog/bodyprog.h"

s_EventParam D_800E0B64[203] = {
    {
        .disabledEventFlag_2  = EventFlag_M7S01_RifleShells,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 170,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 3, // `MapEvent_CommonItemTake`
    },
    {
        .disabledEventFlag_2  = EventFlag_M7S01_HandgunBullets0,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 171,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 3, // `MapEvent_CommonItemTake`
    },
    {
        .disabledEventFlag_2  = EventFlag_M7S01_HealthDrink0,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 172,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 3, // `MapEvent_CommonItemTake`
    },
    {
        .disabledEventFlag_2  = EventFlag_M7S01_HandgunBullets1,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 173,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 3, // `MapEvent_CommonItemTake`
    },
    {
        .disabledEventFlag_2  = EventFlag_M7S01_ShotgunShells,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 174,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 3, // `MapEvent_CommonItemTake`
    },
    {
        .disabledEventFlag_2  = EventFlag_M7S01_FirstAidKit,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 175,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 3, // `MapEvent_CommonItemTake`
    },
    {
        .disabledEventFlag_2  = EventFlag_M7S01_HandgunBullets2,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 176,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 3, // `MapEvent_CommonItemTake`
    },
    {
        .disabledEventFlag_2  = EventFlag_M7S01_HealthDrink1,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 177,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 3, // `MapEvent_CommonItemTake`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 140,
        .sysState_8_0         = SysState_SaveMenu1,
        .eventData_8_5        = 22,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 141,
        .sysState_8_0         = SysState_SaveMenu1,
        .eventData_8_5        = 22,
    },
    {
        .requiredEventFlag_0 = EventFlag_473,
        .disabledEventFlag_2 = EventFlag_479,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_EventCallFunc,
        .eventData_8_5       = 45, // `func_800DCE20`
    },
    {
        .requiredEventFlag_0 = EventFlag_479,
        .disabledEventFlag_2 = EventFlag_480,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_LoadRoom,
        .eventData_8_5       = 4,
        .field_8_24          = 1,
        .mapOverlayIdx_8_25  = MapOverlayId_MAP2_S04,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 3,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 88,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 4,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 88,
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupKeyOfPhaleg,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 118,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 46, // `func_800D8A04`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupKeyOfPhaleg,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 119,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 46, // `func_800D8A04`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupKeyOfPhaleg,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 120,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 46, // `func_800D8A04`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupKeyOfPhaleg,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 121,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 46, // `func_800D8A04`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_491,
        .disabledEventFlag_2  = EventFlag_M7S01_PickupKeyOfPhaleg,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 118,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 13, // `func_800D89D8`
    },
    {
        .requiredEventFlag_0  = EventFlag_491,
        .disabledEventFlag_2  = EventFlag_M7S01_PickupKeyOfPhaleg,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 119,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 13, // `func_800D89D8`
    },
    {
        .requiredEventFlag_0  = EventFlag_491,
        .disabledEventFlag_2  = EventFlag_M7S01_PickupKeyOfPhaleg,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 120,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 13, // `func_800D89D8`
    },
    {
        .requiredEventFlag_0  = EventFlag_491,
        .disabledEventFlag_2  = EventFlag_M7S01_PickupKeyOfPhaleg,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 121,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 13, // `func_800D89D8`
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupBirdCageKey,
        .disabledEventFlag_2  = EventFlag_491,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 118,
        .requiredItemId_6     = InventoryItemId_BirdCageKey,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 12, // `MapEvent_BirdCageKeyUse`
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupBirdCageKey,
        .disabledEventFlag_2  = EventFlag_491,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 118,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 12, // `MapEvent_BirdCageKeyUse`
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupBirdCageKey,
        .disabledEventFlag_2  = EventFlag_491,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 119,
        .requiredItemId_6     = InventoryItemId_BirdCageKey,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 12, // `MapEvent_BirdCageKeyUse`
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupBirdCageKey,
        .disabledEventFlag_2  = EventFlag_491,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 119,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 12, // `MapEvent_BirdCageKeyUse`
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupBirdCageKey,
        .disabledEventFlag_2  = EventFlag_491,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 120,
        .requiredItemId_6     = InventoryItemId_BirdCageKey,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 12, // `MapEvent_BirdCageKeyUse`
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupBirdCageKey,
        .disabledEventFlag_2  = EventFlag_491,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 120,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 12, // `MapEvent_BirdCageKeyUse`
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupBirdCageKey,
        .disabledEventFlag_2  = EventFlag_491,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 121,
        .requiredItemId_6     = InventoryItemId_BirdCageKey,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 12, // `MapEvent_BirdCageKeyUse`
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupBirdCageKey,
        .disabledEventFlag_2  = EventFlag_491,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 121,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 12, // `MapEvent_BirdCageKeyUse`
    },
    {
        .disabledEventFlag_2  = EventFlag_491,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 118,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 11, // `func_800D8958`
    },
    {
        .disabledEventFlag_2  = EventFlag_491,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 119,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 11, // `func_800D8958`
    },
    {
        .disabledEventFlag_2  = EventFlag_491,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 120,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 11, // `func_800D8958`
    },
    {
        .disabledEventFlag_2  = EventFlag_491,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 121,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 11, // `func_800D8958`
    },
    {
        .disabledEventFlag_2  = EventFlag_490,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 117,
        .requiredItemId_6     = InventoryItemId_Pliers,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 15, // `func_800D8A5C`
    },
    {
        .disabledEventFlag_2  = EventFlag_490,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 117,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 14, // `func_800D8A30`
    },
    {
        .requiredEventFlag_0  = EventFlag_490,
        .disabledEventFlag_2  = EventFlag_525,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 103,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 16, // `func_800D8DB4`
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupKeyOfHagith,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 116,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 89,
    },
    {
        .requiredEventFlag_0  = EventFlag_489,
        .disabledEventFlag_2  = EventFlag_M7S01_PickupKeyOfHagith,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 116,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 19, // `func_800D93BC`
    },
    {
        .disabledEventFlag_2  = EventFlag_489,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 116,
        .requiredItemId_6     = InventoryItemId_StoneOfTime,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 18, // `func_800D8FF8`
    },
    {
        .disabledEventFlag_2  = EventFlag_489,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 116,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 17, // `func_800D8FCC`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 122,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 20, // `func_800D93E8`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 123,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 20, // `func_800D93E8`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 124,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 20, // `func_800D93E8`
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupScrewdriver,
        .disabledEventFlag_2  = EventFlag_M7S01_PickupPliers,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 105,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 21, // `func_800D9414`
    },
    {
        .disabledEventFlag_2  = EventFlag_M7S01_PickupPliers,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 104,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 21, // `func_800D9414`
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupPliers,
        .disabledEventFlag_2  = EventFlag_M7S01_PickupScrewdriver,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 107,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 22, // `func_800D9440`
    },
    {
        .disabledEventFlag_2  = EventFlag_M7S01_PickupScrewdriver,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 106,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 22, // `func_800D9440`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 115,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 23, // `func_800D946C`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 114,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 24, // `func_800D94A4`
    },
    {
        .disabledEventFlag_2  = EventFlag_488,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 108,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 25, // `func_800D94DC`
    },
    {
        .disabledEventFlag_2  = EventFlag_M7S01_PickupAmuletOfSolomon,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 113,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 26, // `func_800D99DC`
    },
    {
        .requiredEventFlag_0 = EventFlag_481,
        .disabledEventFlag_2 = EventFlag_482,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_EventCallFunc,
        .eventData_8_5       = 27, // `func_800D725C`
    },
    {
        .requiredEventFlag_0 = EventFlag_482,
        .disabledEventFlag_2 = EventFlag_483,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_Fmv,
        .eventData_8_5       = 5,
        .flags_8_13          = 2,
    },
    {
        .requiredEventFlag_0 = EventFlag_483,
        .disabledEventFlag_2 = EventFlag_484,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_EventCallFunc,
        .eventData_8_5       = 28, // `func_800D7A60`
    },
    {
        .requiredEventFlag_0 = EventFlag_484,
        .disabledEventFlag_2 = EventFlag_569,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_LoadRoom,
        .eventData_8_5       = 169,
    },
    {
        .requiredEventFlag_0  = EventFlag_569,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 112,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 29, // `func_800D9A08`
    },
    {
        .disabledEventFlag_2  = EventFlag_500,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 127,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 30, // `func_800D9C9C`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_501,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 128,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 30, // `func_800D9C9C`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_502,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 129,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 30, // `func_800D9C9C`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_503,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 130,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 30, // `func_800D9C9C`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_504,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 131,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 30, // `func_800D9C9C`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_505,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 132,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 30, // `func_800D9C9C`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_506,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 133,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 30, // `func_800D9C9C`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_487,
        .disabledEventFlag_2  = EventFlag_M7S01_PickupStoneOfTime,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 98,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 31, // `func_800DAB64`
    },
    {
        .requiredEventFlag_0  = EventFlag_487,
        .disabledEventFlag_2  = EventFlag_M7S01_PickupStoneOfTime,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 99,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 31, // `func_800DAB64`
    },
    {
        .requiredEventFlag_0  = EventFlag_487,
        .disabledEventFlag_2  = EventFlag_M7S01_PickupStoneOfTime,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 100,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 31, // `func_800DAB64`
    },
    {
        .requiredEventFlag_0  = EventFlag_487,
        .disabledEventFlag_2  = EventFlag_M7S01_PickupStoneOfTime,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 101,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 31, // `func_800DAB64`
    },
    {
        .disabledEventFlag_2  = EventFlag_M7S01_PickupCrestOfMercury,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 134,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 32, // `func_800DAD7C`
    },
    {
        .disabledEventFlag_2  = EventFlag_M7S01_PickupCrestOfMercury,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 135,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 32, // `func_800DAD7C`
    },
    {
        .disabledEventFlag_2  = EventFlag_M7S01_PickupCrestOfMercury,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 136,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 32, // `func_800DAD7C`
    },
    {
        .disabledEventFlag_2  = EventFlag_M7S01_PickupRingOfContract,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 137,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 33, // `func_800DADA8`
    },
    {
        .disabledEventFlag_2  = EventFlag_M7S01_PickupRingOfContract,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 138,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 33, // `func_800DADA8`
    },
    {
        .disabledEventFlag_2  = EventFlag_M7S01_PickupRingOfContract,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 139,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 33, // `func_800DADA8`
    },
    {
        .disabledEventFlag_2  = EventFlag_M7S01_PickupCamera,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 97,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 34, // `func_800DADD4`
    },
    {
        .disabledEventFlag_2  = EventFlag_486,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 111,
        .requiredItemId_6     = InventoryItemId_Screwdriver,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 35, // `func_800DAE00`
    },
    {
        .requiredEventFlag_0  = EventFlag_486,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 111,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 36, // `func_800DB13C`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 111,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 87,
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0 = EventFlag_561,
        .disabledEventFlag_2 = EventFlag_562,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_EventCallFunc,
        .eventData_8_5       = 37, // `func_800DB1F0`
    },
    {
        .disabledEventFlag_2  = EventFlag_496,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 125,
        .requiredItemId_6     = InventoryItemId_Camera,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 39, // `func_800DB3D0`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_497,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 126,
        .requiredItemId_6     = InventoryItemId_Camera,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 39, // `func_800DB3D0`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_496,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 125,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 38, // `func_800DB31C`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_497,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 126,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 38, // `func_800DB31C`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_M5S03_SeenSecondNewspaper,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 110,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 41, // `func_800DBDE0`
    },
    {
        .requiredEventFlag_0  = EventFlag_477,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 109,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 42, // `func_800DC028`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 109,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 96,
    },
    {
        .disabledEventFlag_2  = EventFlag_M7S01_PickupBirdCageKey,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 96,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 43, // `func_800DC080`
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupKeyOfHagith,
        .disabledEventFlag_2  = EventFlag_531,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 5,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 8, // `MapEvent_KeyOfHagithUse`
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupKeyOfHagith,
        .disabledEventFlag_2  = EventFlag_531,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 5,
        .requiredItemId_6     = InventoryItemId_KeyOfHagith,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 8, // `MapEvent_KeyOfHagithUse`
    },
    {
        .requiredEventFlag_0  = EventFlag_531,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 5,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 13,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_531,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 13,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 5,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 5,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 5, // `func_800D8540`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 5,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 1, // `func_800D82C4`
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 6,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 16,
        .field_8_19           = 12,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 16,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 6,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 7,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 17,
        .field_8_19           = 12,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 17,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 7,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 8,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 18,
        .field_8_19           = 12,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 18,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 8,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 9,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 19,
        .field_8_19           = 14,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 19,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 9,
        .field_8_19           = 14,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_546,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 10,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 30,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_546,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 30,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 10,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_546,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 30,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 2, // `func_800D8358`
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 10,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 1, // `func_800D82C4`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_525,
        .disabledEventFlag_2  = EventFlag_530,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 11,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 7, // `MapEvent_KeyOfOphielUse`
    },
    {
        .requiredEventFlag_0  = EventFlag_525,
        .disabledEventFlag_2  = EventFlag_530,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 11,
        .requiredItemId_6     = InventoryItemId_KeyOfOphiel,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 7, // `MapEvent_KeyOfOphielUse`
    },
    {
        .requiredEventFlag_0  = EventFlag_530,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 11,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 53,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S01,
    },
    {
        .requiredEventFlag_0  = EventFlag_530,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 53,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 11,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S01,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 11,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 4, // `func_800D84AC`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 11,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 1, // `func_800D82C4`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupKeyOfPhaleg,
        .disabledEventFlag_2  = EventFlag_532,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 12,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 9, // `MapEvent_KeyOfPhalegUse`
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupKeyOfPhaleg,
        .disabledEventFlag_2  = EventFlag_532,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 12,
        .requiredItemId_6     = InventoryItemId_KeyOfPhaleg,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 9, // `MapEvent_KeyOfPhalegUse`
    },
    {
        .requiredEventFlag_0  = EventFlag_532,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 12,
        .sysState_8_0         = SysState_LoadOverlay,
        .eventData_8_5        = 71,
        .field_8_19           = 12,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP7_S02,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 12,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 6, // `func_800D85D4`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 12,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 1, // `func_800D82C4`
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 20,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 26,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 24,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 21,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 23,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 44, // `sharedFunc_800D15F0_3_s01`
    },
    {
        .disabledEventFlag_2  = EventFlag_213,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 14,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 22,
        .field_8_19           = 7,
    },
    {
        .disabledEventFlag_2  = EventFlag_213,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 93,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 22,
        .field_8_19           = 7,
    },
    {
        .disabledEventFlag_2  = EventFlag_214,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 46,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 22,
        .field_8_19           = 7,
    },
    {
        .disabledEventFlag_2  = EventFlag_214,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 94,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 22,
        .field_8_19           = 7,
    },
    {
        .disabledEventFlag_2  = EventFlag_215,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 66,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 22,
        .field_8_19           = 7,
    },
    {
        .disabledEventFlag_2  = EventFlag_215,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 95,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 22,
        .field_8_19           = 7,
    },
    {
        .requiredEventFlag_0 = EventFlag_217,
        .disabledEventFlag_2 = EventFlag_221,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_LoadRoom,
        .eventData_8_5       = 93,
    },
    {
        .requiredEventFlag_0 = EventFlag_218,
        .disabledEventFlag_2 = EventFlag_222,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_LoadRoom,
        .eventData_8_5       = 94,
    },
    {
        .requiredEventFlag_0 = EventFlag_219,
        .disabledEventFlag_2 = EventFlag_561,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_LoadRoom,
        .eventData_8_5       = 95,
        .flags_8_13          = 2,
        .field_8_24          = 1,
    },
    {
        .requiredEventFlag_0 = EventFlag_219,
        .disabledEventFlag_2 = EventFlag_223,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_LoadRoom,
        .eventData_8_5       = 95,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 25,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 27,
        .field_8_19           = 12,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 27,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 25,
        .field_8_19           = 12,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 28,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 29,
        .field_8_19           = 12,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 29,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 28,
        .field_8_19           = 12,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 31,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 39,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 39,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 31,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 32,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 51,
        .field_8_19           = 12,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 51,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 32,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 33,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 52,
        .field_8_19           = 12,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 52,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 33,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 40,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 48,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 48,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 40,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 41,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 49,
        .field_8_19           = 12,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 49,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 41,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 54,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 62,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S01,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 62,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 54,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S01,
    },
    {
        .requiredEventFlag_0  = EventFlag_488,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 55,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 63,
        .field_8_19           = 12,
    },
    {
        .requiredEventFlag_0  = EventFlag_488,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 63,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 55,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 55,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 1, // `func_800D82C4`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_M7S01_PickupAmuletOfSolomon,
        .disabledEventFlag_2  = EventFlag_481,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 65,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 92,
        .field_8_19           = 13,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 64,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 65,
        .field_8_19           = 13,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 65,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 64,
        .field_8_19           = 13,
    },
    {
        .requiredEventFlag_0  = EventFlag_492,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 67,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 69,
        .field_8_19           = 12,
    },
    {
        .requiredEventFlag_0  = EventFlag_492,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 69,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 67,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_493,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 67,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 40, // `sharedFunc_800DB60C_7_s01`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_494,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 68,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 70,
        .field_8_19           = 12,
    },
    {
        .requiredEventFlag_0  = EventFlag_494,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 70,
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 68,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_495,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 68,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 40, // `sharedFunc_800DB60C_7_s01`
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 34,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 35,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 36,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 37,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 38,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 42,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 43,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 44,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 45,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 50,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 56,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 57,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 58,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 59,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 60,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 61,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 89,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 90,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 142,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 90,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 143,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 91,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 144,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 93,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 145,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 93,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 146,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 93,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 147,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 93,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 148,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 94,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 149,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 94,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 150,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 94,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 151,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 95,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 152,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 95,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 153,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 95,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 154,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 95,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 155,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 95,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 156,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 95,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 157,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 95,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 158,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 95,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 159,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 95,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 160,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 95,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 161,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 95,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 162,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 95,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 163,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 95,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 164,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 95,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 165,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 95,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 166,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 95,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 167,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 95,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 168,
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 95,
    },
    {
        .triggerType_4_0 = TriggerType_EndOfArray,
    },
};
