
const char* g_MapMessages[] =
{
    #include "maps/shared/mapMsg_common.h"
    "~J0(8.7)\t~E ",
    "~J0(1.2)\tAre_you_OK? ~E ",
    "~J0(1.4)\tYeah,_I_guess_so. ",
    "~J0(3.0)\tBut_I'm_beat. ~N\n\t\t\tI_thought_I_was_a_goner_there. ~E ",
    "~J1(3.0)\tSo,_how'd_it_go? ~N\n\t\t\tDid_you_find_a_way_out? ",
    "~J1(2.4)\tNo._Not_yet. ",
    "~J1(1.1)\tHow_about_you? ",
    "~J1(1.0)\tZip. ",
    "~J1(1.8)\tBut_it's_too_soon_to_give_up. ",
    "~J1(2.8)\tThis_craziness_can't ~N\n\t\t\tgo_on_forever. ",
    "~J1(3.4)\tA_military_rescue_squad ~N\n\t\t\tshould_be_here_any_time_now. ",
    "~J1(2.8)\tIf_they_come_through_the_town, ~N\n\t\t\twe're_home_free. ",
    "~J1(1.7)\tI_hope_so. ",
    "~J1(1.4)\tI_better_get_going. ",
    "~J1(3.4)\tThis_isn't_the_time_to_stand ~N\n\t\t\taround_flapping_our_gums. ~E ",
    "~J0(2.0)\tDo_you_know ~N\n\t\t\ta_girl_called_Alessa? ~E ",
    "~J0(1.0)\tNo. ~E ",
    "\tKaufmann_must_have_dropped ~N\n\tthis. ",
    "\tLooks_like_it's_full_of_stuff... ~E ",
    "\tWhat_is_this? ~N\n\tDrugs? ~E ",
    "~C3\tAugust_20 ",
    "~C3\tHe_came_by._I_handed_over_the ~N\n\t\tpackage_that_the_woman_left_here. ",
    "~C3\tSeptember_12 ",
    "~C3\tHe_showed_up_at_Norman's,_too. ",
    "~C3\tDon't_want_to_be_involved_with ~N\n\t\tthe_likes_of_them_anymore,_but... ",
    "~C3\tI'm_getting_creeped_out ~N\n\t\teven_more_than_before. ",
    "~C3\tThought_of_leaving_town,_but ~N\n\t\tI'm_afraid_of_what_will_happen ~N\n\t\tif_I_do. ~E ",
    "~C3\t3_loaves_of_bread. ~N\n\t\t3_cartons_of_milk. ~N\n\t\t2_dozen_eggs. ",
    "~C3\tDeliver_to_back_door_daily_8_a.m. ~N\n\t\tRear_entrance_code_0886 ~N\n\t\t________________________Norman_Young ~E ",
    "~C3\tNorman's_Grand_Opening. ~E ",
    "\tThere_is_a_drawer. ~N\n\tDo_you_want_to_open_it? ~S4 ",
    "\tUsed_the_ ~C2 Safe_key ~C7 . ~E ",
    "\tThere_is_a_ ~C2 Safe_key ~C7 . ~N\n\tTake_it? ~S4 ",
    "\tIt's_locked. ~E ",
    "\tI've_got_a_ ~C2 Receipt ~C7 . ~E ",
    "\tI've_got_a_ ~C2 Kaufmann_key ~C7 . ~E ",
};
