name: Main Game Logic Overlay (BODYPROG)
sha1: 9E867F8410735EED4D45E49282EA65F8EE4FDAC2
options:
  basename: BODYPROG.BIN
  target_path: assets/JAP2/1ST/BODYPROG.BIN
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/JAP2/bodyprog
  src_path: src/bodyprog
  asset_path: asm/JAP2/bodyprog
  build_path: build/JAP2

  ld_script_path: linkers/JAP2/bodyprog.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/JAP1/screens/sym.b_konami.txt
    - configs/JAP1/screens/sym.stream.txt
    - configs/JAP1/screens/sym.saveload.txt
    - configs/JAP1/screens/sym.options.txt
    - configs/JAP1/screens/sym.credits.txt
    - configs/JAP1/sym.bodyprog.txt
    - configs/USA/sym.main.txt
  reloc_addrs_path:
    - configs/JAP2/rel.bodyprog.txt

  undefined_funcs_auto_path: linkers/JAP2/undefined_funcs_auto.bodyprog.txt
  undefined_syms_auto_path: linkers/JAP2/undefined_syms_auto.bodyprog.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: bodyprog
    type: code
    start: 0x0
    vram: 0x80024B60
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata, bodyprog]
      - [0x4, .rodata, memcard]
      - [0x130, rodata]
      - [0x134, .rodata, screen/screen_fade]
      - [0x17C, .rodata, screen/cutscene_border]
      - [0x1DC, rodata]
      - [0x5A4, .rodata, sys/fs_screens]
      - [0x5B4, .rodata, sys/settings_reset]
      - [0x610, rodata, sys/memcard_2]
      - [0x698, .rodata, game_boot/game_load]
      - [0x6CC, .rodata, events/bgm_update]
      - [0x6F4, rodata] # Garbage padding
      - [0x6F8, .rodata, events/map_msg_display]
      - [0x750, rodata, events/bodyprog_data_800A99B4]
      - [0x810, .rodata, events/game_sys_states]
      - [0x914, .rodata, title]
      - [0x9B8, rodata]
      - [0x107C, rodata] # Garbage padding
      - [0x108C, .rodata, sound/sd_call]
      - [0x11F8, rodata]
      - [0x145C, .rodata, items/item_screens_1]
      - [0x147C, .rodata, items/item_screens_2]
      - [0x1854, .rodata, items/item_screens_3]
      - [0x36F8, .rodata, gfx/bodyprog_80055028]
      - [0x3720, rodata]
      - [0x3740, .rodata, bodyprog_8005E0DC]
      - [0x3BE4, rodata] # Garbage padding
      - [0x3BEC, .rodata, bodyprog_mapscreen_80066EB0]
      - [0x3BF4, rodata] # Garbage padding
      - [0x3BF8, .rodata, bodyprog_mapscreen_80066D90]
      - [0x3D10, .rodata, bodyprog_800697EC]
      - [0x491C, rodata]
      - [0x5CC8, .rodata, bodyprog_80085D78]
      - [0x5DD0, .rodata, bodyprog_80089090]
      - [0x6168, rodata]
      - [0x64C0, .rodata, ranking]
      - [0x6798, rodata] # Garbage padding
      - [0x67A0, rodata]

      - [0x985C, c, memcard]
      - [0xC6F4, c, screen/background_draw]
      - [0xD104, c, text/text_debug_draw]
      - [0xD560, c, screen/screen_draw]
      - [0xD7AC, c, screen/screen_fade]
      - [0xDAA4, c, screen/cutscene_border]
      - [0xDD88, c, sys/vsync]
      - [0xDDD8, c, sys/fs_screens]
      - [0xDF24, c, sys/game_main] # Name from SH2 symbols. This name also applies for SH4 instance too.
      - [0xE5BC, c, sys/settings_reset]
      - [0xE6C8, asm, sys/memcard_2]
      - [0xF2F4, c, sys/warm_boot]
      - [0xF630, c, sys/joy]
      - [0xFAD4, c, game_boot/game_load]
      - [0x100DC, c, game_boot/chara_init]
      - [0x102D0, c, game_boot/game_boot]
      - [0x104A0, c, game_boot/fs_chara_anim]
      - [0x10994, c, game_boot/background_sound_init]
      - [0x10D18, c, game_boot/load_screen]
      - [0x10FC8, c, events/bgm_update]
      - [0x117CC, c, events/map_msg_display]
      - [0x123CC, c, events/radio]
      - [0x12460, c, events/player_pos_update]
      - [0x12600, c, events/events_main]
      - [0x1303C, c, events/npc_main]
      - [0x13E4C, c, events/game_sys_states]
      - [0x15DA0, c, title]
      - [0x16FA4, c, bodyprog_8003BD2C]
      - [0x170C8, asm, gfx/bodyprog_8003BE50]
      - [0x19860, asm, gfx/bodyprog_8003E5E8]
      - [0x1B27C, c, gfx/bodyprog_80040004]
      - [0x1B2C4, c, view/vc_util]
      - [0x1BCDC, c, gfx/bodyprog_80040A64]
      - [0x1F81C, c, gfx/bodyprog_anim_800445A4]
      - [0x20CF4, c, sound/sd_call]
      - [0x23CB0, c, view/vw_main]
      - [0x241A0, c, view/vw_calc] # Contains part of SH2's `vb_main`?
      - [0x25AF4, asm, text/text_draw_jp]
      - [0x28098, c, items/item_screens_cam]
      - [0x28624, c, items/item_screens_1]
      - [0x28E78, c, items/item_screens_2]
      - [0x2BD34, c, items/item_screens_3]
      - [0x31FD0, c, gfx/bodyprog_80055028]
      - [0x38EE0, c, bodyprog_math_8005BF38]
      - [0x39778, c, bodyprog_combat_8005BF38]
      - [0x3A814, c, 3d_audio]
      - [0x3B084, c, bodyprog_8005E0DC]
      - [0x4229C, c, bodyprog_800652F4]
      - [0x43D38, c, bodyprog_mapscreen_80066EB0]
      - [0x43E58, c, bodyprog_mapscreen_80066D90]
      - [0x4679C, c, bodyprog_800697EC]
      - [0x4D694, asm, bodyprog_800706E4]
      - [0x5D8F0, asm, view/vc_main]
      - [0x62D28, c, bodyprog_80085D78]
      - [0x64E58, c, bodyprog_bgm_80087EA8]
      - [0x65168, c, bodyprog_800881B8]
      - [0x65C2C, c, chara_spawn]
      - [0x66040, c, bodyprog_80089090]
      - [0x67008, asm, bodyprog_combat_8008A058]
      - [0x69950, c, dms]
      - [0x6A3CC, asm, water]
      - [0x6BED0, asm, demo]
      - [0x6C8FC, c, ranking]
      - [0x6E728, c, credits_init]

      - [0x6EAAC, asm, lib/psyq]

      - [0x866F8, data, bodyprog]
      - [0x867B8, .data, screen/background_draw]
      - [0x867BC, .data, screen/screen_fade]
      - [0x867F8, .data, screen/cutscene_border]
      - [0x868A4, data]
      - [0x870C8, .data, sys/game_main]
      - [0x87134, data, sys/memcard_2]
      - [0x87164, .data, game_boot/background_sound_init]
      - [0x8725C, .data, game_boot/fs_chara_anim]
      - [0x872FC, .data, events/bgm_update]
      - [0x8730C, .data, events/map_msg_display] # Garbage data at 0x87312 in JAP2
      - [0x87314, data]
      - [0x87380, .data, events/events_main]
      - [0x8738C, .data, events/game_sys_states]
      - [0x873D4, .data, title]
      - [0x87814, data]
      - [0x8ADE0, .data, view/vw_calc]
      - [0x8ADF8, data]
      - [0x8AE24, .data, items/item_screens_3]
      - [0x8D618, data]
      - [0x8D688, .data, bodyprog_80085D78]
      - [0x8D6A0, data]
      - [0x8D778, .data, ranking]
      - [0x8D78C, .data, credits_init]
      - [0x8D800, data]

      - [0x90110, .bss, memcard]
      - [0x93718, .bss, text/text_debug_draw]
      - [0x93720, .bss, screen/screen_fade]
      - [0x9372C, bss]
      - [0x9A80C, pad]
      - [0x9A810, bss]
      - [0x9A838, pad]
      - [0x9A840, .bss, game_boot/game_load]
      - [0x9A844, pad]
      - [0x9A848, .bss, events/bgm_update]
      - [0x9A858, .bss, events/map_msg_display]
      - [0x9A874, pad]
      - [0x9A878, .bss, events/game_sys_states]
      - [0x9A8D4, pad]
      - [0x9A8D8, .bss, title]
      - [0x9A8DC, pad]
      - [0x9A8E0, bss]
      - [0x9D6E4, pad]
      - [0x9D6E8, .bss, gfx/bodyprog_80040A64]
      - [0x9F0A4, pad]
      - [0x9F0A8, .bss, gfx/bodyprog_anim_800445A4]
      - [0x9F0AD, pad]
      - [0x9F0B0, .bss, sound/sd_call]
      - [0xA12D8, .bss, view/vw_main]
      - [0xA1360, .bss, view/vw_calc]
      - [0xA13A0, bss]
      - [0xA1420, .bss, items/item_screens_cam]
      - [0xA1458, .bss, items/item_screens_1]
      - [0xA1460, .bss, items/item_screens_2]
      - [0xA14A0, .bss, items/item_screens_3]
      - [0xA1C60, bss]
      - [0xA1DB4, pad]
      - [0xA1DB8, .bss, 3d_audio]
      - [0xA1DC8, bss]
      - [0xA1DCC, pad]
      - [0xA1DD0, .bss, bodyprog_8005E0DC]
      - [0xA1F20, .bss, bodyprog_800652F4]
      - [0xA1F40, .bss, bodyprog_mapscreen_80066D90]
      - [0xA1F4C, pad]
      - [0xA1F50, .bss, bodyprog_800697EC]
      - [0xA1FC4, pad]
      - [0xA1FC8, bss]
      - [0xA2114, pad]
      - [0xA2118, bss]
      - [0xA2124, pad]
      - [0xA2128, bss]
      - [0xA2138, .bss, bodyprog_80085D78]
      - [0xA2220, bss]
      - [0xA2398, .bss, ranking]
      - [0xA23E4, pad]
      - [0xA23E8, .bss, credits_init]
      - [0xA23EC, pad]
      - [0xA23F0, bss]
      - [0xA4A34, pad]
      - [0xA4A38, bss]
      - [0xA4B24, pad]
      - [0xA4B28, bss]
      - [0xA51E4, pad]
      - [0xA51E8, bss]
      - [0xA65F4, pad]
      - [0xA65F8, bss]

  # Random garbage data at end, define as bin file to make Splat ignore it.
  - name: footer_data
    type: bin
    start: 0xA7070
  - [0xA7100]
