    {
      {
        .positionX_0 = Q12(142.1f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(180.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(22.2f),
      },
      {
        .positionX_0 = Q12(139.8f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(20.0f),
      },
      {
        .positionX_0 = Q12(-20.6f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(180.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-55.3f),
      },
      {
        .positionX_0 = Q12(-16.5f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(270.0f),
        .flags_6 = 11,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-58.1f),
      },
      {
        .positionX_0 = Q12(128.4f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(191.5f),
      },
      {
        .positionX_0 = Q12(137.7f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(270.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(191.3f),
      },
      {
        .positionX_0 = Q12(19.3f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(60.5f),
      },
      {
        .positionX_0 = Q12(107.6f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 7,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(60.2f),
      },
      {
        .positionX_0 = Q12(108.7f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(270.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(60.3f),
      },
      {
        .positionX_0 = Q12(107.5f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(46.0f),
      },
      {
        .positionX_0 = Q12(133.6f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(180.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(190.6f),
      },
      {
        .positionX_0 = Q12(58.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(76.1f),
      },
      {
        .positionX_0 = Q12(61.2f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(52.1f),
      },
      {
        .positionX_0 = Q12(59.5f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(52.7f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
    },
    {
      {
        .positionX_0 = Q12(99.9f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(315.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(142.3f),
      },
      {
        .positionX_0 = Q12(141.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(180.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(102.0f),
      },
      {
        .positionX_0 = Q12(139.3f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(97.8f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
    },
