#include "bodyprog/bodyprog.h"

s_EventData MAP_EVENTS[101] = {
    {
        .disabledEventFlag_2  = EventFlag_M1S00_HandgunBullets0,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 94,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800D7A28`
    },
    {
        .disabledEventFlag_2  = EventFlag_M1S00_HandgunBullets1,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 95,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800D7A28`
    },
    {
        .disabledEventFlag_2  = EventFlag_M1S00_HandgunBullets2,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 96,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800D7A28`
    },
    {
        .disabledEventFlag_2  = EventFlag_M1S00_HealthDrink,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 97,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800D7A28`
    },
    {
        .disabledEventFlag_2  = EventFlag_M1S00_FirstAidKit,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 98,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800D7A28`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 89,
        .sysState_8_0         = SysState_SaveMenu1,
        .eventParam_8_5       = 4,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 91,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 21, // `func_800D9254`
    },
    {
        .disabledEventFlag_2  = EventFlag_M1S00_PickupMap,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 90,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 20, // `MapEvent_TownMapTake`
    },
    {
        .requiredEventFlag_0  = EventFlag_73,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 30,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 23, // `MapEvent_Boiler2`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_72,
        .disabledEventFlag_2  = EventFlag_73,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 30,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 18, // `MapEvent_Boiler0`
    },
    {
        .disabledEventFlag_2  = EventFlag_72,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 30,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 19, // `MapEvent_Boiler1`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 31,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 32,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 32,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 33,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 29,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 17, // `func_800D8CC4`
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_ReceptionQuestion,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 24,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 12, // `func_800D853C`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_ReceptionQuestion,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 25,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 13, // `func_800D8570`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_ReceptionQuestion,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 26,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 14, // `func_800D85A4`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_73,
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_ClockTowerCircle,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 13,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 20,
        .field_8_19           = 3,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_ClockTowerCircle,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 13,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 10, // `func_800D81CC`
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 20,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 21,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_184,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 19,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 22, // `func_800D928C`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0 = EventFlag_184,
        .disabledEventFlag_2 = EventFlag_78,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_LoadRoom,
        .eventParam_8_5      = 23,
        .flags_8_13          = 2,
    },
    {
        .requiredEventFlag_0 = EventFlag_78,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_EventCallFunc,
        .eventParam_8_5      = 15, // `func_800D85D8`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 16,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 16, // `func_800D8948`
    },
    {
        .requiredEventFlag_0 = EventFlag_79,
        .disabledEventFlag_2 = EventFlag_82,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_LoadRoom,
        .eventParam_8_5      = 19,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 17,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 16, // `func_800D8948`
    },
    {
        .requiredEventFlag_0 = EventFlag_80,
        .disabledEventFlag_2 = EventFlag_82,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_LoadRoom,
        .eventParam_8_5      = 21,
    },
    {
        .disabledEventFlag_2  = EventFlag_185,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 21,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 22, // `func_800D928C`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0 = EventFlag_185,
        .disabledEventFlag_2 = EventFlag_81,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_LoadRoom,
        .eventParam_8_5      = 23,
        .flags_8_13          = 2,
    },
    {
        .requiredEventFlag_0 = EventFlag_81,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_EventCallFunc,
        .eventParam_8_5      = 15, // `func_800D85D8`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 22,
        .sysState_8_0         = SysState_LoadOverlay,
        .eventParam_8_5       = 18,
        .field_8_19           = 3,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP1_S02,
    },
    {
        .requiredEventFlag_0  = EventFlag_71,
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_ClockTowerCircle,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 14,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 5, // `func_800D7AF8`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_ClockTowerCircle,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 14,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 4, // `func_800D7AC4`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_71,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 14,
        .requiredItemId_6     = InventoryItemId_GoldMedallion,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 6, // `func_800D7B2C`
    },
    {
        .requiredEventFlag_0  = EventFlag_72,
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_ClockTowerCircle,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 15,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 8, // `func_800D7E7C`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_ClockTowerCircle,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 15,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 7, // `func_800D7E48`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_72,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 15,
        .requiredItemId_6     = InventoryItemId_SilverMedallion,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 9, // `func_800D7EB0`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 1,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 26,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 2,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 26,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_LobbyArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 38,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 33,
        .field_8_19           = 2,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_LobbyArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 33,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 38,
        .field_8_19           = 2,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_UntitledLobbyTopBroken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 49,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_CourtyardBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 5,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 3,
        .field_8_19           = 2,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_CourtyardBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 3,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 5,
        .field_8_19           = 2,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_FogSchool1F_BotRightCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 34,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 50,
        .field_8_19           = 2,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_FogSchool1F_BotRightCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 50,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 34,
        .field_8_19           = 2,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_BotRightCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 50,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_BotRightCorridorLocked,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 34,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_FogSchool1F_BotLeftCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 35,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 65,
        .field_8_19           = 2,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_FogSchool1F_BotLeftCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 65,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 35,
        .field_8_19           = 2,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_BotLeftCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 65,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_BotLeftCorridorLocked,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 35,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_InfirmaryArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 37,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 40,
        .field_8_19           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_InfirmaryArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 40,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 37,
        .field_8_19           = 1,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_ReceptionArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 36,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 39,
        .field_8_19           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_ReceptionArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 39,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 36,
        .field_8_19           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_FogSchool1F_TopRightCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 41,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 51,
        .field_8_19           = 2,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_FogSchool1F_TopRightCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 51,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 41,
        .field_8_19           = 2,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_TopRightCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 51,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_TopRightCorridorLocked,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 41,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_TopLeftCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 42,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 66,
        .field_8_19           = 2,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_TopLeftCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 66,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 42,
        .field_8_19           = 2,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_StorageBroken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 44,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_UntitledLobbyBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 45,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 48,
        .field_8_19           = 2,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_UntitledLobbyBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 48,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 45,
        .field_8_19           = 2,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_HallLeftBroken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 46,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_CourtyardTopArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 6,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 4,
        .field_8_19           = 2,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_CourtyardTopArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 4,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 6,
        .field_8_19           = 2,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_BotClassRoomBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 52,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 59,
        .field_8_19           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_BotClassRoomBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 59,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 52,
        .field_8_19           = 1,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_BotClassRoomTopArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 53,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 60,
        .field_8_19           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_BotClassRoomTopArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 60,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 53,
        .field_8_19           = 1,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_TopClassRoomBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 54,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 62,
        .field_8_19           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_TopClassRoomBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 62,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 54,
        .field_8_19           = 1,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_TopClassRoomTopArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 55,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 63,
        .field_8_19           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_TopClassRoomTopArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 63,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 55,
        .field_8_19           = 1,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_ClassRoomMidArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 64,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 61,
        .field_8_19           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_ClassRoomMidArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 61,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 64,
        .field_8_19           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_HallMidBroken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 56,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_WomensBathroomArrow,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 67,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 7,
        .field_8_19           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_WomensBathroomArrow,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 7,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 67,
        .field_8_19           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_MensBathroomArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 68,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 8,
        .field_8_19           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_MensBathroomArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 8,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 68,
        .field_8_19           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_BotTeachersRoomBotBroken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 69,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_BotTeachersRoomTopBroken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 70,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_TopTeachersRoomBotBroken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 71,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchool1F_TopTeachersRoomTopBroken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 72,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchoolBF_StorageBroken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 82,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchoolBF_BoilerRoomArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 83,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 85,
        .field_8_19           = 17,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_FogSchoolBF_BoilerRoomArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 85,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 83,
        .field_8_19           = 17,
        .field_8_24           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 79,
        .sysState_8_0         = SysState_LoadOverlay,
        .eventParam_8_5       = 11,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP1_S01,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 80,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 10,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 86,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 9,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 81,
        .sysState_8_0         = SysState_LoadOverlay,
        .eventParam_8_5       = 12,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP1_S01,
    },
    {
        .disabledEventFlag_2  = EventFlag_594,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 28,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 26,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 35,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 87,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 36,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 88,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 36,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 92,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 39,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 93,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 39,
    },
    {
        .triggerType_4_0 = TriggerType_EndOfArray,
    },
};
