    {
      .lim_sw_0 = {
        .min_hx = Q4(-240.0f),
        .max_hx = Q4(-157.5f),
        .min_hz = Q4(-12.0f),
        .max_hz = Q4(12.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-200.0f),
        .max_hx = Q4(-150.0f),
        .min_hz = Q4(-7.5f),
        .max_hz = Q4(7.5f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(6.0f),
      .lim_rd_min_hy_13 = Q4(-6.0f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-157.5f),
        .max_hx = Q4(80.0f),
        .min_hz = Q4(-10.0f),
        .max_hz = Q4(10.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-170.0f),
        .max_hx = Q4(80.0f),
        .min_hz = Q4(-5.5f),
        .max_hz = Q4(5.5f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(6.0f),
      .lim_rd_min_hy_13 = Q4(-6.0f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-151.9f),
        .max_hx = Q4(-145.5f),
        .min_hz = Q4(15.5f),
        .max_hz = Q4(16.5f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-151.0f),
        .max_hx = Q4(-151.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(14.8f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_EVENT,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-2.7f),
      .lim_rd_min_hy_13 = Q4(-2.7f),
      .ofs_watch_hy_14 = Q4(-0.8f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-151.9f),
        .max_hx = Q4(-145.5f),
        .min_hz = Q4(-16.5f),
        .max_hz = Q4(-15.5f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-151.0f),
        .max_hx = Q4(-151.0f),
        .min_hz = Q4(-14.8f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_EVENT,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-2.7f),
      .lim_rd_min_hy_13 = Q4(-2.7f),
      .ofs_watch_hy_14 = Q4(-0.8f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-140.0f),
        .max_hx = Q4(-137.0f),
        .min_hz = Q4(17.0f),
        .max_hz = Q4(20.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-134.0f),
        .max_hx = Q4(-128.0f),
        .min_hz = Q4(8.0f),
        .max_hz = Q4(14.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_EVENT,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-3.1f),
      .lim_rd_min_hy_13 = Q4(-3.1f),
      .ofs_watch_hy_14 = Q4(-0.8f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-140.0f),
        .max_hx = Q4(-137.0f),
        .min_hz = Q4(-20.0f),
        .max_hz = Q4(-17.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-134.0f),
        .max_hx = Q4(-128.0f),
        .min_hz = Q4(-14.0f),
        .max_hz = Q4(-8.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_EVENT,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-3.1f),
      .lim_rd_min_hy_13 = Q4(-3.1f),
      .ofs_watch_hy_14 = Q4(-0.8f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-130.0f),
        .max_hx = Q4(-110.0f),
        .min_hz = Q4(-120.0f),
        .max_hz = Q4(40.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-125.5f),
        .max_hx = Q4(-114.5f),
        .min_hz = Q4(-120.0f),
        .max_hz = Q4(40.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(6.0f),
      .lim_rd_min_hy_13 = Q4(-6.0f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-128.0f),
        .max_hx = Q4(40.0f),
        .min_hz = Q4(-90.0f),
        .max_hz = Q4(-70.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-128.0f),
        .max_hx = Q4(40.0f),
        .min_hz = Q4(-85.5f),
        .max_hz = Q4(-74.5f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(6.0f),
      .lim_rd_min_hy_13 = Q4(-6.0f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-67.0f),
        .max_hx = Q4(-53.0f),
        .min_hz = Q4(-80.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-64.0f),
        .max_hx = Q4(-56.0f),
        .min_hz = Q4(-80.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(6.0f),
      .lim_rd_min_hy_13 = Q4(-6.0f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(53.0f),
        .max_hx = Q4(67.0f),
        .min_hz = Q4(-40.0f),
        .max_hz = Q4(80.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(56.0f),
        .max_hx = Q4(64.0f),
        .min_hz = Q4(-40.0f),
        .max_hz = Q4(80.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(6.0f),
      .lim_rd_min_hy_13 = Q4(-6.0f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-10.0f),
        .max_hx = Q4(10.0f),
        .min_hz = Q4(-88.0f),
        .max_hz = Q4(120.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-5.5f),
        .max_hx = Q4(5.5f),
        .min_hz = Q4(-88.0f),
        .max_hz = Q4(112.7f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(6.0f),
      .lim_rd_min_hy_13 = Q4(-6.0f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(8.0f),
        .max_hx = Q4(15.0f),
        .min_hz = Q4(100.5f),
        .max_hz = Q4(104.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(8.6f),
        .min_hz = Q4(98.2f),
        .max_hz = Q4(105.5f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_EFFECT,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(6.0f),
      .lim_rd_min_hy_13 = Q4(-6.0f),
      .ofs_watch_hy_14 = Q4(-0.8f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-16.0f),
        .max_hx = Q4(-8.0f),
        .min_hz = Q4(-104.0f),
        .max_hz = Q4(-80.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-14.0f),
        .max_hx = Q4(-10.0f),
        .min_hz = Q4(-104.0f),
        .max_hz = Q4(-80.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(6.0f),
      .lim_rd_min_hy_13 = Q4(-6.0f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-139.0f),
        .max_hx = Q4(-126.0f),
        .min_hz = Q4(-71.0f),
        .max_hz = Q4(-63.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-132.3f),
        .max_hx = Q4(-127.4f),
        .min_hz = Q4(-70.0f),
        .max_hz = Q4(-59.7f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F | VC_RD_MARGE_ROAD_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_FIX_ANG,
      .lim_rd_max_hy_12 = Q4(-2.0f),
      .lim_rd_min_hy_13 = Q4(-2.6f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(140.0f),
        .max_hx = Q4(148.0f),
        .min_hz = Q4(-25.0f),
        .max_hz = Q4(-10.5f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(141.5f),
        .max_hx = Q4(147.0f),
        .min_hz = Q4(-18.0f),
        .max_hz = Q4(-12.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.6f),
      .lim_rd_min_hy_13 = Q4(-1.6f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(140.0f),
        .max_hx = Q4(148.0f),
        .min_hz = Q4(-12.7f),
        .max_hz = Q4(-10.5f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(146.0f),
        .max_hx = Q4(146.0f),
        .min_hz = Q4(-18.0f),
        .max_hz = Q4(-12.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_EFFECT,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.6f),
      .lim_rd_min_hy_13 = Q4(-1.6f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-222.0f),
        .max_hx = Q4(-215.0f),
        .min_hz = Q4(107.0f),
        .max_hz = Q4(109.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-222.7f),
        .max_hx = Q4(-222.7f),
        .min_hz = Q4(108.1f),
        .max_hz = Q4(108.1f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_FIX_ANG,
      .lim_rd_max_hy_12 = Q4(-1.82f),
      .lim_rd_min_hy_13 = Q4(-1.82f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_FIX_ANG,
      .fix_ang_x_16 = Q8_ANGLE(334.0f),
      .fix_ang_y_17 = Q8_ANGLE(89.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(216.0f),
        .max_hx = Q4(218.0f),
        .min_hz = Q4(-23.5f),
        .max_hz = Q4(-16.8f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(220.5f),
        .max_hx = Q4(220.5f),
        .min_hz = Q4(-20.8f),
        .max_hz = Q4(-20.8f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_EVENT,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-2.4f),
      .lim_rd_min_hy_13 = Q4(-2.4f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(218.2f),
        .max_hx = Q4(224.0f),
        .min_hz = Q4(-23.2f),
        .max_hz = Q4(-16.8f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(220.5f),
        .max_hx = Q4(220.5f),
        .min_hz = Q4(-22.4f),
        .max_hz = Q4(-17.3f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-2.3f),
      .lim_rd_min_hy_13 = Q4(-2.3f),
      .ofs_watch_hy_14 = Q4(-0.7f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(150.0f),
        .max_hx = Q4(172.0f),
        .min_hz = Q4(51.0f),
        .max_hz = Q4(71.5f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(155.3f),
        .max_hx = Q4(165.0f),
        .min_hz = Q4(56.5f),
        .max_hz = Q4(73.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-3.6f),
      .lim_rd_min_hy_13 = Q4(-3.6f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(165.0f),
        .max_hx = Q4(172.0f),
        .min_hz = Q4(58.6f),
        .max_hz = Q4(61.3f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(155.3f),
        .max_hx = Q4(164.0f),
        .min_hz = Q4(51.0f),
        .max_hz = Q4(73.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_EFFECT,
      .mv_y_type_11 = VC_MV_SETTLE,
      .lim_rd_max_hy_12 = Q4(-1.0f),
      .lim_rd_min_hy_13 = Q4(-3.6f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(170.0f),
        .max_hx = Q4(172.0f),
        .min_hz = Q4(56.0f),
        .max_hz = Q4(58.4f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(170.0f),
        .max_hx = Q4(170.0f),
        .min_hz = Q4(59.2f),
        .max_hz = Q4(59.2f),
      },
      .flags_10 = VC_RD_WARP_IN_OUT_FS | VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_EVENT,
      .mv_y_type_11 = VC_MV_SETTLE,
      .lim_rd_max_hy_12 = Q4(-4.5f),
      .lim_rd_min_hy_13 = Q4(-4.5f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(126.0f),
        .max_hx = Q4(134.0f),
        .min_hz = Q4(-96.3f),
        .max_hz = Q4(-93.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(124.2f),
        .max_hx = Q4(128.4f),
        .min_hz = Q4(-95.5f),
        .max_hz = Q4(-95.5f),
      },
      .flags_10 = VC_RD_WARP_IN_OUT_FS,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_EVENT,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-3.8f),
      .lim_rd_min_hy_13 = Q4(-3.8f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_FIX_ANG,
      .fix_ang_x_16 = Q8_ANGLE(314.0f),
      .fix_ang_y_17 = Q8_ANGLE(64.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(119.0f),
        .max_hx = Q4(126.0f),
        .min_hz = Q4(-96.3f),
        .max_hz = Q4(-93.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(114.0f),
        .max_hx = Q4(126.2f),
        .min_hz = Q4(-96.0f),
        .max_hz = Q4(-93.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.7f),
      .lim_rd_min_hy_13 = Q4(-1.7f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(119.0f),
        .max_hx = Q4(134.0f),
        .min_hz = Q4(-96.3f),
        .max_hz = Q4(-93.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(114.0f),
        .max_hx = Q4(133.0f),
        .min_hz = Q4(-96.0f),
        .max_hz = Q4(-93.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.7f),
      .lim_rd_min_hy_13 = Q4(-1.7f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(113.5f),
        .max_hx = Q4(119.0f),
        .min_hz = Q4(-107.0f),
        .max_hz = Q4(-93.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(112.5f),
        .max_hx = Q4(119.0f),
        .min_hz = Q4(-106.0f),
        .max_hz = Q4(-94.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.7f),
      .lim_rd_min_hy_13 = Q4(-1.7f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(104.0f),
        .max_hx = Q4(114.0f),
        .min_hz = Q4(-107.0f),
        .max_hz = Q4(-102.7f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(106.3f),
        .max_hx = Q4(132.0f),
        .min_hz = Q4(-104.8f),
        .max_hz = Q4(-102.1f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.7f),
      .lim_rd_min_hy_13 = Q4(-1.7f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(104.0f),
        .max_hx = Q4(111.0f),
        .min_hz = Q4(-102.7f),
        .max_hz = Q4(-97.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(112.5f),
        .max_hx = Q4(119.0f),
        .min_hz = Q4(-106.0f),
        .max_hz = Q4(-94.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.3f),
      .lim_rd_min_hy_13 = Q4(-1.3f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(104.0f),
        .max_hx = Q4(114.0f),
        .min_hz = Q4(-97.0f),
        .max_hz = Q4(-93.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(106.3f),
        .max_hx = Q4(132.0f),
        .min_hz = Q4(-97.9f),
        .max_hz = Q4(-95.2f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(-1.7f),
      .lim_rd_min_hy_13 = Q4(-1.7f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(112.0f),
        .max_hx = Q4(132.0f),
        .min_hz = Q4(134.2f),
        .max_hz = Q4(146.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(112.0f),
        .max_hx = Q4(131.0f),
        .min_hz = Q4(134.2f),
        .max_hz = Q4(146.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-3.2f),
      .lim_rd_min_hy_13 = Q4(-3.2f),
      .ofs_watch_hy_14 = Q4(4.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-98.3f),
        .max_hx = Q4(-97.2f),
        .min_hz = Q4(-70.1f),
        .max_hz = Q4(-63.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-96.4f),
        .max_hx = Q4(-96.4f),
        .min_hz = Q4(-78.0f),
        .max_hz = Q4(-70.0f),
      },
      .flags_10 = VC_RD_LIM_UP_FAR_VIEW_F,
      .area_size_type_11 = VC_AREA_WIDE,
      .rd_type_11 = VC_RD_TYPE_EFFECT,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(6.0f),
      .lim_rd_min_hy_13 = Q4(-4.1f),
      .ofs_watch_hy_14 = Q4(-0.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-123.5f),
        .max_hx = Q4(-116.5f),
        .min_hz = Q4(103.2f),
        .max_hz = Q4(115.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-124.4f),
        .max_hx = Q4(-116.4f),
        .min_hz = Q4(103.0f),
        .max_hz = Q4(110.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_SELF_VIEW,
      .lim_rd_max_hy_12 = Q4(-0.4f),
      .lim_rd_min_hy_13 = Q4(-0.4f),
      .ofs_watch_hy_14 = Q4(-2.5f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-123.5f),
        .max_hx = Q4(-120.0f),
        .min_hz = Q4(95.0f),
        .max_hz = Q4(103.2f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-122.5f),
        .max_hx = Q4(-122.5f),
        .min_hz = Q4(103.0f),
        .max_hz = Q4(120.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(1.0f),
      .lim_rd_min_hy_13 = Q4(-2.5f),
      .ofs_watch_hy_14 = Q4(-1.8f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-120.7f),
        .max_hx = Q4(-117.0f),
        .min_hz = Q4(95.0f),
        .max_hz = Q4(99.2f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-122.5f),
        .max_hx = Q4(-122.5f),
        .min_hz = Q4(103.0f),
        .max_hz = Q4(120.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(1.0f),
      .lim_rd_min_hy_13 = Q4(-2.5f),
      .ofs_watch_hy_14 = Q4(-1.8f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(-119.7f),
        .max_hx = Q4(-115.0f),
        .min_hz = Q4(95.0f),
        .max_hz = Q4(103.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(-122.5f),
        .max_hx = Q4(-122.5f),
        .min_hz = Q4(103.0f),
        .max_hz = Q4(120.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_SMALL,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(1.0f),
      .lim_rd_min_hy_13 = Q4(-2.5f),
      .ofs_watch_hy_14 = Q4(-1.8f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_END_DATA_F,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
    {
      .lim_sw_0 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .lim_rd_8 = {
        .min_hx = Q4(0.0f),
        .max_hx = Q4(0.0f),
        .min_hz = Q4(0.0f),
        .max_hz = Q4(0.0f),
      },
      .flags_10 = VC_RD_NOFLAG,
      .area_size_type_11 = VC_AREA_TINY,
      .rd_type_11 = VC_RD_TYPE_ROAD,
      .mv_y_type_11 = VC_MV_CHASE,
      .lim_rd_max_hy_12 = Q4(0.0f),
      .lim_rd_min_hy_13 = Q4(0.0f),
      .ofs_watch_hy_14 = Q4(0.0f),
      .field_15 = 0,
      .cam_mv_type_14 = VC_MV_CHASE,
      .fix_ang_x_16 = Q8_ANGLE(0.0f),
      .fix_ang_y_17 = Q8_ANGLE(0.0f),
    },
