name: Main Game Logic Overlay (BODYPROG)
sha1: 6513FD4DF1A0C57B814BA70B89859BA8C4AAE3BE
options:
  basename: BODYPROG.BIN
  target_path: assets/JAP0/1ST/BODYPROG.BIN
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/JAP0/bodyprog
  src_path: src/bodyprog
  o_path: ../../lib
  asset_path: asm/JAP0/bodyprog
  build_path: build/JAP0

  ld_script_path: linkers/JAP0/bodyprog.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False # Disabled as our include_asm.h is customized to work with different game versions.

  section_order: [".rodata", ".text", ".data", ".sdata", ".bss"]

  symbol_addrs_path:
    - configs/JAP0/screens/sym.b_konami.txt
    - configs/JAP0/screens/sym.stream.txt
    - configs/JAP0/screens/sym.saveload.txt
    - configs/JAP0/screens/sym.options.txt
    - configs/JAP0/screens/sym.credits.txt
    - configs/JAP0/sym.bodyprog.txt
    - configs/USA/sym.main.txt
  reloc_addrs_path:
    - configs/JAP0/rel.bodyprog.txt

  undefined_funcs_auto_path: linkers/JAP0/undefined_funcs_auto.bodyprog.txt
  undefined_syms_auto_path: linkers/JAP0/undefined_syms_auto.bodyprog.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: bodyprog
    type: code
    start: 0x0
    vram: 0x80024B60
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata, bodyprog]
      - [0x4, .rodata, memcard]
      - [0x130, rodata] # Garbage padding
      - [0x134, .rodata, screen/screen_fade]
      - [0x17C, .rodata, screen/cutscene_border]
      - [0x1DC, rodata]
      - [0x598, .rodata, sys/fs_screens]
      - [0x5A8, .rodata, sys/settings_reset]
      - [0x604, .rodata, sys/memcard_2]
      - [0x680, rodata] # Garbage padding
      - [0x68C, .rodata, game_boot/game_load]
      - [0x6C0, .rodata, events/bgm_update]
      - [0x6E8, rodata] # Garbage padding
      - [0x6EC, .rodata, events/map_msg_display]
      - [0x744, .rodata, events/bodyprog_data_800A99B4]
      - [0x804, .rodata, events/game_sys_states]
      - [0x908, .rodata, events/title]
      - [0x9AC, rodata] # Garbage padding (should start at 0x9AB but that causes mismatches?)
      - [0x9B0, .rodata, gfx/bodyprog_8003BE50]
      - [0x1040, .rodata, gfx/map_effects]
      - [0x1070, rodata] # Garbage padding
      - [0x1080, .rodata, sound/sd_call]
      - [0x11EC, rodata] # Garbage padding
      - [0x11F4, .rodata, text/text_draw_jp]
      - [0x1450, .rodata, items/item_screens_1]
      - [0x1470, .rodata, items/item_screens_2]
      - [0x1848, .rodata, items/item_screens_3]
      - [0x36EC, .rodata, gfx/bodyprog_80055028]
      - [0x3714, rodata]
      - [0x3734, .rodata, bodyprog_8005E0DC]
      - [0x3BD8, rodata] # Garbage padding
      - [0x3BE0, .rodata, bodyprog_mapscreen_80066EB0]
      - [0x3BE8, rodata] # Garbage padding
      - [0x3BEC, .rodata, bodyprog_mapscreen_80066D90]
      - [0x3D04, .rodata, collision]
      - [0x4910, .rodata, player_control]
      - [0x5A10, .rodata, view/vc_main]
      - [0x5CBC, .rodata, bodyprog_80085D78]
      - [0x5DC4, .rodata, bodyprog_80089090]
      - [0x615C, .rodata, bodyprog_combat_8008A058]
      - [0x6414, .rodata, water]
      - [0x6438, .rodata, demo]
      - [0x6458, .rodata, ranking]
      - [0x672C, rodata] # Garbage padding
      - [0x6734, o, libcd/iso9660, .rdata]
      - [0x6924, o, libcd/type, .rdata]
      - [0x6944, o, libcd/c_011, .rdata]
      - [0x6964, o, libgpu/ktrans, .rdata]
      - [0x69A4, o, libgs/matrix, .rdata]
      - [0x69D4, o, libgs/gs_108, .rdata]
      - [0x69F4, o, libgs/gs_123, .rdata]
      - [0x6A84, o, libgs/objt, .rdata]
      - [0x6B24, o, libgs/objt3, .rdata]
      - [0x6BC4, rodata, lib_unk2/lib_8009687C]
      - [0x93C4, o, libpad/padentry, .rdata]
      - [0x93E4, o, libspu/s_sva, .rdata]
      - [0x9424, o, libspu/s_sca, .rdata]
      - [0x9464, .rodata, libsd/smf_io]
      - [0x96F8, .rodata, libsd/smf_mid]

      # data only files
      - [auto,      c, events/bodyprog_data_800A99B4]
      #- [0x97F0, asm, bodyprog] # Data
      #- [0x97F0, asm, globals] # Data
      #- [0x97F0, asm, syswork_functable] # Data

      - [0x97F0, c, memcard]
      - [0xC674, c, screen/background_draw]
      - [0xD084, c, text/text_debug_draw]
      - [0xD4E0, c, screen/screen_draw]
      - [0xD72C, c, screen/screen_fade]
      - [0xDA24, c, screen/cutscene_border]
      - [0xDD08, c, sys/vsync]
      - [0xDD58, c, sys/fs_screens]
      - [0xDEA4, c, sys/game_main] # Name from SH2 symbols. This name also applies for SH4 instance too.
      - [0xE53C, c, sys/settings_reset]
      - [0xE648, c, sys/memcard_2]
      - [0xF250, c, sys/warm_boot]
      - [0xF58C, c, sys/joy]
      - [0xFA30, c, game_boot/game_load]
      - [0x10038, c, game_boot/chara_init]
      - [0x1022C, c, game_boot/game_boot]
      - [0x103FC, c, game_boot/fs_chara_anim]
      - [0x108F0, c, game_boot/background_sound_init]
      - [0x10C74, c, game_boot/load_screen]
      - [0x10F24, c, events/bgm_update]
      - [0x11728, c, events/map_msg_display]
      - [0x12328, c, events/radio]
      - [0x123BC, c, events/player_pos_update]
      - [0x125A0, c, events/events_main]
      - [0x12F98, c, events/npc_main]
      - [0x13DA8, c, events/game_sys_states]
      - [0x15CFC, c, events/title]
      - [0x16F00, c, events/bodyprog_8003BD2C]
      - [0x17024, c, gfx/bodyprog_8003BE50]
      - [0x197BC, c, gfx/map_effects]
      - [0x1B1D8, c, events/bodyprog_80040004]
      - [0x1B220, c, view/vc_util]
      - [0x1BD48, c, gfx/bodyprog_80040B74]
      - [0x1F778, c, gfx/bodyprog_anim_800445A4]
      - [0x200E8, c, gfx/bodyprog_bone_80044F14]
      - [0x20C50, c, sound/sd_call]
      - [0x23C0C, c, view/vw_main]
      - [0x240FC, c, view/vw_calc] # Contains part of SH2's `vb_main`?
      - [0x25A50, c, text/text_draw_jp]
      - [0x27FF4, c, items/item_screens_cam]
      - [0x28580, c, items/item_screens_1]
      - [0x28DD4, c, items/item_screens_2]
      - [0x2BC80, c, items/item_screens_3]
      - [0x31F1C, c, gfx/bodyprog_80055028]
      - [0x38E2C, c, bodyprog_math_8005BF38]
      - [0x396C4, c, bodyprog_combat_8005BF38]
      - [0x3A760, c, 3d_audio]
      - [0x3AFD0, c, bodyprog_8005E0DC]
      - [0x421E8, c, bodyprog_800652F4]
      - [0x43C84, c, bodyprog_mapscreen_80066EB0]
      - [0x43DA4, c, bodyprog_mapscreen_80066D90]
      - [0x466E0, c, collision]
      - [0x4D5D8, c, player_control]
      - [0x5D81C, c, view/vc_main]
      - [0x62C54, c, bodyprog_80085D78]
      - [0x64D84, c, bodyprog_bgm_80087EA8]
      - [0x65094, c, bodyprog_800881B8]
      - [0x65B58, c, chara_spawn]
      - [0x65F6C, c, bodyprog_80089090]
      - [0x66F34, c, bodyprog_combat_8008A058]
      - [0x6985C, c, dms]
      - [0x6A2D8, c, water]
      - [0x6BDDC, c, demo]
      - [0x6C7D8, c, ranking]
      - [0x6E604, c, credits_init]

      # PsyQ libs
      - [0x6e988, o, libapi/a09]
      - [0x6e998, o, libapi/a11]
      - [0x6e9a8, o, libapi/a39]
      - [0x6e9b8, o, libapi/a51]
      - [0x6e9c8, o, libapi/a53]
      - [0x6e9d8, o, libapi/a65]
      - [0x6e9e8, o, libapi/a67]
      - [0x6e9f8, o, libapi/a68]
      - [0x6ea08, o, libapi/a69]
      - [0x6ea18, o, libapi/a81]
      - [0x6ea28, o, libapi/first]
      - [0x6ecc8, o, libapi/a66]
      - [0x6ecd8, o, libc/a56]
      - [0x6ece8, o, libc/c24]
      - [0x6ecf8, o, libc/c25]
      - [0x6ed08, o, libc/c26]
      - [0x6ed18, o, libc/c27]
      - [0x6ed28, o, libc/c37]
      - [0x6ed38, o, libc/memcmp]
      - [0x6ed88, o, libcard/c171]
      - [0x6ed98, o, libcard/c172]
      - [0x6eda8, o, libcard/a78]
      - [0x6edb8, o, libcard/a80]
      - [0x6edc8, o, libcard/card]
      - [0x6ee08, o, libcard/init]
      - [0x6eed8, o, libapi/pad]
      - [0x6F1D8, o, libapi/a18]
      - [0x6F1E8, o, libapi/a19]
      - [0x6F1F8, o, libapi/a20]
      - [0x6f208, o, libapi/a21]
      - [0x6F218, o, libapi/l02]
      - [0x6F228, o, libapi/l03]
      - [0x6F238, o, libapi/patch]
      - [0x6F2D8, o, libapi/c68]
      - [0x6f2e8, o, libapi/chclrpad]
      - [0x6F358, o, libcard/a74]
      - [0x6F368, o, libcard/a75]
      - [0x6f378, o, libcard/a76]
      - [0x6F388, o, libcard/patch]
      - [0x6f558, o, libcard/end]
      - [0x6F5D8, o, libcd/cdrom]
      - [0x6F608, o, libcd/iso9660]
      - [0x6FF78, o, libcd/cdread2]
      - [0x70028, o, libcd/type] # JAP only
      - [0x702B8, o, libcd/c_002]
      - [0x70318, o, libcd/c_003]
      - [0x70398, o, libcd/c_004]
      - [0x70488, o, libcd/c_005]
      - [0x70518, o, libcd/c_007]
      - [0x705C8, o, libcd/c_008]
      - [0x70608, o, libcd/c_009]
      - [0x706C8, o, libcd/c_010]
      - [0x706E8, o, libcd/c_011]
      - [0x711D8, o, libgpu/ext]
      - [0x71478, o, libgpu/ktrans] # JAP only
      - [0x71B88, o, libc/c39]
      - [0x71B98, o, libgpu/p00]
      - [0x71BD8, o, libgpu/p01]
      - [0x71bf8, o, libgpu/p06]
      - [0x71c38, o, libgpu/p09]
      - [0x71c58, o, libgpu/p14]
      - [0x71c78, o, libgpu/p16]
      - [0x71c98, o, libgpu/p17]
      - [0x71cb8, o, libgpu/p18]
      - [0x71cd8, o, libgpu/p26]
      - [0x71cf8, o, libgpu/p33]
      - [0x71d28, o, libgpu/p34]
      - [0x71D88, o, libgs/2d_sp1]
      - [0x71F08, o, libgs/gs_001]
      - [0x72458, o, libgs/gs_002]
      - [0x72578, o, libgs/gs_003]
      - [0x725f8, o, libgs/gs_007]
      - [0x72638, o, libapi/counter]
      - [0x727a8, o, libgs/gs_008]
      - [0x727d8, o, libgs/gs_009]
      - [0x72808, o, libgs/gs_010]
      - [0x728b8, o, libgs/matrix]
      - [0x72c78, o, libgs/gs_104]
      - [0x72cf8, o, libgs/gs_105]
      - [0x72d68, o, libgs/gs_106]
      - [0x72D88, o, libgs/gs_107]
      - [0x732F8, o, libgs/gs_108]
      - [0x73378, o, libgs/gs_110]
      - [0x733a8, o, libgs/gs_111]
      - [0x733d8, o, libgs/gs_113]
      - [0x73438, o, libgs/gs_114]
      - [0x734F8, o, libgs/gs_121]
      - [0x73548, o, libgs/gs_123]
      - [0x73618, o, libgs/gs_127]
      - [0x73698, o, libgs/objt]
      - [0x73828, o, libgs/objt3]

      - [0x740b8, asm, lib_unk2/lib_8009687C]

      - [0x74704, o, libgte/msc00]
      - [0x74794, o, libgte/msc01]
      - [0x74824, o, libgte/msc02]
      - [0x74AD4, o, libgte/msc06]
      - [0x74d64, o, libgte/msc09]
      - [0x74e04, o, libgte/mtx_000]
      - [0x74F14, o, libgte/mtx_001]
      - [0x75004, o, libgte/mtx_003]
      - [0x75164, o, libgte/mtx_004]
      - [0x752c4, o, libgte/mtx_005]
      - [0x752f4, o, libgte/mtx_006]
      - [0x75444, o, libgte/mtx_007]
      - [0x75494, o, libgte/mtx_01]
      - [0x755D4, o, libgte/mtx_02]
      - [0x756c4, o, libgte/mtx_03]
      - [0x757d4, o, libgte/mtx_04]
      - [0x758e4, o, libgte/mtx_05]
      - [0x75934, o, libgte/mtx_06]
      - [0x75994, o, libgte/mtx_07]
      - [0x759c4, o, libgte/mtx_08]
      - [0x75b04, o, libgte/mtx_09]
      - [0x75b34, o, libgte/mtx_10]
      - [0x75b64, o, libgte/mtx_11]
      - [0x75b94, o, libgte/mtx_12]
      - [0x75bb4, o, libgte/reg08]
      - [0x75bd4, o, libgte/reg09]
      - [0x75be4, o, libgte/reg10]
      - [0x75C04, o, libgte/reg11]
      - [0x75c24, o, libgte/reg12]
      - [0x75c44, o, libgte/reg13]
      - [0x75C54, o, libgte/smp]
      - [0x75E34, o, libgte/smp_00]
      - [0x76044, o, libgte/smp_02]
      - [0x76074, o, libgte/smp_03]
      - [0x760d4, o, libgte/smp_04]
      - [0x76104, o, libgte/cmb_00]
      - [0x76184, o, libgte/fgo_00]
      - [0x761c4, o, libgte/g3]
      - [0x76774, o, libgte/g4]
      - [0x76e34, o, libgte/gt3]
      - [0x77474, o, libgte/gt4]
      - [0x77be4, o, libgte/ratan]
      - [0x77D64, o, libgte/patchgte]
      - [0x77e44, o, libpad/padentry]
      - [0x782F4, o, libpad/padmain]
      - [0x78FF4, o, libpad/padcmd]
      - [0x79954, o, libpad/padif]
      - [0x79f44, o, libpad/padportd]
      - [0x7A5A4, o, libpad/padseqd]
      - [0x7AA34, o, libpad/waitrc2]
      - [0x7aaf4, o, libspu/s_crwa]
      - [0x7AC94, o, libapi/a10]
      - [0x7ACA4, o, libspu/s_m_util]
      - [0x7adb4, o, libspu/s_stm]
      - [0x7ade4, o, libspu/s_sva]
      - [0x7B3E4, o, libspu/s_n2p]
      - [0x7b5e4, o, libspu/s_gva]

      - [0x7B9D4, c, lib_unk/lib_8009E198]
      - [0x7c5e0, c, libsd/smf_snd]

      - [0x7fb98, o, libspu/s_q]      # SpuQuit
      - [0x7FC18, o, libapi/a13]      # DisableEvent
      - [0x7FC28, o, libspu/s_m_init] # SpuInitMalloc
      - [0x7FC88, o, libspu/s_sr]     # SpuSetReverb
      - [0x7FD58, o, libspu/s_srmp]   # SpuSetReverbModeParam
      - [0x80238, o, libspu/s_sra]    # _spu_setReverbAttr
      - [0x80708, o, libspu/s_rrwa]   # SpuReserveReverbWorkArea
      - [0x80758, o, libspu/s_srv]    # SpuSetReverbVoice
      - [0x80788, o, libspu/s_sav]    # _SpuSetAnyVoice
      - [0x80A48, o, libspu/s_sk]     # SpuSetKey
      - [0x80C08, o, libspu/s_gks]    # SpuGetKeyStatus
      - [0x80C98, o, libspu/s_skowa]  # SpuSetKeyOnWithAttr
      - [0x80CC8, o, libspu/s_w]      # SpuWrite
      - [0x80D28, o, libspu/s_stsa]   # SpuSetTransferStartAddr
      - [0x80D88, o, libspu/s_itc]    # SpuIsTransferCompleted
      - [0x80E38, o, libspu/s_sca]    # SpuSetCommonAttr

      - [0x811B8, c, libsd/smf_io]

      - [0x844F4, o, libspu/s_grv] # SpuGetReverbVoice
      - [0x84524, o, libspu/s_gav] # _SpuGetAnyVoice
      
      - [0x84554, c, libsd/smf_main]
      - [0x847F4, c, libsd/smf_mid]

      # TODO - [0x6CF9C, asm, bodyprog_data_800A8D98] # Data
      # TODO - [0x6CF9C, asm, screen/screen_data]     # Data
      # TODO - [0x6CF9C, asm, bodyprog_data_800A90FC] # Data

      - [0x865D4, data, bodyprog]
      - [0x86694, .data, screen/background_draw]
      - [0x86698, .data, screen/screen_fade]
      - [0x866D4, .data, screen/cutscene_border]
      - [0x86780, data]
      - [0x86FA4, .data, sys/game_main]
      - [0x87010, .data, sys/memcard_2]
      - [0x87040, .data, game_boot/background_sound_init]
      - [0x87138, .data, game_boot/fs_chara_anim]
      - [0x871D8, .data, events/bgm_update]
      - [0x871E8, .data, events/map_msg_display]
      - [0x871EE, pad] # Garbage padding
      - [0x871F0, .data, events/bodyprog_data_800A99B4]
      - [0x8725C, .data, events/events_main]
      - [0x87268, .data, events/game_sys_states]
      - [0x872B0, .data, events/title]
      - [0x876E8, .data, gfx/bodyprog_8003BE50]
      - [0x877BC, .data, gfx/map_effects]
      - [0x87804, data]
      - [0x8ACBC, .data, view/vw_calc]
      - [0x8ACD4, .data, text/text_draw_jp]
      - [0x8ACDC, data]
      - [0x8AD00, .data, items/item_screens_3]
      - [0x8D4F4, .data, view/vc_main]
      - [0x8D564, .data, bodyprog_80085D78]
      # 0x8D57C should hold D_800AFD1C here, but that gets included by the bodyprog_combat_8008A058 .bss below somehow?
      - [0x8D59C, .data, water]
      - [0x8D618, .data, demo]
      - [0x8D654, .data, ranking]
      - [0x8D668, .data, credits_init]
      - [0x8D6DC, o, libcard/init, .data]
      - [0x8D6EC, o, libapi/pad, .data]
      - [0x8D6FC, o, libcd/cdrom, .data]
      - [0x8D70C, o, libcd/iso9660, .data]
      - [0x8D71C, o, libcd/c_002, .data]
      - [0x8D72C, o, libcd/c_003, .data]
      - [0x8D73C, o, libcd/c_004, .data]
      - [0x8D74C, o, libcd/c_005, .data]
      - [0x8D75C, o, libcd/c_007, .data]
      - [0x8D76C, o, libcd/c_008, .data]
      - [0x8D77C, o, libcd/c_009, .data]
      - [0x8D78C, o, libcd/c_010, .data]
      - [0x8D79C, o, libcd/c_011, .data]
      - [0x8D7EC, o, libgpu/ktrans, .data]
      - [0x8D95C, o, libgs/gs_001, .data]
      - [0x8D96C, o, libapi/counter, .data]
      - [0x8D98C, o, libgs/global, .data]
      - [0x8D99C, o, libgte/sqrtbl, .data]
      - [0x8DB1C, o, libgte/msc00, .data]
      - [0x8DB2C, o, libgte/msc02, .data]
      - [0x8DCCC, o, libgte/mtx_006, .data]
      - [0x8DFDC, o, libgte/ratan, .data]
      - [0x8E7EC, o, libpad/padmain, .data]
      - [0x8E86C, o, libpad/padif, .data]
      - [0x8E88C, o, libpad/padportd, .data]
      - [0x8E89C, o, libspu/zerobuf, .data]
      - [0x8EC9C, o, libspu/s_n2p, .data]
      - [0x8EDBC, .data, lib_unk/lib_8009E198]
      - [0x8EE0C, .data, libsd/smf_main]
      
      # .sdata section
      - [0x8FFE0, .sdata, lib_unk/lib_8009E198]
      - [0x8FFE6, sdata] # Garbage padding, some reason splat doesn't output data into the .s, so postbuild currently has to add it.

      # .bss section
      - [0x8FFE8, .bss, memcard]
      - [0x935F0, .bss, text/text_debug_draw]
      - [0x935F8, .bss, screen/screen_fade]
      - [0x93604, bss]
      - [0x9A6E4, pad] # Garbage
      - [0x9A6E8, .bss, sys/memcard_2]
      - [0x9A714, pad] # Garbage
      - [0x9A718, .bss, game_boot/game_load]
      - [0x9A71C, pad] # Garbage
      - [0x9A720, .bss, events/bgm_update]
      - [0x9A730, .bss, events/map_msg_display]
      - [0x9A74C, pad] # Garbage
      - [0x9A750, .bss, events/game_sys_states]
      - [0x9A7AC, pad] # Garbage.
      - [0x9A7B0, .bss, events/title]
      - [0x9A7B4, bss]
      - [0x9A7B8, .bss, gfx/map_effects]
      - [0x9A7C8, bss]
      - [0x9D5BC, pad] # Garbage
      - [0x9D5C0, .bss, gfx/bodyprog_80040B74]
      - [0x9EF7C, pad] # Garbage
      - [0x9EF80, .bss, gfx/bodyprog_bone_80044F14]
      - [0x9EF84, pad] # Garbage
      - [0x9EF88, .bss, sound/sd_call]
      - [0xA11B0, .bss, view/vw_main]
      - [0xA1238, .bss, view/vw_calc]
      - [0xA1278, .bss, text/text_draw_jp]
      - [0xA1280, bss]
      - [0xA12F8, .bss, items/item_screens_cam]
      - [0xA1330, .bss, items/item_screens_1]
      - [0xA1338, .bss, items/item_screens_2]
      - [0xA1378, .bss, items/item_screens_3]
      - [0xA1B38, bss]
      - [0xA1C90, .bss, 3d_audio]
      - [0xA1CA0, bss]
      - [0xA1CA8, .bss, bodyprog_8005E0DC]
      - [0xA1DF8, .bss, bodyprog_800652F4]
      - [0xA1E18, .bss, bodyprog_mapscreen_80066D90]
      - [0xA1E24, bss]
      - [0xA1E28, .bss, collision]
      - [0xA1E9C, bss]
      - [0xA1EA0, .bss, player_control]
      - [0xA1FEC, bss, player_control_2]
      - [0xA2000, .bss, view/vc_main]
      - [0xA2010, .bss, bodyprog_80085D78]
      - [0xA20F8, .bss, bodyprog_combat_8008A058]
      - [0xA21E8, .bss, water]
      - [0xA2210, .bss, demo]
      - [0xA2270, .bss, ranking]
      - [0xA22BC, pad] # Garbage
      - [0xA22C0, .bss, credits_init]
      - [0xA22C4, pad] # Garbage
      - [0xA22C8, o, libapi/first, .bss]
      - [0xA22F8,  o, libapi/pad, .bss]
      - [0xA2308,  o, libapi/patch, .bss]
      - [0xA2318,  o, libapi/chclrpad, .bss]
      - [0xA2328,  o, libcard/patch, .bss]
      - [0xA2338,  o, libcard/end, .bss]
      - [0xA2348,  o, libcd/cdrom, .bss]
      - [0xA2390,  o, libcd/iso9660, .bss]
      - [0xA4790,  o, libcd/c_004, .bss]
      - [0xA47A0,  o, libcd/c_005, .bss]
      - [0xA47A8,  o, libcd/c_011, .bss]
      - [0xA47B8,  o, libgs/gs_001, .bss]
      - [0xA4878,  o, libgs/matrix, .bss] # Resized matrix.o .bss section from 0x25B0 to 0x25A8.
      - [0xA48F0,  o, libgs/gs_104, .bss]
      - [0xA490C, pad]  # Garbage.
      - [0xA4910,  o, libgs/gs_107, .bss]
      - [0xA4950,  o, libgs/gs_123, .bss]
      - [0xA49D0,  o, libgs/global, .bss]
      - [0xA49FC, pad]  # Garbage.
      - [0xA4A00,  o, libgs/objt3, .bss]
      - [0xA4B30,  o, libgte/patchgte, .bss]
      - [0xA4B40,  o, libpad/padmain, .bss]
      - [0xA4B60,  o, libpad/padcmd, .bss]
      - [0xA4B70,  o, libpad/padportd, .bss]
      - [0xA4DE0,  bss] # waitrc2.o
      - [0xA4DE8, .bss, libsd/smf_snd]
      - [0xA50B8,  pad]
      - [0xA50C0, .bss, libsd/smf_io]
      - [0xA64CC,  pad]  # Garbage.
      - [0xA64D0, .bss, libsd/smf_mid]

  # Random garbage data at end, define as bin file to make Splat ignore it.
  - name: footer_data
    type: bin
    start: 0xA6F48
  - [0xA7000]
