name: Main Game Logic Overlay (BODYPROG)
sha1: 6513FD4DF1A0C57B814BA70B89859BA8C4AAE3BE
options:
  basename: BODYPROG.BIN
  target_path: assets/JAP0/1ST/BODYPROG.BIN
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/JAP0/bodyprog
  src_path: src/bodyprog
  asset_path: asm/JAP0/bodyprog
  build_path: build/JAP0

  ld_script_path: linkers/JAP0/bodyprog.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
   # - configs/JAP0/screens/sym.b_konami.txt - Can't currently be included as function addrs overlap with map overlay data addrs
    - configs/JAP0/screens/sym.stream.txt
    - configs/JAP0/screens/sym.saveload.txt
    - configs/JAP0/screens/sym.options.txt
    - configs/JAP0/screens/sym.credits.txt
    - configs/JAP0/sym.bodyprog.txt
    - configs/USA/sym.main.txt
  reloc_addrs_path:
    - configs/JAP0/rel.bodyprog.txt

  undefined_funcs_auto_path: linkers/JAP0/undefined_funcs_auto.bodyprog.txt
  undefined_syms_auto_path: linkers/JAP0/undefined_syms_auto.bodyprog.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: bodyprog
    type: code
    start: 0x0
    vram: 0x80024B60
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata, bodyprog]
      - [0x4, .rodata, memcard]
      - [0x134, .rodata, screen/screen_fade]
      - [0x17C, .rodata, screen/cutscene_border]
      - [0x1DC, rodata]
      - [0x598, .rodata, sys/fs_screens]
      - [0x5A8, .rodata, sys/settings_reset]
      - [0x604, .rodata, sys/memcard_2]
      - [0x68C, .rodata, game_boot/game_load]
      - [0x6C0, .rodata, events/bgm_update]
      - [0x6EC, rodata]
      - [0x744, .rodata, events/bodyprog_gamestates_80038BD4]
      - [0x8D4, .rodata, events/bodyprog_event_80039F30]
      - [0x908, .rodata, title]
      - [0x9B0, .rodata, gfx/bodyprog_8003BD2C]
      - [0x1040, .rodata, gfx/bodyprog_8003E5E8]
      - [0x1070, .rodata, gfx/bodyprog_80040004] # TODO: Seems to just be garbage data, might be able to remove from .c
      - [0x1080, .rodata, sound/sd_call]
      - [0x11F4, rodata]
      - [0x1450, .rodata, items/item_screens_1]
      - [0x1470, rodata]
      - [0x36EC, .rodata, gfx/bodyprog_80055028]
      - [0x3714, rodata]
      - [0x3734, .rodata, bodyprog_8005E0DC]
      - [0x3BD8, .rodata, bodyprog_mapscreen_80066EB0]
      - [0x3BEC, rodata] # TODO: - [0x3BEC, .rodata, bodyprog_mapscreen_80066D90]
      - [0x3D04, .rodata, bodyprog_800697EC]
      - [0x4910, .rodata, bodyprog_800706E4]
      - [0x5A10, .rodata, view/vc_main]
      - [0x5CBC, .rodata, bodyprog_80085D78]
      - [0x5DC4, .rodata, bodyprog_80089090]
      - [0x615C, .rodata, bodyprog_combat_8008A058]
      - [0x6414, .rodata, water]
      - [0x6438, .rodata, demo]
      - [0x6458, .rodata, ranking]
      - [0x6734, rodata]

      #- [0x97F0, asm, bodyprog] # Data
      #- [0x97F0, asm, globals] # Data
      #- [0x97F0, asm, syswork_functable] # Data

      - [0x97F0, c, memcard]
      - [0xC674, c, screen/background_draw]
      - [0xD084, c, text/text_debug_draw]
      - [0xD4E0, c, screen/screen_draw]
      - [0xD72C, c, screen/screen_fade]
      - [0xDA24, c, screen/cutscene_border]
      - [0xDD08, c, sys/vsync]
      - [0xDD58, c, sys/fs_screens]
      - [0xDEA4, c, sys/game_main] # Name from SH2 symbols. This name also applies for SH4 instance too.
      - [0xE53C, c, sys/settings_reset]
      - [0xE648, c, sys/memcard_2]
      - [0xF250, c, sys/warm_boot]
      - [0xF58C, c, sys/joy]
      - [0xFA30, c, game_boot/game_load]
      - [0x10038, c, game_boot/chara_init]
      - [0x1022C, c, game_boot/game_boot]
      - [0x103FC, c, game_boot/fs_chara_anim]
      - [0x108F0, c, game_boot/background_sound_init]
      - [0x10C74, c, game_boot/load_screen]
      - [0x10F24, c, events/bgm_update]
      - [0x11728, asm, events/map_msg_display]
      - [0x12328, c, events/radio]
      - [0x123BC, c, events/bodyprog_event_800371E8]
      - [0x12F98, c, events/bodyprog_npc_80037DC4]
      - [0x13DA8, c, events/bodyprog_gamestates_80038BD4]
      - [0x15104, c, events/bodyprog_event_80039F30]
      - [0x15CFC, c, title]
      - [0x16F00, c, gfx/bodyprog_8003BD2C]
      - [0x197BC, c, gfx/bodyprog_8003E5E8]
      - [0x1B1D8, c, gfx/bodyprog_80040004]
      - [0x1B220, c, view/vc_util]
      - [0x1BC38, c, gfx/bodyprog_80040A64]
      - [0x1F778, c, gfx/bodyprog_anim_800445A4]
      - [0x20C50, c, sound/sd_call]
      - [0x23C0C, c, view/vw_main]
      - [0x240FC, c, view/vw_calc] # Contains part of SH2's `vb_main`?
      - [0x25A50, asm, text/text_draw]
      - [0x27FF0, c, items/item_screens_cam]
      - [0x28580, c, items/item_screens_1]
      - [0x28DD4, asm, items/item_screens_2]
      - [0x2BC80, asm, items/item_screens_3]
      - [0x31F1C, c, gfx/bodyprog_80055028]
      - [0x38E2C, c, bodyprog_math_8005BF38]
      - [0x396C4, c, bodyprog_combat_8005BF38]
      - [0x3A760, c, 3d_audio]
      - [0x3AFD0, c, bodyprog_8005E0DC]
      - [0x421E8, c, bodyprog_800652F4]
      - [0x43C84, c, bodyprog_mapscreen_80066EB0]
      - [0x43DA4, asm, bodyprog_mapscreen_80066D90]
      - [0x466E0, c, bodyprog_800697EC]
      - [0x4D5D8, c, bodyprog_800706E4]
      - [0x5D81C, c, view/vc_main]
      - [0x62C54, c, bodyprog_80085D78]
      - [0x64D84, c, bodyprog_bgm_80087EA8]
      - [0x65094, c, bodyprog_800881B8]
      - [0x65B58, c, chara_spawn]
      - [0x65F6C, c, bodyprog_80089090]
      - [0x66F34, c, bodyprog_combat_8008A058]
      - [0x6985C, c, dms]
      - [0x6A2D8, c, water]
      - [0x6BDDC, c, demo]
      - [0x6C7D8, c, ranking]
      - [0x6E604, c, credits_init]

      # TODO: SDK libs
      - [0x6E988, asm, lib/libapi]
      # TODO - [0x6CF9C, asm, bodyprog_data_800A8D98] # Data
      # TODO - [0x6CF9C, asm, screen/screen_data]     # Data
      # TODO - [0x6CF9C, asm, bodyprog_data_800A90FC] # Data

      - [0x865D4, data, bodyprog]
      - [0x86694, .data, screen/background_draw]
      - [0x86698, .data, screen/screen_fade]
      - [0x866D4, .data, screen/cutscene_border]
      - [0x86780, data]
      - [0x86FA4, .data, sys/game_main]
      - [0x87010, .data, sys/memcard_2]
      - [0x87040, .data, game_boot/background_sound_init]
      - [0x87138, .data, game_boot/fs_chara_anim]
      - [0x871D8, .data, events/bgm_update]
      - [0x871E8, data]
      - [0x8725C, .data, events/bodyprog_event_800371E8]
      - [0x87268, .data, events/bodyprog_gamestates_80038BD4]
      - [0x872B0, .data, title]
      - [0x876E8, .data, gfx/bodyprog_8003BD2C]
      - [0x877BC, .data, gfx/bodyprog_8003E5E8]
      - [0x87804, data]
      - [0x8ACBC, .data, view/vw_calc]
      - [0x8ACD4, data]
      - [0x8D4F4, .data, view/vc_main]
      - [0x8D564, .data, bodyprog_80085D78]
      # 0x8D57C should hold D_800AFD1C here, but that gets included by the bodyprog_combat_8008A058 .bss below somehow?
      - [0x8D59C, .data, water]
      - [0x8D618, .data, demo]
      - [0x8D654, .data, ranking]
      - [0x8D668, .data, credits_init]
      - [0x8D6DC, data]
      - [0x8FFE8, .bss, memcard]
      - [0x935F0, .bss, text/text_debug_draw]
      - [0x935F8, .bss, screen/screen_fade]
      - [0x93604, bss]
      - [0x9A6E4, pad] # Garbage
      - [0x9A6E8, .bss, sys/memcard_2]
      - [0x9A714, pad] # Garbage
      - [0x9A718, .bss, game_boot/game_load]
      - [0x9A71C, pad] # Garbage
      - [0x9A720, .bss, events/bgm_update]
      - [0x9A730, bss]
      - [0x9A74C, pad] # Garbage
      - [0x9A750, .bss, events/bodyprog_event_80039F30]
      - [0x9A7AC, pad] # Garbage.
      - [0x9A7B0, .bss, title]
      - [0x9A7B4, bss]
      - [0x9A7B8, .bss, gfx/bodyprog_8003E5E8]
      - [0x9A7C8, bss]
      - [0x9D5BC, pad] # Garbage
      - [0x9D5C0, .bss, gfx/bodyprog_80040A64]
      - [0x9EF7C, pad] # Garbage
      - [0x9EF80, .bss, gfx/bodyprog_anim_800445A4]
      - [0x9EF84, pad] # Garbage
      - [0x9EF88, .bss, sound/sd_call]
      - [0xA11B0, .bss, view/vw_main]
      - [0xA1238, .bss, view/vw_calc]
      - [0xA1278, bss]
      - [0xA12F8, .bss, items/item_screens_cam]
      - [0xA1330, .bss, items/item_screens_1]
      - [0xA1338, bss]
      - [0xA1C90, .bss, 3d_audio]
      - [0xA1CA0, bss]
      - [0xA1CA8, .bss, bodyprog_8005E0DC]
      - [0xA1DF8, .bss, bodyprog_800652F4]
      - [0xA1E18, bss]
      - [0xA1E28, .bss, bodyprog_800697EC]
      - [0xA1E9C, bss]
      - [0xA1EA0, .bss, bodyprog_800706E4]
      - [0xA1FEC, bss, bodyprog_800706E4_2]
      - [0xA2000, .bss, view/vc_main]
      - [0xA2010, .bss, bodyprog_80085D78]
      - [0xA20F8, .bss, bodyprog_combat_8008A058]
      - [0xA21E8, .bss, water]
      - [0xA2210, .bss, demo]
      - [0xA2270, .bss, ranking]
      - [0xA22BC, pad] # Garbage
      - [0xA22C0, .bss, credits_init]
      - [0xA22C4, pad] # Garbage
      - [0xA22C8, bss]
      - [0xA490C, pad] # Garbage
      - [0xA4910, bss]
      - [0xA49FC, pad] # Garbage
      - [0xA4A00, bss]
      - [0xA50BC, pad] # Garbage
      - [0xA50C0, bss]
      - [0xA64CC, pad] # Garbage
      - [0xA64D0, bss]

  # Random garbage data at end, define as bin file to make Splat ignore it.
  - name: footer_data
    type: bin
    start: 0xA6F48
  - [0xA7000]
