    {
      {
        .positionX_0 = Q12(115.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 1,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(140.0f),
      },
      {
        .positionX_0 = Q12(133.91f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(270.0f),
        .flags_6 = 19,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-93.915f),
      },
      {
        .positionX_0 = Q12(133.4f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(270.0f),
        .flags_6 = 20,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-94.35f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
    },
    {
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
    },
