    {
        .positionX = Q12(17.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(-139.1f),
    },
    {
        .positionX = Q12(15.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 8,
        .positionZ = Q12(-135.9f),
    },
    {
        .positionX = Q12(21.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 8,
        .positionZ = Q12(-140.1f),
    },
    {
        .positionX = Q12(14.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 8,
        .positionZ = Q12(-138.5f),
    },
    {
        .positionX = Q12(68.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(-139.05f),
    },
    {
        .positionX = Q12(57.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 1,
        .triggerParam1 = 4,
        .positionZ = Q12(-139.0f),
    },
    {
        .positionX = Q12(-20.9f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 0,
        .positionZ = Q12(-20.9f),
    },
    {
        .positionX = Q12(19.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(-141.3f),
    },
    {
        .positionX = Q12(15.85f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 12,
        .positionZ = Q12(-140.7f),
    },
    {
        .positionX = Q12(15.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 10,
        .positionZ = Q12(-139.9f),
    },
    {
        .positionX = Q12(15.9f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 4,
        .positionZ = Q12(-140.55f),
    }

