#include "bodyprog/bodyprog.h"

s_EventData MAP_EVENTS[201] = {
    {
        .disabledEventFlag  = EventFlag_M2S00_FirstAidKit0,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 139,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HandgunBullets0,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 140,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HandgunBullets1,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 141,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HealthDrink0,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 142,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HandgunBullets2,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 143,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_ShotgunShells0,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 144,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HealthDrink1,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 145,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HandgunBullets3,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 146,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HandgunBullets4,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 147,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HandgunBullets5,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 148,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HandgunBullets6,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 149,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HandgunBullets7,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 150,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HandgunBullets8,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 151,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HealthDrink2,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 152,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HealthDrink3,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 153,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HealthDrink4,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 154,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HandgunBullets9,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 155,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HealthDrink5,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 156,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HandgunBullets10,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 157,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HealthDrink6,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 158,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HealthDrink7,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 159,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HealthDrink8,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 160,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HealthDrink9,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 161,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HealthDrink10,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 162,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HealthDrink11,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 163,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_ShotgunShells1,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 164,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_FirstAidKit1,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 165,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HandgunBullets11,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 166,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HandgunBullets12,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 167,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HandgunBullets13,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 168,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_HandgunBullets14,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 169,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_FirstAidKit2,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 170,
        .sysState         = SysState_EventCallback,
        .eventParam       = 2, // `func_800E7B74`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 107,
        .sysState         = SysState_SaveMenu1,
        .eventParam       = 5,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 108,
        .sysState         = SysState_SaveMenu1,
        .eventParam       = 5,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 109,
        .sysState         = SysState_SaveMenu1,
        .eventParam       = 6,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 110,
        .sysState         = SysState_SaveMenu1,
        .eventParam       = 6,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 111,
        .sysState         = SysState_SaveMenu1,
        .eventParam       = 18,
    },
    {
        .requiredEventFlag = EventFlag_193,
        .disabledEventFlag = EventFlag_M2S00_WaterWorksCutscene,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_EventCallback,
        .eventParam      = 4, // `MapEvent_AtWaterWorks`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_PickupMap,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 115,
        .sysState         = SysState_EventCallback,
        .eventParam       = 25, // `MapEvent_MapTake`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_PickupMap,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 116,
        .sysState         = SysState_EventCallback,
        .eventParam       = 25, // `MapEvent_MapTake`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 1,
        .sysState         = SysState_LoadOverlay,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
        .mapIdx   = MapIdx_MAP0_S01,
    },
    {
        .disabledEventFlag  = EventFlag_147,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 10,
        .sysState         = SysState_EventCallback,
        .eventParam       = 9, // `MapEvent_CherylsSketchbook`
    },
    {
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 11,
        .sysState         = SysState_EventCallback,
        .eventParam       = 10, // `func_800E9470`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_PickupSteelPipe,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 2,
        .sysState         = SysState_EventCallback,
        .eventParam       = 7, // `MapEvent_SteelPipeTake`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_PickupSteelPipe,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 3,
        .sysState         = SysState_EventCallback,
        .eventParam       = 7, // `MapEvent_SteelPipeTake`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_PickupSteelPipe,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 4,
        .sysState         = SysState_EventCallback,
        .eventParam       = 7, // `MapEvent_SteelPipeTake`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_PickupSteelPipe,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 5,
        .sysState         = SysState_EventCallback,
        .eventParam       = 7, // `MapEvent_SteelPipeTake`
    },
    {
        .disabledEventFlag = EventFlag_146,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_EventCallback,
        .eventParam      = 8, // `MapEvent_CutsceneExitCafe`
        .flags_8_13          = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 6,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 7,
        .sfxPairIdx_8_19 = SfxPairIdx_4,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 7,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 6,
        .sfxPairIdx_8_19 = SfxPairIdx_4,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 8,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 9,
        .sfxPairIdx_8_19 = SfxPairIdx_4,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 9,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 8,
        .sfxPairIdx_8_19 = SfxPairIdx_4,
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_DogHouseNoteFound,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 12,
        .sysState         = SysState_EventCallback,
        .eventParam       = 11, // `MapEvent_DoghouseNote`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_DogHouseNoteFound,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 13,
        .sysState         = SysState_EventCallback,
        .eventParam       = 11, // `MapEvent_DoghouseNote`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_DogHouseNoteFound,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 14,
        .sysState         = SysState_EventCallback,
        .eventParam       = 11, // `MapEvent_DoghouseNote`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_DogHouseNoteFound,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 15,
        .sysState         = SysState_EventCallback,
        .eventParam       = 11, // `MapEvent_DoghouseNote`
    },
    {
        .requiredEventFlag  = EventFlag_M2S00_PickupDogHouseKey,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 16,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 24,
    },
    {
        .requiredEventFlag  = EventFlag_M2S00_DogHouseNoteFound,
        .disabledEventFlag  = EventFlag_M2S00_PickupDogHouseKey,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 16,
        .sysState         = SysState_EventCallback,
        .eventParam       = 12, // `MapEvent_DoghouseKeyTake`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 16,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 25,
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_PickupKeyOfLion,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 17,
        .sysState         = SysState_EventCallback,
        .eventParam       = 13, // `func_800E9A0C`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_PickupKeyOfWoodman,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 18,
        .sysState         = SysState_EventCallback,
        .eventParam       = 14, // `func_800E9A74`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_PickupKeyOfScarecrow,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 19,
        .sysState         = SysState_EventCallback,
        .eventParam       = 15, // `func_800E9CB4`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_PickupKeyOfScarecrow,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 20,
        .sysState         = SysState_EventCallback,
        .eventParam       = 15, // `func_800E9CB4`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_PickupKeyOfScarecrow,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 21,
        .sysState         = SysState_EventCallback,
        .eventParam       = 15, // `func_800E9CB4`
    },
    {
        .requiredEventFlag  = EventFlag_M2S00_PickupDogHouseKey,
        .disabledEventFlag  = EventFlag_153,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 22,
        .sysState         = SysState_EventCallback,
        .eventParam       = 16, // `MapEvent_HouseKeyUse`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_M2S00_PickupDogHouseKey,
        .disabledEventFlag  = EventFlag_153,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Item,
        .pointOfInterestIdx = 22,
        .requiredItemId     = InvItemId_HouseKey,
        .sysState         = SysState_EventCallback,
        .eventParam       = 16, // `MapEvent_HouseKeyUse`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_153,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 22,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 23,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .requiredEventFlag  = EventFlag_153,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 23,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 22,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 22,
        .sysState         = SysState_EventCallback,
        .eventParam       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_159,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 24,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 25,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .requiredEventFlag  = EventFlag_159,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 25,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 24,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .requiredEventFlag = EventFlag_158,
        .disabledEventFlag = EventFlag_159,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_EventCallback,
        .eventParam      = 18, // `MapEvent_DoorOfEclipseEnter`
    },
    {
        .requiredEventFlag  = EventFlag_M2S00_DoorOfEclypseOpen,
        .disabledEventFlag  = EventFlag_158,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 24,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 25,
        .flags_8_13           = 2,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 24,
        .sysState         = SysState_EventCallback,
        .eventParam       = 17, // `func_800E9DD8`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Item,
        .pointOfInterestIdx = 24,
        .requiredItemId     = InvItemId_KeyOfLion,
        .sysState         = SysState_EventCallback,
        .eventParam       = 17, // `func_800E9DD8`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Item,
        .pointOfInterestIdx = 24,
        .requiredItemId     = InvItemId_KeyOfWoodman,
        .sysState         = SysState_EventCallback,
        .eventParam       = 17, // `func_800E9DD8`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Item,
        .pointOfInterestIdx = 24,
        .requiredItemId     = InvItemId_KeyOfScarecrow,
        .sysState         = SysState_EventCallback,
        .eventParam       = 17, // `func_800E9DD8`
    },
    {
        .requiredEventFlag  = EventFlag_57,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 28,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 134,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
        .mapIdx   = MapIdx_MAP0_S02,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 28,
        .sysState         = SysState_EventCallback,
        .eventParam       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 26,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 27,
        .sfxPairIdx_8_19 = SfxPairIdx_11,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 27,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 26,
        .sfxPairIdx_8_19 = SfxPairIdx_11,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 124,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 64,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 125,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 65,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 126,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 66,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 127,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 66,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 128,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 67,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 29,
        .sysState         = SysState_EventCallback,
        .eventParam       = 19, // `func_800EA6E0`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 30,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 35,
        .sfxPairIdx_8_19 = SfxPairIdx_6,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 31,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 35,
        .sfxPairIdx_8_19 = SfxPairIdx_6,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 33,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 32,
        .sfxPairIdx_8_19 = SfxPairIdx_6,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 34,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 32,
        .sfxPairIdx_8_19 = SfxPairIdx_6,
    },
    {
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 36,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 38,
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_OldTown_KGordonArrowsOnly,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 40,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 39,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_OldTown_KGordonArrowsOnly,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 39,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 40,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .requiredEventFlag  = EventFlag_M1S06_PickupKGordonKey,
        .disabledEventFlag  = EventFlag_M2S00_KGordonDoorOpen,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 40,
        .sysState         = SysState_EventCallback,
        .eventParam       = 20, // `MapEvent_KGordonKeyUse`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_M1S06_PickupKGordonKey,
        .disabledEventFlag  = EventFlag_M2S00_KGordonDoorOpen,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Item,
        .pointOfInterestIdx = 40,
        .requiredItemId     = InvItemId_KGordonKey,
        .sysState         = SysState_EventCallback,
        .eventParam       = 20, // `MapEvent_KGordonKeyUse`
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 40,
        .sysState         = SysState_EventCallback,
        .eventParam       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 37,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 38,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 38,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 37,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 41,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 42,
        .sfxPairIdx_8_19 = SfxPairIdx_11,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 42,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 41,
        .sfxPairIdx_8_19 = SfxPairIdx_11,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 43,
        .sysState         = SysState_EventCallback,
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 118,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 64,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 119,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 65,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 120,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 66,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 121,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 67,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 122,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 68,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 123,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 69,
    },
    {
        .requiredEventFlag  = EventFlag_M2S00_KGordonDoorOpen,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 45,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 41,
    },
    {
        .requiredEventFlag  = EventFlag_134,
        .disabledEventFlag  = EventFlag_140,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 46,
        .sysState         = SysState_EventCallback,
        .eventParam       = 1, // `MapEvent_DoorLocked`
    },
    {
        .requiredEventFlag  = EventFlag_134,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 46,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 48,
        .sfxPairIdx_8_19 = SfxPairIdx_2,
        .mapIdx   = MapIdx_MAP1_S06,
    },
    {
        .requiredEventFlag  = EventFlag_134,
        .disabledEventFlag  = EventFlag_141,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 45,
        .sysState         = SysState_EventCallback,
        .eventParam       = 1, // `MapEvent_DoorLocked`
    },
    {
        .requiredEventFlag  = EventFlag_134,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 45,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 47,
        .sfxPairIdx_8_19 = SfxPairIdx_2,
        .mapIdx   = MapIdx_MAP1_S06,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 45,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 47,
        .sfxPairIdx_8_19 = SfxPairIdx_2,
        .mapIdx   = MapIdx_MAP1_S00,
    },
    {
        .requiredEventFlag  = EventFlag_M2S00_KGordonDoorOpen,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 46,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 41,
    },
    {
        .requiredEventFlag  = EventFlag_134,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 46,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 48,
        .sfxPairIdx_8_19 = SfxPairIdx_2,
        .mapIdx   = MapIdx_MAP1_S06,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 46,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 48,
        .sfxPairIdx_8_19 = SfxPairIdx_2,
        .mapIdx   = MapIdx_MAP1_S00,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 44,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 40,
    },
    {
        .disabledEventFlag  = EventFlag_163,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 50,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .requiredEventFlag  = EventFlag_163,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 49,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 51,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .requiredEventFlag  = EventFlag_163,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 51,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 49,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 49,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 52,
        .sfxPairIdx_8_19 = SfxPairIdx_18,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 52,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 49,
        .sfxPairIdx_8_19 = SfxPairIdx_18,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 53,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 48,
    },
    {
        .disabledEventFlag  = EventFlag_164,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Item,
        .pointOfInterestIdx = 54,
        .requiredItemId     = InvItemId_DrawbridgeKey,
        .sysState         = SysState_EventCallback,
        .eventParam       = 21, // `func_800EA960`
    },
    {
        .requiredEventFlag  = EventFlag_164,
        .disabledEventFlag  = EventFlag_165,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 54,
        .sysState         = SysState_EventCallback,
        .eventParam       = 22, // `func_800EAD2C`
    },
    {
        .requiredEventFlag  = EventFlag_165,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 54,
        .sysState         = SysState_EventCallback,
        .eventParam       = 29, // `func_800EB090`
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 54,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 43,
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_164,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 117,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 62,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 117,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 63,
    },
    {
        .triggerType      = TriggerType_TouchAabb,
        .pointOfInterestIdx = 55,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 56,
        .mapIdx   = MapIdx_MAP2_S02,
    },
    {
        .requiredEventFlag  = EventFlag_169,
        .disabledEventFlag  = EventFlag_170,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 58,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 59,
        .sfxPairIdx_8_19 = SfxPairIdx_4,
    },
    {
        .requiredEventFlag  = EventFlag_170,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 59,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 58,
        .sfxPairIdx_8_19 = SfxPairIdx_4,
    },
    {
        .requiredEventFlag  = EventFlag_170,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 58,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 59,
        .sfxPairIdx_8_19 = SfxPairIdx_4,
    },
    {
        .requiredEventFlag  = EventFlag_340,
        .disabledEventFlag  = EventFlag_169,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 57,
        .sysState         = SysState_EventCallback,
        .eventParam       = 23, // `func_800EB174`
    },
    {
        .requiredEventFlag = EventFlag_168,
        .disabledEventFlag = EventFlag_169,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_EventCallback,
        .eventParam      = 24, // `func_800EB3F4`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 58,
        .sysState         = SysState_EventCallback,
        .eventParam       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 61,
        .sysState         = SysState_EventCallback,
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 62,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 66,
        .mapIdx   = MapIdx_MAP5_S00,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 63,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 66,
        .mapIdx   = MapIdx_MAP5_S00,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 64,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 66,
        .mapIdx   = MapIdx_MAP5_S00,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 65,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 66,
        .mapIdx   = MapIdx_MAP5_S00,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 60,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 49,
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_PickupHealthDrink,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 67,
        .sysState         = SysState_EventCallback,
        .eventParam       = 3, // `func_800E7D54`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_PickupHealthDrink,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 68,
        .sysState         = SysState_EventCallback,
        .eventParam       = 3, // `func_800E7D54`
    },
    {
        .disabledEventFlag  = EventFlag_M2S00_PickupHealthDrink,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 69,
        .sysState         = SysState_EventCallback,
        .eventParam       = 3, // `func_800E7D54`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 67,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 46,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 68,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 46,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 69,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 46,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 70,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 45,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 71,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 45,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 72,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 45,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 73,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 45,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 74,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 45,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 75,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 45,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 76,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 45,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 77,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 45,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 78,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 45,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 79,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 45,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 80,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 45,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 81,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 45,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 82,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 45,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_OldTown_BachmanRdTopCross,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 83,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_OldTown_FinneyStRightCross,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 84,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_OldTown_FinneyStLeftCross,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 85,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_OldTown_MidwitchStTopCross,
        .triggerType      = TriggerType_TouchObb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 86,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_OldTown_UntitledStLeftCross,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 87,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_OldTown_MidwitchStBotCross,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 88,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_OldTown_BradburyStMidCross,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 89,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_OldTown_BradburyStLeftCross,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 90,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_OldTown_BachmanRdBotCross,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 91,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_OldTown_ElroyStBotCross,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 92,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_OldTown_ElroyStMidCross,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 93,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_OldTown_BachmanRdMidCross,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 94,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_OldTown_BlochStLeftCross,
        .triggerType      = TriggerType_TouchObb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 95,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_OldTown_LevinStTopCross,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 96,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_OldTown_BlochStRightCross,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 97,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_OldTown_LevinStBotCross,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 98,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_OldTown_MathesonStCross,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 99,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_61,
        .disabledEventFlag  = EventFlag_MapMark_OldTown_BotBridgeCross,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 100,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 101,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 102,
        .sfxPairIdx_8_19 = SfxPairIdx_5,
        .mapIdx   = MapIdx_MAP0_S02,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 103,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 104,
        .sfxPairIdx_8_19 = SfxPairIdx_22,
        .mapIdx   = MapIdx_MAP0_S02,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 105,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 106,
        .sfxPairIdx_8_19 = SfxPairIdx_2,
        .mapIdx   = MapIdx_MAP2_S01,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 112,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 114,
        .sfxPairIdx_8_19 = SfxPairIdx_24,
        .mapIdx   = MapIdx_MAP0_S02,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 113,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 114,
        .sfxPairIdx_8_19 = SfxPairIdx_24,
        .mapIdx   = MapIdx_MAP0_S02,
    },
    {
        .requiredEventFlag  = EventFlag_183,
        .disabledEventFlag  = EventFlag_M2S00_PickupRockDrill,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 131,
        .sysState         = SysState_EventCallback,
        .eventParam       = 5, // `func_800E816C`
    },
    {
        .requiredEventFlag  = EventFlag_183,
        .disabledEventFlag  = EventFlag_M2S00_PickupRockDrill,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 132,
        .sysState         = SysState_EventCallback,
        .eventParam       = 5, // `func_800E816C`
    },
    {
        .disabledEventFlag  = EventFlag_183,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Item,
        .pointOfInterestIdx = 131,
        .requiredItemId     = InvItemId_GasolineTank,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 77,
    },
    {
        .disabledEventFlag  = EventFlag_183,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Item,
        .pointOfInterestIdx = 132,
        .requiredItemId     = InvItemId_GasolineTank,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 77,
    },
    {
        .requiredEventFlag  = EventFlag_66,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 131,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 71,
    },
    {
        .requiredEventFlag  = EventFlag_66,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 132,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 71,
    },
    {
        .requiredEventFlag  = EventFlag_61,
        .disabledEventFlag  = EventFlag_M2S00_PickupChainsaw,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 133,
        .sysState         = SysState_EventCallback,
        .eventParam       = 6, // `func_800E8198`
    },
    {
        .disabledEventFlag  = EventFlag_61,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Item,
        .pointOfInterestIdx = 133,
        .requiredItemId     = InvItemId_GasolineTank,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 77,
    },
    {
        .requiredEventFlag  = EventFlag_65,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 133,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 74,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 129,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 70,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 130,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 70,
    },
    {
        .disabledEventFlag  = EventFlag_172,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 135,
        .sysState         = SysState_EventCallback,
        .eventParam       = 26, // `func_800EB758`
    },
    {
        .disabledEventFlag  = EventFlag_173,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 136,
        .sysState         = SysState_EventCallback,
        .eventParam       = 27, // `func_800EB79C`
    },
    {
        .disabledEventFlag  = EventFlag_173,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 138,
        .sysState         = SysState_EventCallback,
        .eventParam       = 27, // `func_800EB79C`
    },
    {
        .disabledEventFlag  = EventFlag_174,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 137,
        .sysState         = SysState_EventCallback,
        .eventParam       = 28, // `func_800EB7E0`
    },
    {
        .triggerType = TriggerType_EndOfArray,
    },
};
