#include "bodyprog/bodyprog.h"

s_EventData MAP_EVENTS[49] = {
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 49,
        .sysState         = SysState_SaveMenu1,
        .eventParam       = 4,
    },
    {
        .disabledEventFlag = EventFlag_133,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_Fmv,
        .eventParam      = 14,
        .flags_8_13          = 2,
    },
    {
        .disabledEventFlag = EventFlag_134,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_EventCallFunc,
        .eventParam      = 4, // `func_800D5614`
    },
    {
        .disabledEventFlag  = EventFlag_M1S06_PickupKGordonKey,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 10,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 5, // `func_800D5B98`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 11,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 19,
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 12,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 20,
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 13,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 21,
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 50,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 7, // `func_800D6338`
    },
    {
        .disabledEventFlag  = EventFlag_M1S00_PickupMap,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 51,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 8, // `MapEvent_MapTake`
    },
    {
        .disabledEventFlag  = EventFlag_140,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 1,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_140,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 1,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 4,
        .sfxPairIdx_8_19 = SfxPairIdx_2,
        .mapIdx   = MapIdx_MAP2_S00,
    },
    {
        .disabledEventFlag  = EventFlag_141,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 2,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_141,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 2,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 3,
        .sfxPairIdx_8_19 = SfxPairIdx_2,
        .mapIdx   = MapIdx_MAP2_S00,
    },
    {
        .disabledEventFlag  = EventFlag_139,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 14,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag = EventFlag_139,
        .disabledEventFlag = EventFlag_MapMark_FogSchool1F_LobbyArrows,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_EventSetFlag,
    },
    {
        .requiredEventFlag  = EventFlag_139,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 19,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 14,
        .sfxPairIdx_8_19 = SfxPairIdx_2,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_139,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 14,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 19,
        .sfxPairIdx_8_19 = SfxPairIdx_2,
    },
    {
        .disabledEventFlag  = EventFlag_138,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 22,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag = EventFlag_138,
        .disabledEventFlag = EventFlag_MapMark_FogSchool1F_BotRightCorridorArrows,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_EventSetFlag,
    },
    {
        .requiredEventFlag  = EventFlag_138,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 15,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 22,
        .sfxPairIdx_8_19 = SfxPairIdx_2,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_138,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 22,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 15,
        .sfxPairIdx_8_19 = SfxPairIdx_2,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchool2F_BotRightCorridorBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 39,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchool1F_CourtyardBotBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 5,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchool1F_BotLeftCorridorBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 16,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchool1F_InfirmaryArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 18,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 21,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchool1F_InfirmaryArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 21,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 18,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchool1F_ReceptionBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 17,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchool1F_TopRightCorridorBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 23,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchool2F_TopRightCorridorBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 40,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchool1F_BotClassRoomBotBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 24,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchool2F_BotRightClassRoomBotBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 41,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchool1F_BotClassRoomTopBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 25,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchool2F_BotRightClassRoomTopBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 42,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchool1F_TopClassRoomBotBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 26,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchool2F_TopRightClassRoomBotBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 43,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchool1F_TopClassRoomTopBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 27,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchool2F_TopRightClassRoomTopBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 44,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchool1F_HallMidBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 28,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchool2F_LibraryBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 45,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchoolBF_StorageBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 34,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchoolBF_BoilerRoomArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 35,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 37,
        .sfxPairIdx_8_19 = SfxPairIdx_17,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogSchoolBF_BoilerRoomArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 37,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 35,
        .sfxPairIdx_8_19 = SfxPairIdx_17,
        .field_8_24           = 1,
    },
    {
        .triggerType      = TriggerType_TouchAabb,
        .pointOfInterestIdx = 32,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 7,
    },
    {
        .disabledEventFlag  = EventFlag_135,
        .triggerType      = TriggerType_TouchAabb,
        .pointOfInterestIdx = 38,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 6,
        .flags_8_13           = 2,
    },
    {
        .requiredEventFlag = EventFlag_135,
        .disabledEventFlag = EventFlag_M1S06_ChurchMarkedOnMap,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_EventCallFunc,
        .eventParam      = 6, // `func_800D5DD8`
    },
    {
        .triggerType      = TriggerType_TouchAabb,
        .pointOfInterestIdx = 38,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 6,
    },
    {
        .triggerType      = TriggerType_TouchAabb,
        .pointOfInterestIdx = 31,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 8,
    },
    {
        .triggerType      = TriggerType_TouchAabb,
        .pointOfInterestIdx = 46,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 9,
    },
    {
        .triggerType = TriggerType_EndOfArray,
    },
};
