#include "bodyprog/bodyprog.h"

s_EventData MAP_EVENTS[35] = {
    {
        .disabledEventFlag_2  = EventFlag_346,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 25,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .requiredEventFlag_0  = EventFlag_346,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 26,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 27,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 28,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 29,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 2,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 3,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 4,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 5,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 6,
        .sysState_8_0         = SysState_LoadOverlay,
        .eventParam_8_5       = 7,
        .field_8_19           = 12,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP4_S01,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 19,
        .sysState_8_0         = SysState_LoadOverlay,
        .eventParam_8_5       = 34,
        .field_8_19           = 13,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP2_S04,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 20,
        .sysState_8_0         = SysState_LoadOverlay,
        .eventParam_8_5       = 34,
        .field_8_19           = 13,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP2_S04,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 21,
        .sysState_8_0         = SysState_LoadOverlay,
        .eventParam_8_5       = 34,
        .field_8_19           = 13,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP2_S04,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 9,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 12,
        .field_8_19           = 16,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 10,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 12,
        .field_8_19           = 16,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 11,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 12,
        .field_8_19           = 16,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 13,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 8,
        .field_8_19           = 16,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 14,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 8,
        .field_8_19           = 16,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 15,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 8,
        .field_8_19           = 16,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 16,
        .sysState_8_0         = SysState_LoadOverlay,
        .eventParam_8_5       = 18,
        .field_8_19           = 13,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP4_S04,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 17,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_319,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 30,
        .sysState_8_0         = SysState_LoadOverlay,
        .eventParam_8_5       = 31,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP4_S03,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 30,
        .sysState_8_0         = SysState_LoadOverlay,
        .eventParam_8_5       = 31,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP4_S03,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 32,
        .sysState_8_0         = SysState_LoadOverlay,
        .eventParam_8_5       = 33,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP4_S03,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 46,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 15,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltCentralTown_CrichtonStTopBigCross,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 35,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltCentralTown_CrichtonStBotBigCross,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 36,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltCentralTown_SimmonsStTopBigCross,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 37,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltCentralTown_SimmonsStMidCross,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 38,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltCentralTown_SimmonsStBotCross,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 39,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltCentralTown_WilsonStCross,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 40,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltCentralTown_KoontzStBigCross,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 41,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltCentralTown_SaganStRightBigCross,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 42,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltCentralTown_SaganStLeftBigCross,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 43,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltCentralTown_ParkingLotBigCross,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 44,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltCentralTown_UntatiledStBotCross,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 45,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 47,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 48,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 16,
    },
    {
        .triggerType_4_0 = TriggerType_EndOfArray,
    },
};
