    {
      {
        .positionX_0 = Q12(-61.8f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(135.0f),
        .flags_6 = 1,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(109.1f),
      },
      {
        .positionX_0 = Q12(-57.9f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(270.0f),
        .flags_6 = 14,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(93.1f),
      },
      {
        .positionX_0 = Q12(-99.9f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 9,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(95.5f),
      },
      {
        .positionX_0 = Q12(-98.8f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(180.0f),
        .flags_6 = 13,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(102.3f),
      },
      {
        .positionX_0 = Q12(-99.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(180.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(107.2f),
      },
      {
        .positionX_0 = Q12(-100.4f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 8,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(59.1f),
      },
      {
        .positionX_0 = Q12(-138.4f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 18,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(20.6f),
      },
      {
        .positionX_0 = Q12(-140.9f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(270.0f),
        .flags_6 = 14,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(16.9f),
      },
      {
        .positionX_0 = Q12(-99.5f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 18,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(20.9f),
      },
      {
        .positionX_0 = Q12(-57.9f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 14,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(19.0f),
      },
      {
        .positionX_0 = Q12(-98.8f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(270.0f),
        .flags_6 = 10,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-140.0f),
      },
      {
        .positionX_0 = Q12(-19.2f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 14,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-103.0f),
      },
      {
        .positionX_0 = Q12(-59.7f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(180.0f),
        .flags_6 = 18,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-93.3f),
      },
      {
        .positionX_0 = Q12(-58.5f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 1,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-91.5f),
      },
      {
        .positionX_0 = Q12(-98.5f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 9,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-57.5f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
    },
    {
      {
        .positionX_0 = Q12(-143.25f),
        .charaId_4 = Chara_Bloodsucker,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 18,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(61.2f),
      },
      {
        .positionX_0 = Q12(-143.25f),
        .charaId_4 = Chara_Bloodsucker,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 19,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(61.2f),
      },
      {
        .positionX_0 = Q12(-143.25f),
        .charaId_4 = Chara_Bloodsucker,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 20,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(61.2f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
    },
