#include "bodyprog/bodyprog.h"

s_EventData MAP_EVENTS[136] = {
    {
        .disabledEventFlag_2  = EventFlag_M3S03_FirstAidKit0,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 126,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800D151C`
    },
    {
        .disabledEventFlag_2  = EventFlag_M3S03_HealthDrink,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 127,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800D151C`
    },
    {
        .disabledEventFlag_2  = EventFlag_M3S03_HandgunBullets,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 128,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800D151C`
    },
    {
        .disabledEventFlag_2  = EventFlag_M3S03_FirstAidKit1,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 129,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800D151C`
    },
    {
        .disabledEventFlag_2  = EventFlag_M3S03_ShotgunShells,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 130,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800D151C`
    },
    {
        .disabledEventFlag_2  = EventFlag_214,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 38,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 73,
        .sfxPairIdx_8_19 = SfxPairIdx_7,
    },
    {
        .disabledEventFlag_2  = EventFlag_214,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 39,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 73,
        .sfxPairIdx_8_19 = SfxPairIdx_7,
    },
    {
        .disabledEventFlag_2  = EventFlag_215,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 1,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 73,
        .sfxPairIdx_8_19 = SfxPairIdx_7,
    },
    {
        .disabledEventFlag_2  = EventFlag_215,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 2,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 73,
        .sfxPairIdx_8_19 = SfxPairIdx_7,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 125,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 20, // `sharedFunc_800D15F0_3_s01`
    },
    {
        .requiredEventFlag_0 = EventFlag_216,
        .disabledEventFlag_2 = EventFlag_220,
        .triggerType_4_0     = TriggerType_None,
        .sysState_0        = SysState_LoadOverlay,
        .eventParam_8_5      = 124,
        .mapOverlayIdx_8_25  = MapOverlayId_MAP3_S05,
    },
    {
        .requiredEventFlag_0 = EventFlag_217,
        .disabledEventFlag_2 = EventFlag_221,
        .triggerType_4_0     = TriggerType_None,
        .sysState_0        = SysState_LoadOverlay,
        .eventParam_8_5      = 123,
        .mapOverlayIdx_8_25  = MapOverlayId_MAP3_S04,
    },
    {
        .requiredEventFlag_0 = EventFlag_218,
        .disabledEventFlag_2 = EventFlag_222,
        .triggerType_4_0     = TriggerType_None,
        .sysState_0        = SysState_LoadRoom,
        .eventParam_8_5      = 38,
    },
    {
        .requiredEventFlag_0 = EventFlag_219,
        .disabledEventFlag_2 = EventFlag_223,
        .triggerType_4_0     = TriggerType_None,
        .sysState_0        = SysState_LoadRoom,
        .eventParam_8_5      = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_250,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 87,
        .requiredItemId_6     = InventoryItemId_BloodPack,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 17, // `func_800D2CDC`
    },
    {
        .disabledEventFlag_2  = EventFlag_M3S03_PickupPlateOfHatter,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 78,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 4, // `func_800D1774`
    },
    {
        .disabledEventFlag_2  = EventFlag_M3S03_PickupPlateOfCat,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 77,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 5, // `func_800D17A0`
    },
    {
        .disabledEventFlag_2  = EventFlag_M3S03_PickupPlateOfTurtle,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 76,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 6, // `func_800D17CC`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 92,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 19, // `func_800D3128`
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 79,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 8, // `func_800D26D0`
    },
    {
        .requiredEventFlag_0  = EventFlag_254,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 74,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 26,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_254,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 74,
        .requiredItemId_6     = InventoryItemId_VideoTape,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 12, // `func_800D27F4`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 74,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 54,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 85,
        .sysState_0         = SysState_SaveMenu1,
        .eventParam_8_5       = 11,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 86,
        .sysState_0         = SysState_SaveMenu1,
        .eventParam_8_5       = 11,
    },
    {
        .disabledEventFlag_2  = EventFlag_M3S03_PickupBloodPack,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 75,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 13, // `func_800D2C2C`
    },
    {
        .disabledEventFlag_2  = EventFlag_M3S03_PickupDisinfectingAlcohol,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 93,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 14, // `func_800D2C58`
    },
    {
        .disabledEventFlag_2  = EventFlag_M3S03_PickupLighter,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 80,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 15, // `func_800D2C84`
    },
    {
        .disabledEventFlag_2  = EventFlag_M3S03_PickupBasementStoreroomKey,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 81,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 16, // `func_800D2CB0`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 82,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 9, // `func_800D2708`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 83,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 10, // `func_800D2740`
    },
    {
        .requiredEventFlag_0  = EventFlag_1611,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 3,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 4,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_1611,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 4,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 3,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1611,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 4,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltHospital3F_StairsArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 3,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltHospital3F_Room301Arrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 5,
        .sysState_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltHospital3F_Room303Broken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 6,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 32,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltHospital3F_Room303Broken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 32,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 6,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1616,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 7,
        .sysState_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1619,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 8,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 30,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
    },
    {
        .disabledEventFlag_2  = EventFlag_1619,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 30,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 8,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltHospital3F_LinenRoomLeftArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 31,
        .sysState_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1623,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 9,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 33,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag_2  = EventFlag_1623,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 33,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 9,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1625,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 10,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 11,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1625,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 11,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 10,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1628,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 12,
        .sysState_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1627,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 13,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 28,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag_2  = EventFlag_1627,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 28,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 13,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1631,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 14,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 20,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
    },
    {
        .disabledEventFlag_2  = EventFlag_1631,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 20,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 14,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1633,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 15,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 27,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag_2  = EventFlag_1633,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 27,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 15,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1635,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 16,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 26,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag_2  = EventFlag_1635,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 26,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 16,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1636,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 17,
        .sysState_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1639,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 18,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 25,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag_2  = EventFlag_1639,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 25,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 18,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1641,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 19,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 34,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag_2  = EventFlag_1641,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 34,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 19,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 21,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 22,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 23,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 24,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 35,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 36,
    },
    {
        .requiredEventFlag_0  = EventFlag_1565,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 40,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 41,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_1565,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 41,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 40,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1565,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 41,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltHospital2F_StairsArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 40,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltHospital2F_Room202Broken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 42,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 70,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltHospital2F_Room202Broken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 70,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 42,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1568,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 43,
        .sysState_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1571,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 44,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 69,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
    },
    {
        .disabledEventFlag_2  = EventFlag_1571,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 69,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 44,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1573,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 45,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 66,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
    },
    {
        .disabledEventFlag_2  = EventFlag_1573,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 66,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 45,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1575,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 67,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 68,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
    },
    {
        .disabledEventFlag_2  = EventFlag_1575,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 68,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 67,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_713,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 46,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 71,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_713,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 71,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 46,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 71,
        .requiredItemId_6     = InventoryItemId_PlateOfTurtle,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 7, // `func_800D1A58`
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 71,
        .requiredItemId_6     = InventoryItemId_PlateOfHatter,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 7, // `func_800D1A58`
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 71,
        .requiredItemId_6     = InventoryItemId_PlateOfCat,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 7, // `func_800D1A58`
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 71,
        .requiredItemId_6     = InventoryItemId_PlateOfQueen,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 7, // `func_800D1A58`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_281,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 71,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 7, // `func_800D1A58`
    },
    {
        .requiredEventFlag_0  = EventFlag_1579,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 47,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 48,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_1579,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 48,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 47,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1579,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 47,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1578,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 48,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1580,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 49,
        .sysState_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1582,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 50,
        .sysState_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1585,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 51,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 57,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
    },
    {
        .disabledEventFlag_2  = EventFlag_1585,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 57,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 51,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1587,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 52,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 63,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag_2  = EventFlag_1587,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 63,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 52,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1588,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 53,
        .sysState_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltHospital3F_NearElevatorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 54,
        .sysState_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_1593,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 55,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 62,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag_2  = EventFlag_1593,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 62,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 55,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltHospital3F_Room305Broken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 56,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 72,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltHospital3F_Room305Broken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 72,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 56,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 58,
        .sysState_0         = SysState_LoadRoom,
        .eventParam_8_5       = 59,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 60,
        .sysState_0         = SysState_LoadOverlay,
        .eventParam_8_5       = 61,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP3_S04,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 88,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 18, // `func_800D30FC`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 89,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 18, // `func_800D30FC`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 90,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 18, // `func_800D30FC`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 91,
        .sysState_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 18, // `func_800D30FC`
    },
    {
        .requiredEventFlag_0  = EventFlag_M3S03_PickupDisinfectingAlcohol,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 93,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 46,
    },
    {
        .requiredEventFlag_0  = EventFlag_M3S03_PickupDisinfectingAlcohol,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 94,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 46,
    },
    {
        .requiredEventFlag_0  = EventFlag_M3S03_PickupDisinfectingAlcohol,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 95,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 46,
    },
    {
        .requiredEventFlag_0  = EventFlag_M3S03_PickupDisinfectingAlcohol,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 96,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 46,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 97,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 56,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 98,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 56,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 99,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 56,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 100,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 57,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 101,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 57,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 102,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 59,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 103,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 59,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 104,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 59,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 105,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 59,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 106,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 60,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 107,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 60,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 108,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 58,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 109,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 58,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 110,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 58,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 111,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 61,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 112,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 61,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 113,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 61,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 114,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 61,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 115,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 60,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 116,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 60,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 117,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 60,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 118,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 60,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 119,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 58,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 120,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 58,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 121,
        .sysState_0         = SysState_ReadMessage,
        .eventParam_8_5       = 58,
    },
    {
        .disabledEventFlag_2  = EventFlag_1642,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 122,
        .sysState_0         = SysState_EventSetFlag,
    },
    {
        .triggerType_4_0 = TriggerType_EndOfArray,
    },
};
