    {
        .positionX = Q12(-62.4f),
        .paperMapIdx = PaperMapIdx_AltHospital2F,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(93.5f),
    },
    {
        .positionX = Q12(-96.7f),
        .paperMapIdx = PaperMapIdx_AltHospital3F,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 19,
        .positionZ = Q12(-98.4f),
    },
    {
        .positionX = Q12(-97.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 3,
        .positionZ = Q12(-99.8f),
    },
    {
        .positionX = Q12(-100.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 12,
        .positionZ = Q12(-100.8f),
    },
    {
        .positionX = Q12(-59.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 12,
        .positionZ = Q12(-87.0f),
    },
    {
        .positionX = Q12(-58.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(-88.0f),
    },
    {
        .positionX = Q12(-58.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(-91.2f),
    },
    {
        .positionX = Q12(-58.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(-97.6f),
    },
    {
        .positionX = Q12(-61.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 12,
        .positionZ = Q12(-101.4f),
    },
    {
        .positionX = Q12(-62.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(-98.2f),
    },
    {
        .positionX = Q12(-64.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 12,
        .positionZ = Q12(-99.8f),
    },
    {
        .positionX = Q12(-15.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 12,
        .positionZ = Q12(-107.2f),
    },
    {
        .positionX = Q12(-17.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(-108.8f),
    },
    {
        .positionX = Q12(-19.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(-108.8f),
    },
    {
        .positionX = Q12(-21.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 12,
        .positionZ = Q12(-107.2f),
    },
    {
        .positionX = Q12(-21.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(-104.6f),
    },
    {
        .positionX = Q12(-21.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(-101.4f),
    },
    {
        .positionX = Q12(-21.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(-98.2f),
    },
    {
        .positionX = Q12(-21.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(-95.0f),
    },
    {
        .positionX = Q12(-18.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(-103.4f),
    },
    {
        .positionX = Q12(-136.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 12,
        .positionZ = Q12(-58.4f),
    },
    {
        .positionX = Q12(-138.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 6,
        .positionZ = Q12(-63.2f),
    },
    {
        .positionX = Q12(-138.2f),
        .paperMapIdx = PaperMapIdx_24,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 0,
        .positionZ = Q12(-142.8f),
    },
    {
        .positionX = Q12(-141.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 6,
        .positionZ = Q12(-63.2f),
    },
    {
        .positionX = Q12(-17.4f),
        .paperMapIdx = PaperMapIdx_AltHospital2F,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(101.2f),
    },
    {
        .positionX = Q12(-96.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(-61.4f),
    },
    {
        .positionX = Q12(-56.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(-60.6f),
    },
    {
        .positionX = Q12(-16.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(-60.6f),
    },
    {
        .positionX = Q12(-139.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(-16.8f),
    },
    {
        .positionX = Q12(-100.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(-16.8f),
    },
    {
        .positionX = Q12(-60.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 12,
        .positionZ = Q12(-16.0f),
    },
    {
        .positionX = Q12(-56.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 12,
        .positionZ = Q12(-19.2f),
    },
    {
        .positionX = Q12(-23.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(-18.6f),
    },
    {
        .positionX = Q12(-138.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(-101.6f),
    },
    {
        .positionX = Q12(-143.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(-99.4f),
    },
    {
        .positionX = Q12(-138.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 6,
        .positionZ = Q12(-140.8f),
    },
    {
        .positionX = Q12(-138.2f),
        .paperMapIdx = PaperMapIdx_AltHospital3F,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(-61.2f),
    },
    {
        .positionX = Q12(-141.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 22,
        .positionZ = Q12(-142.4f),
    },
    {
        .positionX = Q12(-136.7f),
        .paperMapIdx = PaperMapIdx_AltHospital2F,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 19,
        .positionZ = Q12(101.6f),
    },
    {
        .positionX = Q12(-137.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 3,
        .positionZ = Q12(100.2f),
    },
    {
        .positionX = Q12(-140.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 12,
        .positionZ = Q12(99.2f),
    },
    {
        .positionX = Q12(-99.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 12,
        .positionZ = Q12(108.1f),
    },
    {
        .positionX = Q12(-97.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(107.1f),
    },
    {
        .positionX = Q12(-97.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(103.1f),
    },
    {
        .positionX = Q12(-97.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 12,
        .positionZ = Q12(96.9f),
    },
    {
        .positionX = Q12(-100.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 12,
        .positionZ = Q12(93.7f),
    },
    {
        .positionX = Q12(-101.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(96.9f),
    },
    {
        .positionX = Q12(-103.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 12,
        .positionZ = Q12(95.3f),
    },
    {
        .positionX = Q12(-57.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 12,
        .positionZ = Q12(93.4f),
    },
    {
        .positionX = Q12(-59.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(91.8f),
    },
    {
        .positionX = Q12(-61.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(91.8f),
    },
    {
        .positionX = Q12(-64.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 12,
        .positionZ = Q12(93.4f),
    },
    {
        .positionX = Q12(-64.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(96.0f),
    },
    {
        .positionX = Q12(-64.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(99.2f),
    },
    {
        .positionX = Q12(-64.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(102.4f),
    },
    {
        .positionX = Q12(-64.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(105.6f),
    },
    {
        .positionX = Q12(-60.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(97.2f),
    },
    {
        .positionX = Q12(-16.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 12,
        .positionZ = Q12(104.0f),
    },
    {
        .positionX = Q12(-17.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 6,
        .positionZ = Q12(99.2f),
    },
    {
        .positionX = Q12(-141.8f),
        .paperMapIdx = PaperMapIdx_AltHospital3F,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(-61.2f),
    },
    {
        .positionX = Q12(-21.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 6,
        .positionZ = Q12(99.2f),
    },
    {
        .positionX = Q12(17.8f),
        .paperMapIdx = PaperMapIdx_AltHospital1F,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(18.8f),
    },
    {
        .positionX = Q12(-136.95f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(59.15f),
    },
    {
        .positionX = Q12(-97.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(57.35f),
    },
    {
        .positionX = Q12(-60.05f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(63.85f),
    },
    {
        .positionX = Q12(-23.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(64.5f),
    },
    {
        .positionX = Q12(-140.85f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 12,
        .positionZ = Q12(23.0f),
    },
    {
        .positionX = Q12(-137.25f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 12,
        .positionZ = Q12(19.8f),
    },
    {
        .positionX = Q12(-102.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 12,
        .positionZ = Q12(20.95f),
    },
    {
        .positionX = Q12(-64.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 12,
        .positionZ = Q12(20.0f),
    },
    {
        .positionX = Q12(-24.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(20.2f),
    },
    {
        .positionX = Q12(-18.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(138.4f),
    },
    {
        .positionX = Q12(-23.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(140.6f),
    },
    {
        .positionX = Q12(17.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 19,
        .positionZ = Q12(59.1f),
    },
    {
        .positionX = Q12(-62.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 100,
        .triggerParam1 = 11,
        .positionZ = Q12(-59.04f),
    },
    {
        .positionX = Q12(-57.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 6,
        .positionZ = Q12(-21.0f),
    },
    {
        .positionX = Q12(-140.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 4,
        .positionZ = Q12(-23.2f),
    },
    {
        .positionX = Q12(-16.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 3,
        .positionZ = Q12(-20.8f),
    },
    {
        .positionX = Q12(-143.35f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 3,
        .positionZ = Q12(61.35f),
    },
    {
        .positionX = Q12(-16.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 4,
        .positionZ = Q12(140.6f),
    },
    {
        .positionX = Q12(-102.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 3,
        .positionZ = Q12(57.4f),
    },
    {
        .positionX = Q12(-98.54f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 188,
        .triggerParam1 = 4,
        .positionZ = Q12(21.0f),
    },
    {
        .positionX = Q12(-58.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 6,
        .positionZ = Q12(94.9f),
    },
    {
        .positionX = Q12(-62.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 6,
        .positionZ = Q12(110.9f),
    },
    {
        .positionX = Q12(-61.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 16,
        .positionZ = Q12(-96.0f),
    },
    {
        .positionX = Q12(-58.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 5,
        .positionZ = Q12(-59.4f),
    },
    {
        .positionX = Q12(-58.9f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 3,
        .positionZ = Q12(-59.2f),
    },
    {
        .positionX = Q12(-140.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 10,
        .triggerParam1 = 12,
        .positionZ = Q12(61.35f),
    },
    {
        .positionX = Q12(-20.88f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 8,
        .triggerParam1 = 4,
        .positionZ = Q12(-59.78f),
    },
    {
        .positionX = Q12(-20.7f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 72,
        .triggerParam1 = 4,
        .positionZ = Q12(-60.06f),
    },
    {
        .positionX = Q12(-21.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 116,
        .triggerParam1 = 4,
        .positionZ = Q12(-60.37f),
    },
    {
        .positionX = Q12(-21.18f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 199,
        .triggerParam1 = 6,
        .positionZ = Q12(-60.09f),
    },
    {
        .positionX = Q12(-103.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 4,
        .positionZ = Q12(-59.2f),
    },
    {
        .positionX = Q12(-60.82f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 190,
        .triggerParam1 = 14,
        .positionZ = Q12(20.0f),
    },
    {
        .positionX = Q12(-60.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 6,
        .positionZ = Q12(19.1f),
    },
    {
        .positionX = Q12(-60.02f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 62,
        .triggerParam1 = 15,
        .positionZ = Q12(20.0f),
    },
    {
        .positionX = Q12(-60.45f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 6,
        .positionZ = Q12(20.9f),
    },
    {
        .positionX = Q12(-62.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 12,
        .positionZ = Q12(17.6f),
    },
    {
        .positionX = Q12(-60.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 12,
        .positionZ = Q12(17.6f),
    },
    {
        .positionX = Q12(-60.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 6,
        .positionZ = Q12(17.2f),
    },
    {
        .positionX = Q12(-141.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 28,
        .positionZ = Q12(-100.5f),
    },
    {
        .positionX = Q12(-137.9f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 17,
        .positionZ = Q12(-99.5f),
    },
    {
        .positionX = Q12(-58.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 6,
        .positionZ = Q12(-16.8f),
    },
    {
        .positionX = Q12(-58.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 12,
        .positionZ = Q12(-17.6f),
    },
    {
        .positionX = Q12(-58.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 6,
        .positionZ = Q12(-18.4f),
    },
    {
        .positionX = Q12(-59.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 12,
        .positionZ = Q12(-17.6f),
    },
    {
        .positionX = Q12(-57.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 6,
        .positionZ = Q12(-18.4f),
    },
    {
        .positionX = Q12(-57.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 12,
        .positionZ = Q12(-17.6f),
    },
    {
        .positionX = Q12(-62.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 6,
        .positionZ = Q12(-20.0f),
    },
    {
        .positionX = Q12(-62.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 12,
        .positionZ = Q12(-20.8f),
    },
    {
        .positionX = Q12(-62.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 6,
        .positionZ = Q12(-21.6f),
    },
    {
        .positionX = Q12(-61.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 6,
        .positionZ = Q12(-20.0f),
    },
    {
        .positionX = Q12(-60.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 12,
        .positionZ = Q12(-20.8f),
    },
    {
        .positionX = Q12(-61.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 6,
        .positionZ = Q12(-21.6f),
    },
    {
        .positionX = Q12(-61.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 12,
        .positionZ = Q12(-20.8f),
    },
    {
        .positionX = Q12(-58.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 6,
        .positionZ = Q12(-20.0f),
    },
    {
        .positionX = Q12(-58.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 12,
        .positionZ = Q12(-20.8f),
    },
    {
        .positionX = Q12(-58.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 6,
        .positionZ = Q12(-21.6f),
    },
    {
        .positionX = Q12(-59.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 12,
        .positionZ = Q12(-20.8f),
    },
    {
        .positionX = Q12(-57.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 6,
        .positionZ = Q12(-20.0f),
    },
    {
        .positionX = Q12(-57.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 6,
        .positionZ = Q12(-21.6f),
    },
    {
        .positionX = Q12(-57.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 12,
        .positionZ = Q12(-20.8f),
    },
    {
        .positionX = Q12(-60.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 16,
        .triggerParam1 = 10,
        .positionZ = Q12(-60.0f),
    },
    {
        .positionX = Q12(143.3f),
        .paperMapIdx = PaperMapIdx_AltHospital1F,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 19,
        .positionZ = Q12(27.2f),
    },
    {
        .positionX = Q12(64.5f),
        .paperMapIdx = PaperMapIdx_AltHospitalBF,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 19,
        .positionZ = Q12(-54.8f),
    },
    {
        .positionX = Q12(17.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 3,
        .positionZ = Q12(60.5f),
    },
    {
        .positionX = Q12(-18.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(20.65f),
    },
    {
        .positionX = Q12(-101.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(-58.2f),
    },
    {
        .positionX = Q12(-62.55f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(-21.2f),
    },
    {
        .positionX = Q12(-57.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(-17.2f),
    },
    {
        .positionX = Q12(-61.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(-60.45f),
    }

