#include "bodyprog/bodyprog.h"
#include "bodyprog/math/math.h"
#include "bodyprog/player.h"
#include "main/rng.h"
#include "maps/map3/map3_s03.h"
#include "maps/particle.h"
#include "maps/characters/bloodsucker.h"
#include "maps/characters/player.h"
#include "maps/characters/puppet_nurse.h"

#include "../src/maps/characters/player.c"
