    {
      {
        .positionX_0 = Q12(4.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(180.0f),
        .flags_6 = 9,
        .minGameDifficulty_7_0 = GameDifficulty_Hard,
        .positionZ_8 = Q12(96.0f),
      },
      {
        .positionX_0 = Q12(-256.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(180.0f),
        .flags_6 = 10,
        .minGameDifficulty_7_0 = GameDifficulty_Hard,
        .positionZ_8 = Q12(-256.0f),
      },
      {
        .positionX_0 = Q12(-117.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(270.0f),
        .flags_6 = 6,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(3.0f),
      },
      {
        .positionX_0 = Q12(-123.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(270.0f),
        .flags_6 = 6,
        .minGameDifficulty_7_0 = GameDifficulty_Hard,
        .positionZ_8 = Q12(-3.0f),
      },
      {
        .positionX_0 = Q12(33.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 7,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-13.0f),
      },
      {
        .positionX_0 = Q12(-120.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 7,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-105.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 6,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-36.0f),
      },
      {
        .positionX_0 = Q12(-11.5f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(180.0f),
        .flags_6 = 6,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-110.0f),
      },
      {
        .positionX_0 = Q12(-12.5f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(180.0f),
        .flags_6 = 6,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-110.9f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
    },
    {
      {
        .positionX_0 = Q12(-104.0f),
        .charaId_4 = Chara_Romper,
        .rotationY_5 = Q8_ANGLE(180.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(9.0f),
      },
      {
        .positionX_0 = Q12(-95.0f),
        .charaId_4 = Chara_Romper,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(8.0f),
      },
      {
        .positionX_0 = Q12(-112.0f),
        .charaId_4 = Chara_Romper,
        .rotationY_5 = Q8_ANGLE(270.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(7.0f),
      },
      {
        .positionX_0 = Q12(-14.0f),
        .charaId_4 = Chara_Romper,
        .rotationY_5 = Q8_ANGLE(180.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-71.0f),
      },
      {
        .positionX_0 = Q12(-9.0f),
        .charaId_4 = Chara_Romper,
        .rotationY_5 = Q8_ANGLE(135.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-66.0f),
      },
      {
        .positionX_0 = Q12(-60.0f),
        .charaId_4 = Chara_Groaner,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-10.0f),
      },
      {
        .positionX_0 = Q12(-60.0f),
        .charaId_4 = Chara_Groaner,
        .rotationY_5 = Q8_ANGLE(180.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-70.0f),
      },
      {
        .positionX_0 = Q12(147.0f),
        .charaId_4 = Chara_Groaner,
        .rotationY_5 = Q8_ANGLE(315.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-20.0f),
      },
      {
        .positionX_0 = Q12(142.0f),
        .charaId_4 = Chara_Groaner,
        .rotationY_5 = Q8_ANGLE(45.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(-19.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
    },
