    {
      .positionX = -84,
      .positionZ = 11,
      .sizeX = 3,
      .sizeZ = 1,
      .height = 3,
    },
    {
      .positionX = -79,
      .positionZ = 10,
      .sizeX = 6,
      .sizeZ = 1,
      .height = 3,
    },
    {
      .positionX = -68,
      .positionZ = 9,
      .sizeX = 3,
      .sizeZ = 2,
      .height = 2,
    },
    {
      .positionX = -59,
      .positionZ = 11,
      .sizeX = 8,
      .sizeZ = 1,
      .height = 2,
    },
    {
      .positionX = -48,
      .positionZ = 10,
      .sizeX = 7,
      .sizeZ = 1,
      .height = 2,
    },
    {
      .positionX = -39,
      .positionZ = 10,
      .sizeX = 8,
      .sizeZ = 1,
      .height = 2,
    },
    {
      .positionX = -30,
      .positionZ = 13,
      .sizeX = 6,
      .sizeZ = 3,
      .height = 2,
    },
    {
      .positionX = -24,
      .positionZ = 12,
      .sizeX = 14,
      .sizeZ = 9,
      .height = 2,
    },
    {
      .positionX = -108,
      .positionZ = -11,
      .sizeX = 14,
      .sizeZ = 1,
      .height = 2,
    },
    {
      .positionX = -94,
      .positionZ = -11,
      .sizeX = 8,
      .sizeZ = 1,
      .height = 2,
    },
    {
      .positionX = -86,
      .positionZ = -12,
      .sizeX = 5,
      .sizeZ = 1,
      .height = 2,
    },
    {
      .positionX = -55,
      .positionZ = -12,
      .sizeX = 6,
      .sizeZ = 3,
      .height = 2,
    },
    {
      .positionX = -48,
      .positionZ = -12,
      .sizeX = 3,
      .sizeZ = 1,
      .height = 3,
    },
    {
      .positionX = -44,
      .positionZ = -12,
      .sizeX = 3,
      .sizeZ = 1,
      .height = 1,
    },
    {
      .positionX = -40,
      .positionZ = -10,
      .sizeX = 8,
      .sizeZ = 1,
      .height = 2,
    },
    {
      .positionX = -32,
      .positionZ = -12,
      .sizeX = 8,
      .sizeZ = 4,
      .height = 2,
    },
    {
      .positionX = -24,
      .positionZ = -12,
      .sizeX = 3,
      .sizeZ = 2,
      .height = 2,
    },
    {
      .positionX = -138,
      .positionZ = -71,
      .sizeX = 5,
      .sizeZ = 1,
      .height = 1,
    },
    {
      .positionX = -133,
      .positionZ = -79,
      .sizeX = 2,
      .sizeZ = 5,
      .height = 1,
    },
    {
      .positionX = -131,
      .positionZ = -89,
      .sizeX = 1,
      .sizeZ = 4,
      .height = 3,
    },
    {
      .positionX = -132,
      .positionZ = -96,
      .sizeX = 2,
      .sizeZ = 6,
      .height = 2,
    },
    {
      .positionX = -131,
      .positionZ = -103,
      .sizeX = 2,
      .sizeZ = 5,
      .height = 2,
    },
    {
      .positionX = -132,
      .positionZ = -107,
      .sizeX = 1,
      .sizeZ = 3,
      .height = 3,
    },
    {
      .positionX = -111,
      .positionZ = -21,
      .sizeX = 1,
      .sizeZ = 2,
      .height = 3,
    },
    {
      .positionX = -109,
      .positionZ = -40,
      .sizeX = 4,
      .sizeZ = 10,
      .height = 0,
    },
    {
      .positionX = -99,
      .positionZ = -69,
      .sizeX = 3,
      .sizeZ = 1,
      .height = 3,
    },
    {
      .positionX = -95,
      .positionZ = -68,
      .sizeX = 2,
      .sizeZ = 1,
      .height = 2,
    },
    {
      .positionX = -75,
      .positionZ = -70,
      .sizeX = 3,
      .sizeZ = 1,
      .height = 3,
    },
    {
      .positionX = -54,
      .positionZ = -70,
      .sizeX = 1,
      .sizeZ = 1,
      .height = 2,
    },
    {
      .positionX = -38,
      .positionZ = -70,
      .sizeX = 5,
      .sizeZ = 1,
      .height = 2,
    },
    {
      .positionX = -27,
      .positionZ = -70,
      .sizeX = 3,
      .sizeZ = 1,
      .height = 3,
    },
    {
      .positionX = -21,
      .positionZ = -71,
      .sizeX = 3,
      .sizeZ = 2,
      .height = 1,
    },
    {
      .positionX = -16,
      .positionZ = -71,
      .sizeX = 3,
      .sizeZ = 2,
      .height = 1,
    },
    {
      .positionX = -11,
      .positionZ = -67,
      .sizeX = 2,
      .sizeZ = 7,
      .height = 1,
    },
    {
      .positionX = -14,
      .positionZ = -68,
      .sizeX = 2,
      .sizeZ = 2,
      .height = 3,
    },
    {
      .positionX = 17,
      .positionZ = -70,
      .sizeX = 3,
      .sizeZ = 2,
      .height = 4,
    },
    {
      .positionX = -68,
      .positionZ = -92,
      .sizeX = 11,
      .sizeZ = 1,
      .height = 2,
    },
    {
      .positionX = -40,
      .positionZ = -92,
      .sizeX = 3,
      .sizeZ = 1,
      .height = 3,
    },
    {
      .positionX = -31,
      .positionZ = -92,
      .sizeX = 5,
      .sizeZ = 1,
      .height = 2,
    },
    {
      .positionX = -23,
      .positionZ = -89,
      .sizeX = 3,
      .sizeZ = 2,
      .height = 4,
    },
    {
      .positionX = 5,
      .positionZ = -91,
      .sizeX = 4,
      .sizeZ = 3,
      .height = 3,
    },
    {
      .positionX = 10,
      .positionZ = -91,
      .sizeX = 6,
      .sizeZ = 1,
      .height = 2,
    },
    {
      .positionX = -67,
      .positionZ = -27,
      .sizeX = 1,
      .sizeZ = 3,
      .height = 3,
    },
    {
      .positionX = -67,
      .positionZ = -37,
      .sizeX = 1,
      .sizeZ = 4,
      .height = 2,
    },
    {
      .positionX = -66,
      .positionZ = -60,
      .sizeX = 2,
      .sizeZ = 3,
      .height = 4,
    },
    {
      .positionX = -55,
      .positionZ = -15,
      .sizeX = 1,
      .sizeZ = 1,
      .height = 2,
    },
    {
      .positionX = -54,
      .positionZ = -47,
      .sizeX = 1,
      .sizeZ = 5,
      .height = 2,
    },
    {
      .positionX = -54,
      .positionZ = -56,
      .sizeX = 1,
      .sizeZ = 3,
      .height = 3,
    },
    {
      .positionX = -12,
      .positionZ = 106,
      .sizeX = 1,
      .sizeZ = 2,
      .height = 3,
    },
    {
      .positionX = -12,
      .positionZ = 98,
      .sizeX = 3,
      .sizeZ = 4,
      .height = 3,
    },
    {
      .positionX = -13,
      .positionZ = 93,
      .sizeX = 1,
      .sizeZ = 3,
      .height = 3,
    },
    {
      .positionX = -13,
      .positionZ = 88,
      .sizeX = 1,
      .sizeZ = 3,
      .height = 1,
    },
    {
      .positionX = -13,
      .positionZ = 82,
      .sizeX = 1,
      .sizeZ = 5,
      .height = 2,
    },
    {
      .positionX = -14,
      .positionZ = 75,
      .sizeX = 1,
      .sizeZ = 3,
      .height = 2,
    },
    {
      .positionX = -13,
      .positionZ = 64,
      .sizeX = 2,
      .sizeZ = 5,
      .height = 1,
    },
    {
      .positionX = -14,
      .positionZ = 49,
      .sizeX = 3,
      .sizeZ = 6,
      .height = 2,
    },
    {
      .positionX = -11,
      .positionZ = 26,
      .sizeX = 1,
      .sizeZ = 5,
      .height = 2,
    },
    {
      .positionX = -11,
      .positionZ = 22,
      .sizeX = 1,
      .sizeZ = 1,
      .height = 1,
    },
    {
      .positionX = -11,
      .positionZ = -27,
      .sizeX = 3,
      .sizeZ = 9,
      .height = 3,
    },
    {
      .positionX = -11,
      .positionZ = -38,
      .sizeX = 1,
      .sizeZ = 5,
      .height = 2,
    },
    {
      .positionX = -10,
      .positionZ = -43,
      .sizeX = 1,
      .sizeZ = 3,
      .height = 3,
    },
    {
      .positionX = -12,
      .positionZ = -58,
      .sizeX = 2,
      .sizeZ = 10,
      .height = 2,
    },
    {
      .positionX = 10,
      .positionZ = 106,
      .sizeX = 3,
      .sizeZ = 3,
      .height = 3,
    },
    {
      .positionX = 10,
      .positionZ = 102,
      .sizeX = 6,
      .sizeZ = 2,
      .height = 2,
    },
    {
      .positionX = 9,
      .positionZ = 98,
      .sizeX = 3,
      .sizeZ = 4,
      .height = 2,
    },
    {
      .positionX = 11,
      .positionZ = 89,
      .sizeX = 2,
      .sizeZ = 5,
      .height = 2,
    },
    {
      .positionX = 11,
      .positionZ = 76,
      .sizeX = 2,
      .sizeZ = 7,
      .height = 2,
    },
    {
      .positionX = 11,
      .positionZ = 68,
      .sizeX = 2,
      .sizeZ = 3,
      .height = 2,
    },
    {
      .positionX = 11,
      .positionZ = 49,
      .sizeX = 2,
      .sizeZ = 3,
      .height = 2,
    },
    {
      .positionX = 11,
      .positionZ = 40,
      .sizeX = 1,
      .sizeZ = 3,
      .height = 3,
    },
    {
      .positionX = 11,
      .positionZ = 32,
      .sizeX = 1,
      .sizeZ = 3,
      .height = 3,
    },
    {
      .positionX = 10,
      .positionZ = 29,
      .sizeX = 2,
      .sizeZ = 2,
      .height = 1,
    },
    {
      .positionX = 11,
      .positionZ = 22,
      .sizeX = 2,
      .sizeZ = 5,
      .height = 1,
    },
    {
      .positionX = 12,
      .positionZ = 12,
      .sizeX = 1,
      .sizeZ = 6,
      .height = 2,
    },
    {
      .positionX = 14,
      .positionZ = -19,
      .sizeX = 1,
      .sizeZ = 2,
      .height = 1,
    },
    {
      .positionX = 13,
      .positionZ = -27,
      .sizeX = 2,
      .sizeZ = 6,
      .height = 2,
    },
    {
      .positionX = 12,
      .positionZ = -35,
      .sizeX = 1,
      .sizeZ = 2,
      .height = 2,
    },
    {
      .positionX = 13,
      .positionZ = -39,
      .sizeX = 1,
      .sizeZ = 1,
      .height = 2,
    },
    {
      .positionX = 13,
      .positionZ = -48,
      .sizeX = 1,
      .sizeZ = 3,
      .height = 3,
    },
    {
      .positionX = 11,
      .positionZ = -53,
      .sizeX = 1,
      .sizeZ = 2,
      .height = 1,
    },
    {
      .positionX = 12,
      .positionZ = -60,
      .sizeX = 2,
      .sizeZ = 1,
      .height = 3,
    },
    {
      .positionX = 12,
      .positionZ = -66,
      .sizeX = 2,
      .sizeZ = 2,
      .height = 3,
    },
    {
      .positionX = -14,
      .positionZ = -96,
      .sizeX = 2,
      .sizeZ = 3,
      .height = 4,
    },
    {
      .isEndOfArray = true,
    },
