    {
        .positionX = Q12(98.0f),
        .paperMapIdx = PaperMapIdx_FogHospital1F,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 0,
        .positionZ = Q12(100.0f),
    },
    {
        .positionX = Q12(139.8f),
        .paperMapIdx = PaperMapIdx_FogCentralTown,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 16,
        .positionZ = Q12(-13.0f),
    },
    {
        .positionX = Q12(26.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 4,
        .positionZ = Q12(144.9f),
    },
    {
        .positionX = Q12(17.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(14.3f),
    },
    {
        .positionX = Q12(15.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 12,
        .positionZ = Q12(12.8f),
    },
    {
        .positionX = Q12(16.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(11.2f),
    },
    {
        .positionX = Q12(19.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(11.2f),
    },
    {
        .positionX = Q12(21.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(12.6f),
    },
    {
        .positionX = Q12(21.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 12,
        .positionZ = Q12(16.0f),
    },
    {
        .positionX = Q12(21.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(20.6f),
    },
    {
        .positionX = Q12(21.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(24.6f),
    },
    {
        .positionX = Q12(23.3f),
        .paperMapIdx = PaperMapIdx_FogHospital1F,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 19,
        .positionZ = Q12(28.0f),
    },
    {
        .positionX = Q12(23.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 3,
        .positionZ = Q12(26.6f),
    },
    {
        .positionX = Q12(18.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(29.0f),
    },
    {
        .positionX = Q12(57.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 19,
        .positionZ = Q12(19.1f),
    },
    {
        .positionX = Q12(97.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(20.4f),
    },
    {
        .positionX = Q12(101.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 3,
        .triggerParam1 = 4,
        .positionZ = Q12(20.6f),
    },
    {
        .positionX = Q12(99.7f),
        .paperMapIdx = PaperMapIdx_FogHospital1F,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 0,
        .positionZ = Q12(20.4f),
    },
    {
        .positionX = Q12(136.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(19.8f),
    },
    {
        .positionX = Q12(17.1f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(58.45f),
    },
    {
        .positionX = Q12(56.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(60.6f),
    },
    {
        .positionX = Q12(59.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(57.6f),
    },
    {
        .positionX = Q12(99.3f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(61.3f),
    },
    {
        .positionX = Q12(139.9f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(63.1f),
    },
    {
        .positionX = Q12(20.3f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(105.1f),
    },
    {
        .positionX = Q12(61.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(98.4f),
    },
    {
        .positionX = Q12(56.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(100.6f),
    },
    {
        .positionX = Q12(101.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(99.9f),
    },
    {
        .positionX = Q12(95.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(104.1f),
    },
    {
        .positionX = Q12(94.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(101.5f),
    },
    {
        .positionX = Q12(21.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(137.4f),
    },
    {
        .positionX = Q12(28.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 19,
        .positionZ = Q12(146.8f),
    },
    {
        .positionX = Q12(25.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(143.2f),
    },
    {
        .positionX = Q12(20.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 12,
        .positionZ = Q12(133.6f),
    },
    {
        .positionX = Q12(136.7f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(97.9f),
    },
    {
        .positionX = Q12(139.9f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(101.1f),
    },
    {
        .positionX = Q12(24.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 8,
        .positionZ = Q12(143.2f),
    },
    {
        .positionX = Q12(95.85f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 4,
        .positionZ = Q12(99.85f),
    },
    {
        .positionX = Q12(95.7f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 2,
        .positionZ = Q12(100.1f),
    },
    {
        .positionX = Q12(21.3f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 7,
        .positionZ = Q12(142.4f),
    },
    {
        .positionX = Q12(20.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 19,
        .positionZ = Q12(29.6f),
    },
    {
        .positionX = Q12(61.7f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 5,
        .positionZ = Q12(100.3f),
    },
    {
        .positionX = Q12(99.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(98.7f),
    },
    {
        .positionX = Q12(95.1f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(103.1f),
    },
    {
        .positionX = Q12(140.7f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 7,
        .positionZ = Q12(99.15f),
    },
    {
        .positionX = Q12(140.25f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 7,
        .positionZ = Q12(98.7f),
    },
    {
        .positionX = Q12(136.95f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 4,
        .positionZ = Q12(99.7f),
    },
    {
        .positionX = Q12(136.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 7,
        .positionZ = Q12(99.4f),
    },
    {
        .positionX = Q12(135.9f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(98.5f),
    },
    {
        .positionX = Q12(141.3f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 8,
        .positionZ = Q12(100.9f),
    },
    {
        .positionX = Q12(138.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(100.7f),
    },
    {
        .positionX = Q12(139.45f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(98.5f),
    },
    {
        .positionX = Q12(138.25f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(98.3f),
    },
    {
        .positionX = Q12(26.95f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 6,
        .positionZ = Q12(144.0f),
    },
    {
        .positionX = Q12(63.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 8,
        .positionZ = Q12(99.2f),
    },
    {
        .positionX = Q12(59.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 25,
        .positionZ = Q12(100.8f),
    },
    {
        .positionX = Q12(58.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 25,
        .positionZ = Q12(99.2f),
    },
    {
        .positionX = Q12(95.85f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 8,
        .positionZ = Q12(99.6f),
    },
    {
        .positionX = Q12(95.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 8,
        .positionZ = Q12(100.1f),
    },
    {
        .positionX = Q12(27.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = 0,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 6,
        .positionZ = Q12(143.6f),
    }

