#include "bodyprog/bodyprog.h"

s_EventParam D_800D2424[17] = {
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M3S00_FirstAidKit,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 16,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 3, // `MapEvent_FirstAidKitTake`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_195,
        .disabledEventFlag_2  = 196,
        .triggerType_4_0      = TriggerType_None,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 0,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_Fmv,
        .eventData_8_5        = 13,
        .flags_8_13           = 2,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = 196,
        .disabledEventFlag_2  = EventFlag_197,
        .triggerType_4_0      = TriggerType_None,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 0,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 4, // `func_800D0CF8`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 12,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_SaveMenu1,
        .eventData_8_5        = 10,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 4,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 47,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1424,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 5,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 0, // `MapEvent_DoorJammed`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_195,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 3,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 2,
        .flags_8_13           = 0,
        .field_8_19           = 20,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP6_S01,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1427,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 2,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadOverlay,
        .eventData_8_5        = 3,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP3_S01,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1431,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 1,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadOverlay,
        .eventData_8_5        = 7,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP3_S01,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1433,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 0,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadOverlay,
        .eventData_8_5        = 6,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP3_S01,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M3S00_PickupMap,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 14,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 5, // `MapEvent_MapTake`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 15,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 49,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 8,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 50,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 9,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 50,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 10,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 51,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 11,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 51,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_EndOfArray,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 0,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_Gameplay,
        .eventData_8_5        = 0,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
};
