#include "bodyprog/bodyprog.h"

s_EventData MAP_EVENTS[111] = {
    {
        .disabledEventFlag  = EventFlag_M3S01_HealthDrink,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 101,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 2, // `func_800D14BC`
    },
    {
        .disabledEventFlag  = EventFlag_M3S00_FirstAidKit,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 100,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `func_800D1500`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 67,
        .sysState         = SysState_SaveMenu1,
        .eventParam       = 10,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 75,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 13, // `func_800D2A88`
    },
    {
        .disabledEventFlag  = EventFlag_M3S01_PickupUnknownLiquid,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Item,
        .pointOfInterestIdx = 57,
        .requiredItemId     = InvItemId_PlasticBottle,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 7, // `MapEvent_UseBottleOnLiquid`
    },
    {
        .disabledEventFlag  = EventFlag_M3S01_PickupUnknownLiquid,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Item,
        .pointOfInterestIdx = 58,
        .requiredItemId     = InvItemId_PlasticBottle,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 7, // `MapEvent_UseBottleOnLiquid`
    },
    {
        .disabledEventFlag  = EventFlag_M3S01_PickupUnknownLiquid,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Item,
        .pointOfInterestIdx = 59,
        .requiredItemId     = InvItemId_PlasticBottle,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 7, // `MapEvent_UseBottleOnLiquid`
    },
    {
        .disabledEventFlag  = EventFlag_M3S01_PickupUnknownLiquid,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Item,
        .pointOfInterestIdx = 60,
        .requiredItemId     = InvItemId_PlasticBottle,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 7, // `MapEvent_UseBottleOnLiquid`
    },
    {
        .disabledEventFlag  = EventFlag_M3S01_PickupUnknownLiquid,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 57,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 6, // `MapEvent_UnknownLiquidInteract`
    },
    {
        .disabledEventFlag  = EventFlag_M3S01_PickupUnknownLiquid,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 58,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 6, // `MapEvent_UnknownLiquidInteract`
    },
    {
        .disabledEventFlag  = EventFlag_M3S01_PickupUnknownLiquid,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 59,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 6, // `MapEvent_UnknownLiquidInteract`
    },
    {
        .disabledEventFlag  = EventFlag_M3S01_PickupUnknownLiquid,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 60,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 6, // `MapEvent_UnknownLiquidInteract`
    },
    {
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 57,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 20,
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 58,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 20,
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 59,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 20,
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 60,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 20,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_M3S01_PickupPlasticBottle,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 62,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 8, // `MapEvent_PlasticBottleTake`
    },
    {
        .disabledEventFlag  = EventFlag_M3S01_PickupMap,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 63,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 10, // `MapEvent_MapTake1`
    },
    {
        .disabledEventFlag  = EventFlag_M3S01_PickupMap,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 64,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 10, // `MapEvent_MapTake1`
    },
    {
        .disabledEventFlag  = EventFlag_M3S01_PickupBasementKey,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 65,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 11, // `func_800D279C`
    },
    {
        .disabledEventFlag  = EventFlag_M3S01_GeneratorOn,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 66,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 12, // `MapEvent_Generator0`
    },
    {
        .requiredEventFlag  = EventFlag_M3S01_GeneratorOn,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 66,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 14, // `func_800D29A4`
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 55,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 5, // `sharedFunc_800D15F0_3_s01`
    },
    {
        .requiredEventFlag  = EventFlag_M3S01_GeneratorOn,
        .disabledEventFlag  = EventFlag_212,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 37,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 14,
        .sfxPairIdx_8_19 = SfxPairIdx_7,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 37,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 15,
    },
    {
        .requiredEventFlag  = EventFlag_M3S01_GeneratorOn,
        .disabledEventFlag  = EventFlag_212,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 36,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 14,
        .sfxPairIdx_8_19 = SfxPairIdx_7,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 36,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 15,
    },
    {
        .requiredEventFlag = EventFlag_216,
        .disabledEventFlag = EventFlag_220,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_LoadRoom,
        .eventParam      = 36,
    },
    {
        .requiredEventFlag  = EventFlag_M3S01_GeneratorOn,
        .disabledEventFlag  = EventFlag_213,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 12,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 14,
        .sfxPairIdx_8_19 = SfxPairIdx_7,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 12,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 15,
    },
    {
        .requiredEventFlag  = EventFlag_M3S01_GeneratorOn,
        .disabledEventFlag  = EventFlag_213,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 11,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 14,
        .sfxPairIdx_8_19 = SfxPairIdx_7,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 11,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 15,
    },
    {
        .requiredEventFlag = EventFlag_217,
        .disabledEventFlag = EventFlag_221,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_LoadRoom,
        .eventParam      = 11,
    },
    {
        .disabledEventFlag  = EventFlag_214,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 39,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 14,
        .sfxPairIdx_8_19 = SfxPairIdx_7,
    },
    {
        .disabledEventFlag  = EventFlag_214,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 38,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 14,
        .sfxPairIdx_8_19 = SfxPairIdx_7,
    },
    {
        .requiredEventFlag = EventFlag_218,
        .disabledEventFlag = EventFlag_222,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_LoadRoom,
        .eventParam      = 38,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltHospital2F_OperatingPrepRoomArrow,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 40,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_215,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 42,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 14,
        .sfxPairIdx_8_19 = SfxPairIdx_7,
    },
    {
        .disabledEventFlag  = EventFlag_215,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 41,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 14,
        .sfxPairIdx_8_19 = SfxPairIdx_7,
    },
    {
        .requiredEventFlag = EventFlag_219,
        .disabledEventFlag = EventFlag_223,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_LoadRoom,
        .eventParam      = 41,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltHospital2F_CorridorMidArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 43,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag = EventFlag_224,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_LoadOverlay,
        .eventParam      = 56,
        .flags_8_13          = 1,
        .mapIdx  = MapIdx_MAP3_S02,
    },
    {
        .requiredEventFlag  = EventFlag_M3S01_PickupBasementKey,
        .disabledEventFlag  = EventFlag_M3S01_BasementDoorOpen,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 10,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 4, // `func_800D1524`
    },
    {
        .requiredEventFlag  = EventFlag_M3S01_PickupBasementKey,
        .disabledEventFlag  = EventFlag_M3S01_BasementDoorOpen,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Item,
        .pointOfInterestIdx = 10,
        .requiredItemId     = InvItemId_BasementKey,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 4, // `func_800D1524`
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_585,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 10,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 15,
        .sfxPairIdx_8_19 = SfxPairIdx_19,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_585,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 15,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 10,
        .sfxPairIdx_8_19 = SfxPairIdx_19,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_1448,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 10,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 31,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 29,
    },
    {
        .disabledEventFlag  = EventFlag_M3S00_PickupMap,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 68,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 9, // `MapEvent_MapTake0`
    },
    {
        .disabledEventFlag  = EventFlag_1435,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 3,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 25,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .disabledEventFlag  = EventFlag_1435,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 25,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 3,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_1452,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 4,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_1436,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 5,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_1438,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 6,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_1443,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 7,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 20,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .disabledEventFlag  = EventFlag_1443,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 20,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 7,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_1445,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 8,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 19,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .disabledEventFlag  = EventFlag_1445,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 19,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 8,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltHospital1F_CorridorLeftBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 9,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 18,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltHospital1F_CorridorLeftBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 18,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 9,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltHospital1F_ExaminationMedicineArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 13,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_1441,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 21,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 22,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .disabledEventFlag  = EventFlag_1441,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 22,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 21,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogHospital1F_RightEntranceBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 26,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 27,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogHospital1F_RightEntranceBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 27,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 26,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogHospital1F_CorridorMidBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 28,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 34,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogHospital1F_CorridorMidBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 34,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 28,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogHospital1F_StairsBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 32,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 35,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogHospital1F_StairsBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 35,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 32,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogHospital1F_StairsLocked,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 29,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 30,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogHospital1F_StairsLocked,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 30,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 29,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_FogHospital1F_KitchenArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 33,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_1513,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 44,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 49,
        .sfxPairIdx_8_19 = SfxPairIdx_19,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_1513,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 49,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 44,
        .sfxPairIdx_8_19 = SfxPairIdx_19,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltHospitalBF_MorgueArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 47,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltHospitalBF_StoreroomArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 48,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltHospitalBF_BoilerRoomBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 50,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 53,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltHospitalBF_BoilerRoomBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 53,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 50,
        .sfxPairIdx_8_19 = SfxPairIdx_1,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_1520,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 51,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchAabb,
        .pointOfInterestIdx = 16,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 46,
    },
    {
        .triggerType      = TriggerType_TouchAabb,
        .pointOfInterestIdx = 45,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 17,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 69,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 30,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 70,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 31,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 71,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 32,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 72,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 33,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 73,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 34,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 76,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 38,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 77,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 35,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 78,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 34,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 79,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 35,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 80,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 39,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 81,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 34,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 82,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 35,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 83,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 40,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 84,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 40,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 85,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 39,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 86,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 39,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 87,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 39,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 88,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 39,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 89,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 39,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 90,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 39,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 91,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 35,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 92,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 35,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 93,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 40,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 94,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 40,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 95,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 40,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 96,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 34,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 97,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 40,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 98,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 40,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 99,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 35,
    },
    {
        .triggerType = TriggerType_EndOfArray,
    },
};
