    {
        .positionX = Q12(-20.0f),
        .paperMapIdx = PaperMapIdx_AltSewer,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 4,
        .positionZ = Q12(24.4f),
    },
    {
        .positionX = Q12(72.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(20.0f),
    },
    {
        .positionX = Q12(90.15f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 4,
        .positionZ = Q12(19.0f),
    },
    {
        .positionX = Q12(90.3f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 2,
        .positionZ = Q12(19.3f),
    },
    {
        .positionX = Q12(90.3f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 2,
        .positionZ = Q12(18.7f),
    },
    {
        .positionX = Q12(-20.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 16,
        .triggerParam1 = 8,
        .positionZ = Q12(32.0f),
    },
    {
        .positionX = Q12(-20.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 16,
        .triggerParam1 = 8,
        .positionZ = Q12(50.0f),
    },
    {
        .positionX = Q12(-61.5f),
        .paperMapIdx = PaperMapIdx_24,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(-85.7f),
    },
    {
        .positionX = Q12(-22.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 4,
        .positionZ = Q12(26.4f),
    },
    {
        .positionX = Q12(-20.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 16,
        .triggerParam1 = 16,
        .positionZ = Q12(36.0f),
    },
    {
        .positionX = Q12(20.87f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(75.52f),
    },
    {
        .positionX = Q12(18.61f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(75.17f),
    },
    {
        .positionX = Q12(26.36f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(60.16f),
    }

