    {
        .positionX = Q12(102.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(19.4f),
    },
    {
        .positionX = Q12(102.9f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(58.1f),
    },
    {
        .positionX = Q12(56.3f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 6,
        .positionZ = Q12(58.7f),
    },
    {
        .positionX = Q12(-152.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 7,
        .positionZ = Q12(-23.0f),
    },
    {
        .positionX = Q12(59.9f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 1,
        .triggerParam1 = 1,
        .positionZ = Q12(62.0f),
    },
    {
        .positionX = Q12(59.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 6,
        .positionZ = Q12(62.0f),
    },
    {
        .positionX = Q12(59.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 1,
        .triggerParam1 = 1,
        .positionZ = Q12(21.9f),
    },
    {
        .positionX = Q12(59.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 6,
        .positionZ = Q12(21.9f),
    },
    {
        .positionX = Q12(62.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 8,
        .positionZ = Q12(17.9f),
    },
    {
        .positionX = Q12(63.3f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 8,
        .positionZ = Q12(19.1f),
    },
    {
        .positionX = Q12(61.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 8,
        .positionZ = Q12(22.7f),
    },
    {
        .positionX = Q12(32.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 8,
        .positionZ = Q12(-142.5f),
    },
    {
        .positionX = Q12(103.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 7,
        .positionZ = Q12(57.3f),
    },
    {
        .positionX = Q12(-157.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 7,
        .positionZ = Q12(-8.0f),
    },
    {
        .positionX = Q12(103.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 7,
        .positionZ = Q12(17.6f),
    },
    {
        .positionX = Q12(104.25f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(60.0f),
    },
    {
        .positionX = Q12(101.67f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 170,
        .triggerParam1 = 8,
        .positionZ = Q12(19.05f),
    },
    {
        .positionX = Q12(102.13f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 56,
        .triggerParam1 = 11,
        .positionZ = Q12(19.41f),
    },
    {
        .positionX = Q12(101.27f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 179,
        .triggerParam1 = 7,
        .positionZ = Q12(19.9f),
    },
    {
        .positionX = Q12(62.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 6,
        .positionZ = Q12(22.3f),
    },
    {
        .positionX = Q12(60.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 16,
        .positionZ = Q12(20.5f),
    },
    {
        .positionX = Q12(60.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 16,
        .positionZ = Q12(19.5f),
    },
    {
        .positionX = Q12(61.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 8,
        .positionZ = Q12(20.0f),
    },
    {
        .positionX = Q12(58.1f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 4,
        .positionZ = Q12(62.3f),
    },
    {
        .positionX = Q12(61.1f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 6,
        .positionZ = Q12(18.7f),
    },
    {
        .positionX = Q12(62.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 3,
        .positionZ = Q12(21.3f),
    },
    {
        .positionX = Q12(101.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 19,
        .positionZ = Q12(20.8f),
    },
    {
        .positionX = Q12(62.9f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 6,
        .positionZ = Q12(20.7f),
    },
    {
        .positionX = Q12(59.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 6,
        .positionZ = Q12(19.15f),
    },
    {
        .positionX = Q12(60.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 5,
        .positionZ = Q12(22.2f),
    },
    {
        .positionX = Q12(57.85f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 4,
        .positionZ = Q12(61.4f),
    },
    {
        .positionX = Q12(57.85f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 4,
        .positionZ = Q12(60.95f),
    },
    {
        .positionX = Q12(56.75f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 8,
        .positionZ = Q12(61.85f),
    },
    {
        .positionX = Q12(59.1f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 6,
        .positionZ = Q12(59.95f),
    },
    {
        .positionX = Q12(104.3f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 11,
        .positionZ = Q12(61.8f),
    },
    {
        .positionX = Q12(104.3f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 4,
        .positionZ = Q12(59.8f),
    },
    {
        .positionX = Q12(104.45f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 2,
        .positionZ = Q12(59.7f),
    },
    {
        .positionX = Q12(102.86f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(63.1f),
    },
    {
        .positionX = Q12(100.75f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(20.94f),
    },
    {
        .positionX = Q12(100.14f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .unused_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(20.69f),
    }
