#include "bodyprog/bodyprog.h"

s_EventData MAP_EVENTS[121] = {
    {
        .disabledEventFlag  = EventFlag_M1S02_Ampoule0,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 107,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag  = EventFlag_M1S02_ShotgunShells0,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 108,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag  = EventFlag_M1S02_ShotgunShells1,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 109,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag  = EventFlag_M1S02_FirstAidKit0,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 110,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag  = EventFlag_M1S02_HandgunBullets0,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 111,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag  = EventFlag_M1S02_HandgunBullets1,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 112,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag  = EventFlag_M1S02_HandgunBullets2,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 113,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag  = EventFlag_M1S02_Ampoule1,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 114,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag  = EventFlag_M1S02_HealthDrink0,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 115,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag  = EventFlag_M1S02_FirstAidKit1,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 116,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag  = EventFlag_M1S02_HealthDrink1,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 117,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag  = EventFlag_91,
        .triggerType      = TriggerType_TouchAabb,
        .pointOfInterestIdx = 1,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 5, // `func_800DA384`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag = EventFlag_225,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_EventCallFunc,
        .eventParam      = 21, // `func_800DD420`
    },
    {
        .requiredEventFlag  = EventFlag_M1S03_KeyDownTheDrain,
        .disabledEventFlag  = EventFlag_M1S02_PickupClassroomKey,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 103,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 20, // `func_800DD208`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 101,
        .sysState         = SysState_SaveMenu1,
        .eventParam       = 4,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 102,
        .sysState         = SysState_SaveMenu1,
        .eventParam       = 4,
    },
    {
        .disabledEventFlag  = EventFlag_118,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 40,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 18, // `func_800DC1E0`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_119,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 39,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 18, // `func_800DC1E0`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_120,
        .triggerType      = TriggerType_TouchAabb,
        .pointOfInterestIdx = 41,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 19, // `func_800DCF00`
    },
    {
        .requiredEventFlag = EventFlag_120,
        .triggerType     = TriggerType_None,
        .sysState        = SysState_LoadOverlay,
        .eventParam      = 18,
        .mapIdx  = MapIdx_MAP1_S05,
    },
    {
        .disabledEventFlag  = EventFlag_96,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 37,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 15, // `func_800DBB7C`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 38,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 52,
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 36,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 16, // `func_800DBF88`
    },
    {
        .requiredEventFlag  = EventFlag_96,
        .disabledEventFlag  = EventFlag_M1S02_PickupShotgun,
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 35,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 17, // `func_800DBFC8`
    },
    {
        .disabledEventFlag  = EventFlag_M1S02_PickupRubberBall,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 33,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 13, // `func_800DB33C`
    },
    {
        .disabledEventFlag  = EventFlag_M1S02_PickupRubberBall,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 34,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 13, // `func_800DB33C`
    },
    {
        .disabledEventFlag  = EventFlag_98,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 91,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 14, // `func_800DB368`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 42,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 50,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_M1S02_PickupPictureCard,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 29,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 12, // `func_800DB310`
    },
    {
        .disabledEventFlag  = EventFlag_M1S02_PickupPictureCard,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 30,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 12, // `func_800DB310`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 31,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 45,
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 32,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 45,
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_AltSchool1F_SecretDoorArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 12,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 26,
        .sfxPairIdx_8_19 = SfxPairIdx_2,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_AltSchool1F_SecretDoorArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 26,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 12,
        .sfxPairIdx_8_19 = SfxPairIdx_2,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_SecretDoorLocked,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 26,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 10, // `func_800DAD2C`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Item,
        .pointOfInterestIdx = 26,
        .requiredItemId     = InventoryItemId_PictureCard,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 11, // `func_800DB058`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 19,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 8, // `func_800DA8F8`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 20,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 6, // `func_800DA9D4`
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 21,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 7, // `func_800DAA00`
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_LobbyTopArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 47,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 52,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_LobbyTopArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 52,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 47,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_LobbyBotBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 4,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_LobbyBotBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 5,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_AltSchool1F_CourtyardBotArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 8,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 6,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_AltSchool1F_CourtyardBotArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 6,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 8,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_CourtyardBotArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 8,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_CourtyardBotLocked,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 6,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_BotRightCorridorArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 48,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 64,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_BotRightCorridorArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 64,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 48,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_AltSchool1F_BotLeftCorridorArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 49,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 79,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_AltSchool1F_BotLeftCorridorArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 79,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 49,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_BotLeftCorridorArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 79,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_BotLeftCorridorLocked,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 49,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_InfirmaryArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 51,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 54,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_InfirmaryArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 54,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 51,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_ReceptionArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 50,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 53,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_ReceptionArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 53,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 50,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_AltSchool1F_TopRightCorridorArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 65,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 55,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_AltSchool1F_TopRightCorridorArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 55,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 65,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_TopRightCorridorArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 65,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_TopRightCorridorLocked,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 55,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_AltSchool1F_TopLeftCorridorArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 56,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 80,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_AltSchool1F_TopLeftCorridorArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 80,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 56,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_TopLeftCorridorArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 80,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_TopLeftCorridorLocked,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 56,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_StorageArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 58,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 61,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_StorageArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 61,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 58,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_UntitledLobbyBotArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 59,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 62,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_UntitledLobbyBotArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 62,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 59,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_HallLeftArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 60,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 72,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_HallLeftArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 72,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 60,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_CourtyardTopArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 9,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 7,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_CourtyardTopArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 7,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 9,
        .sfxPairIdx_8_19 = SfxPairIdx_13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_BotClassRoomBotArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 66,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 73,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_BotClassRoomBotArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 73,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 66,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_BotClassRoomTopBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 67,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_BotClassRoomTopBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 74,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_TopClassRoomBotArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 68,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 76,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_TopClassRoomBotArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 76,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 68,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_TopClassRoomTopArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 69,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 77,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_TopClassRoomTopArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 77,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 69,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_ClassRoomMidArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 78,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 75,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_ClassRoomMidArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 75,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 78,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_HallMidArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 70,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 71,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_HallMidArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 71,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 70,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_WomensBathroomArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 81,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 10,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .mapIdx   = MapIdx_MAP1_S03,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_WomensBathroomArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 10,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 81,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_MensBathroomArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 82,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 11,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_MensBathroomArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 11,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 82,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_BotTeachersRoomBotArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 83,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 87,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_BotTeachersRoomBotArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 87,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 83,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_BotTeachersRoomTopArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 84,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 88,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_BotTeachersRoomTopArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 88,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 84,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_TopTeachersRoomBotBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 85,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_TopTeachersRoomBotBroken,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 90,
        .sysState         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_TopTeachersRoomTopArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 86,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 91,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_TopTeachersRoomTopArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 91,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 86,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_TeacherMidArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 89,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 92,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_TeacherMidArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 92,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 89,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchoolBF_StorageArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 96,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 98,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchoolBF_StorageArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 98,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 96,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchoolBF_BoilerRoomArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 97,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 17,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchoolBF_BoilerRoomArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 17,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 97,
        .sfxPairIdx_8_19 = SfxPairIdx_12,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_AltSchool1F_RightCorridorBotArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 27,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 28,
        .sfxPairIdx_8_19 = SfxPairIdx_8,
    },
    {
        .requiredEventFlag  = EventFlag_MapMark_AltSchool1F_RightCorridorBotArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 28,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 27,
        .sfxPairIdx_8_19 = SfxPairIdx_8,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_RightCorridorBotArrows,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 28,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_RightCorridorBotLocked,
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 27,
        .sysState         = SysState_EventCallFunc,
        .eventParam       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .triggerType      = TriggerType_TouchAabb,
        .pointOfInterestIdx = 93,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 15,
        .mapIdx   = MapIdx_MAP1_S03,
    },
    {
        .triggerType      = TriggerType_TouchAabb,
        .pointOfInterestIdx = 94,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 14,
    },
    {
        .triggerType      = TriggerType_TouchAabb,
        .pointOfInterestIdx = 100,
        .sysState         = SysState_LoadRoom,
        .eventParam       = 13,
    },
    {
        .triggerType      = TriggerType_TouchAabb,
        .pointOfInterestIdx = 95,
        .sysState         = SysState_LoadOverlay,
        .eventParam       = 16,
        .mapIdx   = MapIdx_MAP1_S03,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_LeftMidCorridorBroken,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 22,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_RightCorridorMidBroken,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 23,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_UntitledLobbyTopCross,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 25,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 43,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 46,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 44,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 46,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 46,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 48,
    },
    {
        .triggerType      = TriggerType_TouchObbFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 105,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 54,
    },
    {
        .triggerType      = TriggerType_TouchFacing,
        .activationType   = TriggerActivationType_Button,
        .pointOfInterestIdx = 104,
        .sysState         = SysState_ReadMessage,
        .eventParam       = 53,
    },
    {
        .disabledEventFlag  = EventFlag_MapMark_AltSchool1F_RightCorridorBotDots,
        .triggerType      = TriggerType_TouchAabb,
        .activationType   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx = 106,
        .sysState         = SysState_EventSetFlag,
    },
    {
        .triggerType = TriggerType_EndOfArray,
    },
};
