#include "bodyprog/bodyprog.h"

s_EventData MAP_EVENTS[121] = {
    {
        .disabledEventFlag_2  = EventFlag_M1S02_Ampoule0,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 107,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag_2  = EventFlag_M1S02_ShotgunShells0,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 108,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag_2  = EventFlag_M1S02_ShotgunShells1,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 109,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag_2  = EventFlag_M1S02_FirstAidKit0,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 110,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag_2  = EventFlag_M1S02_HandgunBullets0,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 111,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag_2  = EventFlag_M1S02_HandgunBullets1,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 112,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag_2  = EventFlag_M1S02_HandgunBullets2,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 113,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag_2  = EventFlag_M1S02_Ampoule1,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 114,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag_2  = EventFlag_M1S02_HealthDrink0,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 115,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag_2  = EventFlag_M1S02_FirstAidKit1,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 116,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag_2  = EventFlag_M1S02_HealthDrink1,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 117,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 3, // `func_800DA200`
    },
    {
        .disabledEventFlag_2  = EventFlag_91,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 1,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 5, // `func_800DA384`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0 = EventFlag_225,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_EventCallFunc,
        .eventParam_8_5      = 21, // `func_800DD420`
    },
    {
        .requiredEventFlag_0  = EventFlag_M1S03_KeyDownTheDrain,
        .disabledEventFlag_2  = EventFlag_M1S02_PickupClassroomKey,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 103,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 20, // `func_800DD208`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 101,
        .sysState_8_0         = SysState_SaveMenu1,
        .eventParam_8_5       = 4,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 102,
        .sysState_8_0         = SysState_SaveMenu1,
        .eventParam_8_5       = 4,
    },
    {
        .disabledEventFlag_2  = EventFlag_118,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 40,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 18, // `func_800DC1E0`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_119,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 39,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 18, // `func_800DC1E0`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_120,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 41,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 19, // `func_800DCF00`
    },
    {
        .requiredEventFlag_0 = EventFlag_120,
        .triggerType_4_0     = TriggerType_None,
        .sysState_8_0        = SysState_LoadOverlay,
        .eventParam_8_5      = 18,
        .mapOverlayIdx_8_25  = MapOverlayId_MAP1_S05,
    },
    {
        .disabledEventFlag_2  = EventFlag_96,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 37,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 15, // `func_800DBB7C`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 38,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 52,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 36,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 16, // `func_800DBF88`
    },
    {
        .requiredEventFlag_0  = EventFlag_96,
        .disabledEventFlag_2  = EventFlag_M1S02_PickupShotgun,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 35,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 17, // `func_800DBFC8`
    },
    {
        .disabledEventFlag_2  = EventFlag_M1S02_PickupRubberBall,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 33,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 13, // `func_800DB33C`
    },
    {
        .disabledEventFlag_2  = EventFlag_M1S02_PickupRubberBall,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 34,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 13, // `func_800DB33C`
    },
    {
        .disabledEventFlag_2  = EventFlag_98,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 91,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 14, // `func_800DB368`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 42,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 50,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_M1S02_PickupPictureCard,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 29,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 12, // `func_800DB310`
    },
    {
        .disabledEventFlag_2  = EventFlag_M1S02_PickupPictureCard,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 30,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 12, // `func_800DB310`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 31,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 45,
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 32,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 45,
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_AltSchool1F_SecretDoorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 12,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 26,
        .field_8_19           = 2,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_AltSchool1F_SecretDoorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 26,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 12,
        .field_8_19           = 2,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_SecretDoorLocked,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 26,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 10, // `func_800DAD2C`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 26,
        .requiredItemId_6     = InventoryItemId_PictureCard,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 11, // `func_800DB058`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 19,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 8, // `func_800DA8F8`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 20,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 6, // `func_800DA9D4`
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 21,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 7, // `func_800DAA00`
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_LobbyTopArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 47,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 52,
        .field_8_19           = 13,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_LobbyTopArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 52,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 47,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_LobbyBotBroken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 4,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_LobbyBotBroken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 5,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_AltSchool1F_CourtyardBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 8,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 6,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_AltSchool1F_CourtyardBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 6,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 8,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_CourtyardBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 8,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_CourtyardBotLocked,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 6,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_BotRightCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 48,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 64,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_BotRightCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 64,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 48,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_AltSchool1F_BotLeftCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 49,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 79,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_AltSchool1F_BotLeftCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 79,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 49,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_BotLeftCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 79,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_BotLeftCorridorLocked,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 49,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_InfirmaryArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 51,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 54,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_InfirmaryArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 54,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 51,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_ReceptionArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 50,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 53,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_ReceptionArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 53,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 50,
        .field_8_19           = 12,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_AltSchool1F_TopRightCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 65,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 55,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_AltSchool1F_TopRightCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 55,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 65,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_TopRightCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 65,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_TopRightCorridorLocked,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 55,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_AltSchool1F_TopLeftCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 56,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 80,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_AltSchool1F_TopLeftCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 80,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 56,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_TopLeftCorridorArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 80,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_TopLeftCorridorLocked,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 56,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_StorageArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 58,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 61,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_StorageArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 61,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 58,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_UntitledLobbyBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 59,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 62,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_UntitledLobbyBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 62,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 59,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_HallLeftArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 60,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 72,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_HallLeftArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 72,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 60,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_CourtyardTopArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 9,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 7,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_CourtyardTopArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 7,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 9,
        .field_8_19           = 13,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_BotClassRoomBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 66,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 73,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_BotClassRoomBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 73,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 66,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_BotClassRoomTopBroken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 67,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_BotClassRoomTopBroken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 74,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_TopClassRoomBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 68,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 76,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_TopClassRoomBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 76,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 68,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_TopClassRoomTopArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 69,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 77,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_TopClassRoomTopArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 77,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 69,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_ClassRoomMidArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 78,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 75,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_ClassRoomMidArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 75,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 78,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_HallMidArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 70,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 71,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_HallMidArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 71,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 70,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_WomensBathroomArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 81,
        .sysState_8_0         = SysState_LoadOverlay,
        .eventParam_8_5       = 10,
        .field_8_19           = 12,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP1_S03,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_WomensBathroomArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 10,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 81,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_MensBathroomArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 82,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 11,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_MensBathroomArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 11,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 82,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_BotTeachersRoomBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 83,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 87,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_BotTeachersRoomBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 87,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 83,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_BotTeachersRoomTopArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 84,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 88,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_BotTeachersRoomTopArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 88,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 84,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_TopTeachersRoomBotBroken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 85,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_TopTeachersRoomBotBroken,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 90,
        .sysState_8_0         = SysState_EventCallFunc,
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_TopTeachersRoomTopArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 86,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 91,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_TopTeachersRoomTopArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 91,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 86,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_TeacherMidArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 89,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 92,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_TeacherMidArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 92,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 89,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchoolBF_StorageArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 96,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 98,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchoolBF_StorageArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 98,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 96,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchoolBF_BoilerRoomArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 97,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 17,
        .field_8_19           = 12,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchoolBF_BoilerRoomArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 17,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 97,
        .field_8_19           = 12,
        .field_8_24           = 1,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_AltSchool1F_RightCorridorBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 27,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 28,
        .field_8_19           = 8,
    },
    {
        .requiredEventFlag_0  = EventFlag_MapMark_AltSchool1F_RightCorridorBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 28,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 27,
        .field_8_19           = 8,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_RightCorridorBotArrows,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 28,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_RightCorridorBotLocked,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 27,
        .sysState_8_0         = SysState_EventCallFunc,
        .eventParam_8_5       = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 93,
        .sysState_8_0         = SysState_LoadOverlay,
        .eventParam_8_5       = 15,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP1_S03,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 94,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 14,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 100,
        .sysState_8_0         = SysState_LoadRoom,
        .eventParam_8_5       = 13,
    },
    {
        .triggerType_4_0      = TriggerType_TouchAabb,
        .pointOfInterestIdx_5 = 95,
        .sysState_8_0         = SysState_LoadOverlay,
        .eventParam_8_5       = 16,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP1_S03,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_LeftMidCorridorBroken,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 22,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_RightCorridorMidBroken,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 23,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_UntitledLobbyTopCross,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 25,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 43,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 46,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 44,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 46,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 46,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 48,
    },
    {
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 105,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 54,
    },
    {
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 104,
        .sysState_8_0         = SysState_ReadMessage,
        .eventParam_8_5       = 53,
    },
    {
        .disabledEventFlag_2  = EventFlag_MapMark_AltSchool1F_RightCorridorBotDots,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 106,
        .sysState_8_0         = SysState_EventSetFlag,
    },
    {
        .triggerType_4_0 = TriggerType_EndOfArray,
    },
};
