import sys
import os

# Patch garbage bytes in .bss segment

if __name__ == "__main__":
    match sys.argv[1]:
        case "screens/stream" | "build/USA/out/VIN/STREAM.BIN":
            file = open("build/USA/out/VIN/STREAM.BIN", "r+b")
            file.seek(0x12AE4)
            file.write(b'\xE4\x73\x40\xAC')
            file.close()
        case "bodyprog" | "build/USA/out/1ST/BODYPROG.BIN" | "build/JAP0/out/1ST/BODYPROG.BIN":
            usaPath = "build/USA/out/1ST/BODYPROG.BIN"
            jap0Path = "build/JAP0/out/1ST/BODYPROG.BIN"
            if os.path.isfile(usaPath):
                file = open(usaPath, "r+b")
                file.seek(0xA23DC)
                file.write(b'\x0A\x09\x2E\x62')
                file.seek(0xA24CC)
                file.write(b'\x38\x0D\x0A\x09')
                file.seek(0xA2B8C)
                file.write(b'\x0D\x0A\x09\x2E')
                file.seek(0xA3F9C)
                file.write(b'\x09\x30\x78\x61')
                file.seek(0x9827C)
                file.write(b'\x22\x00\xA2\x97')
                file.seek(0x98284)
                file.write(b'\x21\x10\x46\x00')
                file.seek(0x9B08C)
                file.write(b'\x02\x00\x01\x00')
                file.seek(0x9CA4C)
                file.write(b'\x04\xCF\x41\x76')
                file.seek(0x9CA54)
                file.write(b'\x00\x18\xE3\xB8')
                file.seek(0x9F75C)
                file.write(b'\x10\x00\xB0\x8F')
                file.seek(0x9FD88)
                file.write(b'\x00\x00\x42\x30')
                file.seek(0x9FD8C)
                file.write(b'\x07\x00\x40\x14')
                file.seek(0x9FD94)
                file.write(b'\x0F\x80\x02\x3C')
                file.seek(0x9F774)
                file.write(b'\x21\x80\x80\x00')
                file.seek(0x9F8F4)
                file.write(b'\x00\x00\x02\x00')
                file.seek(0x9F96C)
                file.write(b'\x10\x00\xB0\x8F')
                file.seek(0x9FABC)
                file.write(b'\x30\x00\xA4\x27')
                file.seek(0x9FACC)
                file.write(b'\x61\x26\x01\x0C')
                file.seek(0x910CC)
                file.write(b'\x3C\x38\x92\xD8')
                file.seek(0x910D0)
                file.write(b'\x00\x00\x00\x00')
                file.seek(0x981B4)
                file.write(b'\x80\x18\x13\x00')
                file.seek(0x981B8)
                file.write(b'\x00\x00\x00\x00')
                file.seek(0x981E0)
                file.write(b'\x00\x70\xE5\x8D')
                file.seek(0x981E4)
                file.write(b'\x05\x00\x02\x24')
                file.seek(0x981EC)
                file.write(b'\x28\x00\x02\x24')
                file.seek(0x981F0)
                file.write(b'\x00\x00\x00\x00')
                file.seek(0x9821C)
                file.write(b'\x21\x10\x49\x00')
                file.seek(0x98220)
                file.write(b'\x00\x00\x00\x00')
                file.close()
            if os.path.isfile(jap0Path):
                file = open(jap0Path, "r+b")
                file.seek(0x9A71C)
                file.write(b'\x00\x00\x58\x00')
                file.seek(0x9A74C)
                file.write(b'\x04\x04\x04\x04')
                file.seek(0x9D5BC)
                file.write(b'\x00\xFE\x00\x00')
                file.seek(0x9EF7C)
                file.write(b'\x10\x00\xB0\xAF')
                file.seek(0x9EF84)
                file.write(b'\x00\x00\x00\x16')
                file.seek(0xA22B8)
                file.write(b'\x00\x4E\x0A\x09\x09\x09\x82\xB7')
                file.seek(0xA22C4)
                file.write(b'\x8C\x8C\x82\xC6')
                file.seek(0xA490C)
                file.write(b'\x3A\x20\x25\x64')
                file.seek(0xA49FC)
                file.write(b'\x54\x81\x09\x80')
                file.seek(0xA50BC)
                file.write(b'\x73\x5F\x6F\x72')
                file.seek(0xA64CC)
                file.write(b'\x6F\x72\x67\x65')
                file.close()
        case "screens/b_konami" | "build/USA/out/1ST/B_KONAMI.BIN":
            # Random pad bytes between b_konami.c .data and lzss.c .data.
            file = open("build/USA/out/1ST/B_KONAMI.BIN", "r+b")
            file.seek(0xF79)
            file.write(b'\x1F\xCE\xF3')
        case "maps/map3_s06" | "build/USA/out/VIN/MAP3_S06.BIN":
            # Random bytes at end of rodata section, linker artifact?
            file = open("build/USA/out/VIN/MAP3_S06.BIN", "r+b")
            file.seek(0x1D65)
            file.write(b'\x65\x74\x5F')
            file.close()
        case "maps/map4_s05" | "build/USA/out/VIN/MAP4_S05.BIN":
            # Random bytes at end of rodata section, linker artifact?
            file = open("build/USA/out/VIN/MAP4_S05.BIN", "r+b")
            file.seek(0x1729)
            file.write(b'\x65\x5F\x77')
            file.close()
        case "maps/map5_s01" | "build/USA/out/VIN/MAP5_S01.BIN":
            # Random bytes at end of rodata section, linker artifact?
            file = open("build/USA/out/VIN/MAP5_S01.BIN", "r+b")
            file.seek(0x3515)
            file.write(b'\x9C\x03\x08')
            file.close()
        case "maps/map6_s01" | "build/USA/out/VIN/MAP6_S01.BIN":
            # Random bytes at end of rodata section, linker artifact?
            file = open("build/USA/out/VIN/MAP6_S01.BIN", "r+b")
            file.seek(0x25e6)
            file.write(b'\x40\x14')
            file.close()
