#include "bodyprog/bodyprog.h"

s_EventParam D_800D5720[53] = {
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M3S04_HealthDrink0,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 52,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 2, // `func_800D2470`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M3S04_HealthDrink1,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 53,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 2, // `func_800D2470`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M3S04_HealthDrink2,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 54,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 2, // `func_800D2470`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M3S04_HealthDrink3,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 55,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 2, // `func_800D2470`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M3S04_HandgunBullets,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 56,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 2, // `func_800D2470`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = 292,
        .disabledEventFlag_2  = EventFlag_293,
        .triggerType_4_0      = TriggerType_None,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 0,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_Fmv,
        .eventData_8_5        = 10,
        .flags_8_13           = 2,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_293,
        .disabledEventFlag_2  = EventFlag_294,
        .triggerType_4_0      = TriggerType_None,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 0,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 4, // `func_800D2668`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_294,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_None,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 0,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadOverlay,
        .eventData_8_5        = 39,
        .flags_8_13           = 4,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP3_S06,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 38,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_SaveMenu1,
        .eventData_8_5        = 12,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M3S04_PickupPlateOfQueen,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 37,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 5, // `func_800D2E58`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_258,
        .disabledEventFlag_2  = 292,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 5,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 4,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP5_S02,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_M3S05_PickupExaminationRoomKey,
        .disabledEventFlag_2  = EventFlag_258,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 5,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 3, // `func_800D250C`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_M3S05_PickupExaminationRoomKey,
        .disabledEventFlag_2  = EventFlag_258,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 5,
        .requiredItemId_6     = InventoryItemId_ExaminationRoomKey,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 3, // `func_800D250C`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1474,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 5,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 1, // `func_800D21C4`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 40,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 6, // `sharedFunc_800D15F0_3_s01`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_216,
        .disabledEventFlag_2  = 220,
        .triggerType_4_0      = TriggerType_None,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 0,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadOverlay,
        .eventData_8_5        = 43,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP3_S05,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = 217,
        .disabledEventFlag_2  = 221,
        .triggerType_4_0      = TriggerType_None,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 0,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 17,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = 218,
        .disabledEventFlag_2  = 222,
        .triggerType_4_0      = TriggerType_None,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 0,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadOverlay,
        .eventData_8_5        = 41,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP3_S03,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_219,
        .disabledEventFlag_2  = EventFlag_223,
        .triggerType_4_0      = TriggerType_None,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 0,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadOverlay,
        .eventData_8_5        = 42,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP3_S03,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_213,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 17,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 36,
        .flags_8_13           = 0,
        .field_8_19           = 7,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_213,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 18,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 36,
        .flags_8_13           = 0,
        .field_8_19           = 7,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1477,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 6,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 26,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1477,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 26,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 6,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1479,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 7,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 24,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1479,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 24,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 7,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1481,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 8,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 23,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1481,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 23,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 8,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1482,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 22,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 0, // `MapEvent_DoorJammed`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1485,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 12,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 21,
        .flags_8_13           = 0,
        .field_8_19           = 13,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1485,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 21,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 12,
        .flags_8_13           = 0,
        .field_8_19           = 13,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1487,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 13,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 20,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1487,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 20,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 13,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1489,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 14,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 19,
        .flags_8_13           = 0,
        .field_8_19           = 14,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1489,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 19,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 14,
        .flags_8_13           = 0,
        .field_8_19           = 14,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1491,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 25,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 30,
        .flags_8_13           = 0,
        .field_8_19           = 13,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1491,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 30,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 25,
        .flags_8_13           = 0,
        .field_8_19           = 13,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1492,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 27,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 0, // `MapEvent_DoorJammed`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1494,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 32,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 0, // `MapEvent_DoorJammed`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1496,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 31,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 0, // `MapEvent_DoorJammed`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1468,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 33,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 0, // `MapEvent_DoorJammed`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 34,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadOverlay,
        .eventData_8_5        = 35,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP3_S03,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 15,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadOverlay,
        .eventData_8_5        = 16,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP3_S05,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 2,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 0, // `MapEvent_DoorJammed`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 3,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 0, // `MapEvent_DoorJammed`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 44,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 49,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 46,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 50,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 45,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 50,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 47,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 51,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 48,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 53,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 49,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 52,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 50,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 50,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 51,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 50,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_EndOfArray,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 0,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_Gameplay,
        .eventData_8_5        = 0,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
};
