
const char* g_MapMessages[] =
{
    #include "maps/shared/mapMsg_common.h"
    "~J1(3.6)\tFinally. ~N\n\t\t\tSomeone_else_who's_OK. ",
    "~J1(1.0)\tWho_are_you? ",
    "~J1(3.1)\tMy_name's_Lisa_Garland. ~N\n\t\t\tWhat's_yours? ",
    "~J1(1.2)\tHarry_Mason. ~E ",
    "~J0(4.7)\tHarry,_tell_me ~N\n\t\t\twhat's_happening_here? ~N\n\t\t\tWhere_is_everybody? ",
    "~J0(2.7)\tI_must_have_gotten_knocked_out. ",
    "~J0(3.2)\tWhen_I_came_to, ~N\n\t\t\teveryone_was_gone. ",
    "~J0(1.3)\tIt's_awful... ~E ",
    "~J1(3.8)\tSo_you_don't_know ~N\n\t\t\tanything_either.__Great. ",
    "~J1(2.5)\tI_just_don't_get_it. ~E ",
    "~J1(4.0)\tIt's_like_this_is ~N\n\t\t\tall_some_kind_of_bad_dream. ",
    "~J1(2.8)\tYeah. ~N\n\t\t\tA_living_nightmare. ~E ",
    "~J1(3.6)\tLet_me_ask_you,_have_you_seen ~N\n\t\t\ta_little_girl_around_here? ",
    "~J1(2.8)\tShort,_black_hair. ~N\n\t\t\tSeven_years_old. ",
    "~J1(3.8)\tA_seven-year-old_girl? ~N\n\t\t\tWhat?_She's_your_daughter? ",
    "~J1(1.2)\tYes. ",
    "~J1(3.0)\tA_seven-year-old_girl... ",
    "~J1(4.8)\tI_can't_say_that_I_have. ~N\n\t\t\tI_was_unconscious_all_this_time. ",
    "~J1(1.3)\tI'm_sorry. ~E ",
    "~J1(2.2)\tThat's_alright. ",
    "~J1(3.8)\tDo_you_know_anything_about_all ~N\n\t\t\tthat_weird_stuff_in_the_basement? ",
    "~J1(3.8)\tNo.__Why? ~N\n\t\t\tIs_there_something_down_there? ",
    "~J1(2.7)\tYou_don't_know? ~N\n\t\t\tDon't_you_work_here? ",
    "~J1(4.0)\tWe're_under_strict_orders_never_to ~N\n\t\t\tenter_the_basement_storeroom. ",
    "~J1(2.0)\tSo_I_really_don't_know. ~E ",
    "~J1(2.0)\tWhat_did_you_say_was_down_there? ",
    "~J1(1.7)\tWell,_it's... ~E ",
    "~J0(0.8)\t~E ",
    "~J0(2.5)\tDamn! ~N\n\t\t\tMy_head...  ",
    "~J0(2.5)\tWhat's_wrong? ~N\n\t\t\tHarry...? ~E ",
    "~J0(2.6)\tHarry, ~N\n\t\t\tlet_me_help_you. ~E ",
    "~J0(1.0)\t~E ",
    "\tThere_is_ a_ ~C2 Plate_of_[Queen] ~C7 . ~N\n\tTake_it? ~S4 ",
    "\tUsed_the_ ~C2 Examination_room_key ~C7 . ~E ",
    "\tThere_is_a_broken ~N\n\tvending_machine. ~E ",
    "\tNothing_unusual. ~E ",
    "\tThe_refrigerator_is_empty. ~E ",
    "\tNothing_helpful. ~E ",
    "\tNothing_useful ~N\n\tin_the_desk_drawer. ~E ",
    "\tA_sound_is_heard ~N\n\tfrom_beyond_the_door. ~E ",
};
