    {
      {
        .positionX_0 = Q12(-61.55f),
        .charaId_4 = Chara_LockerDeadBody,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(20.75f),
      },
      {
        .positionX_0 = Q12(-138.2f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(135.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(139.3f),
      },
      {
        .positionX_0 = Q12(-140.1f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(315.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(142.3f),
      },
      {
        .positionX_0 = Q12(-139.6f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(135.6f),
      },
      {
        .positionX_0 = Q12(-97.6f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(135.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(51.3f),
      },
      {
        .positionX_0 = Q12(-20.1f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(270.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(20.0f),
      },
      {
        .positionX_0 = Q12(-18.3f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(315.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(97.7f),
      },
      {
        .positionX_0 = Q12(-22.9f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(98.1f),
      },
      {
        .positionX_0 = Q12(-20.2f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(95.1f),
      },
      {
        .positionX_0 = Q12(-25.9f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(270.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(189.9f),
      },
      {
        .positionX_0 = Q12(-21.7f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(180.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(191.9f),
      },
      {
        .positionX_0 = Q12(-141.8f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(135.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(103.5f),
      },
      {
        .positionX_0 = Q12(-139.2f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(270.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(106.1f),
      },
      {
        .positionX_0 = Q12(-138.5f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(102.6f),
      },
      {
        .positionX_0 = Q12(-142.2f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(180.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(104.1f),
      },
      {
        .positionX_0 = Q12(-140.82f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(90.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(96.2f),
      },
    },
    {
      {
        .positionX_0 = Q12(-49.1f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(45.6f),
      },
      {
        .positionX_0 = Q12(-51.1f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(45.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(42.6f),
      },
      {
        .positionX_0 = Q12(-50.4f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(45.8f),
      },
      {
        .positionX_0 = Q12(-50.2f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(180.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(52.8f),
      },
      {
        .positionX_0 = Q12(-48.9f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(225.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(56.1f),
      },
      {
        .positionX_0 = Q12(-98.9f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(180.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(55.1f),
      },
      {
        .positionX_0 = Q12(-97.6f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(135.0f),
        .flags_6 = 3,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(51.3f),
      },
      {
        .positionX_0 = Q12(-19.9f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(270.0f),
        .flags_6 = 13,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(21.0f),
      },
      {
        .positionX_0 = Q12(-19.9f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(135.0f),
        .flags_6 = 12,
        .minGameDifficulty_7_0 = GameDifficulty_Easy,
        .positionZ_8 = Q12(18.9f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
      {
        .positionX_0 = Q12(0.0f),
        .charaId_4 = Chara_None,
        .rotationY_5 = Q8_ANGLE(0.0f),
        .flags_6 = 0,
        .minGameDifficulty_7_0 = GameDifficulty_Normal,
        .positionZ_8 = Q12(0.0f),
      },
    },
