#include "bodyprog/bodyprog.h"

s_EventParam D_800E1AA0[103] = {
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S03_ShotgunShells0,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 84,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 5, // `func_800DA950`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S03_HandgunBullets0,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 85,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 5, // `func_800DA950`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S03_HealthDrink0,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 86,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 5, // `func_800DA950`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S03_HandgunBullets1,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 87,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 5, // `func_800DA950`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S03_HandgunBullets2,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 88,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 5, // `func_800DA950`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S03_ShotgunShells1,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 89,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 5, // `func_800DA950`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S03_HandgunBullets3,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 90,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 5, // `func_800DA950`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S03_HealthDrink1,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 91,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 5, // `func_800DA950`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S03_HealthDrink2,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 92,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 5, // `func_800DA950`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S03_FirstAidKit,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 93,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 5, // `func_800DA950`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_97,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 23,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 9, // `func_800DBEC8`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 24,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 39,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 25,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 10, // `func_800DC0F8`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_M1S03_KeyDownTheDrain,
        .disabledEventFlag_2  = EventFlag_M1S02_PickupClassroomKey,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 17,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 7, // `func_800DABC4`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_M1S03_KeyDownTheDrain,
        .disabledEventFlag_2  = EventFlag_M1S02_PickupClassroomKey,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 18,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 7, // `func_800DABC4`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S03_KeyDownTheDrain,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 17,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 7, // `func_800DABC4`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S03_KeyDownTheDrain,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 18,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 7, // `func_800DABC4`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 17,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 7, // `func_800DABC4`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 18,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 7, // `func_800DABC4`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_M1S02_UsedRubberBall,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 19,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 7, // `func_800DABC4`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_M1S02_UsedRubberBall,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 20,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 7, // `func_800DABC4`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S02_UsedRubberBall,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 19,
        .requiredItemId_6     = InventoryItemId_RubberBall,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 15, // `func_800DCB54`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S02_UsedRubberBall,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 20,
        .requiredItemId_6     = InventoryItemId_RubberBall,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 15, // `func_800DCB54`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 19,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 7, // `func_800DABC4`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 20,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 7, // `func_800DABC4`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_112,
        .disabledEventFlag_2  = EventFlag_M1S03_KeyDownTheDrain,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 21,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 8, // `func_800DAF18`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1364,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 21,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 31,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = 1295,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 26,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 41,
        .flags_8_13           = 0,
        .field_8_19           = 13,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = 1295,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 41,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 26,
        .flags_8_13           = 0,
        .field_8_19           = 13,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1295,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 41,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1294,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 26,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = 1297,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 42,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 32,
        .flags_8_13           = 0,
        .field_8_19           = 13,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = 1297,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 32,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 42,
        .flags_8_13           = 0,
        .field_8_19           = 13,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1297,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 42,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1296,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 32,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1307,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 43,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 48,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1307,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 48,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 43,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1305,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 44,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 49,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1305,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 49,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 44,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = 1303,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 45,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 51,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = 1303,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 51,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 45,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1303,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 51,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1302,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 45,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = 1301,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 46,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 52,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = 1301,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 52,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 46,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_M1S02_PickupClassroomKey,
        .disabledEventFlag_2  = 1301,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 46,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 4, // `func_800DA8B0`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_M1S02_PickupClassroomKey,
        .disabledEventFlag_2  = 1301,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 46,
        .requiredItemId_6     = InventoryItemId_ClassroomKey,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 4, // `func_800DA8B0`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1300,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 46,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1299,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 47,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 54,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1299,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 54,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 47,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1309,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 50,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 53,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1309,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 53,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 50,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1293,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 28,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 30,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1293,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 30,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 28,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1290,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 29,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 0, // `MapEvent_DoorJammed`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1289,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 56,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 27,
        .flags_8_13           = 0,
        .field_8_19           = 13,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1289,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 27,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 56,
        .flags_8_13           = 0,
        .field_8_19           = 13,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1317,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 57,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 33,
        .flags_8_13           = 0,
        .field_8_19           = 13,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1317,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 33,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 57,
        .flags_8_13           = 0,
        .field_8_19           = 13,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1331,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 58,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadOverlay,
        .eventData_8_5        = 9,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP1_S02,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1331,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 9,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 58,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1329,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 59,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 10,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1329,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 10,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 59,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1325,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 60,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 64,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1325,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 64,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 60,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1323,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 61,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 65,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1323,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 65,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 61,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1321,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 62,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 67,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1321,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 67,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 62,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1319,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 63,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 68,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1319,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 68,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 63,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1327,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 66,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 69,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1327,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 69,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 66,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1339,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 55,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 38,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1339,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 38,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 55,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = 1311,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 34,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 37,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = 1311,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 37,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 34,
        .flags_8_13           = 0,
        .field_8_19           = 12,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_M1S03_PickupLibraryReserveKey,
        .disabledEventFlag_2  = 1311,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 34,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 3, // `func_800DA7F4`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_M1S03_PickupLibraryReserveKey,
        .disabledEventFlag_2  = 1311,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 34,
        .requiredItemId_6     = InventoryItemId_LibraryReserveKey,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 3, // `func_800DA7F4`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1310,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 34,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1312,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 35,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 0, // `MapEvent_DoorJammed`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1314,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 36,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 0, // `MapEvent_DoorJammed`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 72,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 8,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 7,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 4,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1363,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 5,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 6,
        .flags_8_13           = 0,
        .field_8_19           = 14,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1363,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 6,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 5,
        .flags_8_13           = 0,
        .field_8_19           = 14,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 70,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadOverlay,
        .eventData_8_5        = 2,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP1_S02,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 71,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadOverlay,
        .eventData_8_5        = 3,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP1_S02,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1332,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 11,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventSetFlag,
        .eventData_8_5        = 0,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1334,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 12,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventSetFlag,
        .eventData_8_5        = 0,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1336,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 13,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventSetFlag,
        .eventData_8_5        = 0,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_M1S03_LockerOpened,
        .disabledEventFlag_2  = EventFlag_105,
        .triggerType_4_0      = TriggerType_TouchObb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 77,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 13, // `func_800DC780`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_M1S03_LockerOpened,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 76,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 11, // `func_800DC2E4`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S03_LockerOpened,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 76,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 12, // `func_800DC310`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_106,
        .disabledEventFlag_2  = EventFlag_M1S03_PickupLibraryReserveKey,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 82,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 14, // `func_800DC9A0`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_106,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 78,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 45,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_106,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 79,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 45,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_106,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 80,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 45,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 73,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 42,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 74,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 42,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 75,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 42,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_456,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 83,
        .requiredItemId_6     = InventoryItemId_ChannelingStone,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 16, // `func_800DCDDC`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_EndOfArray,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 0,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_Gameplay,
        .eventData_8_5        = 0,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
};
