    {
        .positionX = Q12(-11.3f),
        .paperMapIdx = PaperMapIdx_AltSchoolRF,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 0,
        .positionZ = Q12(-14.7f),
    },
    {
        .positionX = Q12(-101.3f),
        .paperMapIdx = PaperMapIdx_AltSchool2F,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 0,
        .positionZ = Q12(140.3f),
    },
    {
        .positionX = Q12(111.0f),
        .paperMapIdx = PaperMapIdx_AltSchool1F,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 0,
        .positionZ = Q12(45.9f),
    },
    {
        .positionX = Q12(58.0f),
        .paperMapIdx = PaperMapIdx_AltSchool1F,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 0,
        .positionZ = Q12(74.0f),
    },
    {
        .positionX = Q12(-101.0f),
        .paperMapIdx = PaperMapIdx_AltSchool2F,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 0,
        .positionZ = Q12(74.0f),
    },
    {
        .positionX = Q12(-56.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 1,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(-17.2f),
    },
    {
        .positionX = Q12(-30.3f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 6,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(-11.0f),
    },
    {
        .positionX = Q12(-63.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 6,
        .positionZ = Q12(-17.2f),
    },
    {
        .positionX = Q12(-61.0f),
        .paperMapIdx = PaperMapIdx_AltSchoolRF,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 0,
        .positionZ = Q12(-17.2f),
    },
    {
        .positionX = Q12(23.27f),
        .paperMapIdx = PaperMapIdx_AltSchool1F,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(19.9f),
    },
    {
        .positionX = Q12(-136.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(59.4f),
    },
    {
        .positionX = Q12(-98.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 19,
        .positionZ = Q12(59.6f),
    },
    {
        .positionX = Q12(-98.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 19,
        .positionZ = Q12(46.8f),
    },
    {
        .positionX = Q12(-49.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 19,
        .positionZ = Q12(60.3f),
    },
    {
        .positionX = Q12(-99.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 12,
        .triggerParam1 = 19,
        .positionZ = Q12(74.1f),
    },
    {
        .positionX = Q12(-32.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 6,
        .positionZ = Q12(191.5f),
    },
    {
        .positionX = Q12(-29.3f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 6,
        .positionZ = Q12(191.5f),
    },
    {
        .positionX = Q12(-16.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 5,
        .positionZ = Q12(-17.6f),
    },
    {
        .positionX = Q12(-17.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 3,
        .positionZ = Q12(-17.5f),
    },
    {
        .positionX = Q12(-10.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 8,
        .positionZ = Q12(-17.6f),
    },
    {
        .positionX = Q12(-10.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 8,
        .positionZ = Q12(-17.6f),
    },
    {
        .positionX = Q12(-10.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 6,
        .positionZ = Q12(-12.9f),
    },
    {
        .positionX = Q12(-28.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 6,
        .positionZ = Q12(20.0f),
    },
    {
        .positionX = Q12(-101.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(142.0f),
    },
    {
        .positionX = Q12(-101.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 28,
        .positionZ = Q12(140.8f),
    },
    {
        .positionX = Q12(-59.35f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 5,
        .positionZ = Q12(141.7f),
    },
    {
        .positionX = Q12(-10.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 14,
        .positionZ = Q12(20.0f),
    },
    {
        .positionX = Q12(-29.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 14,
        .positionZ = Q12(20.0f),
    },
    {
        .positionX = Q12(-15.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(18.4f),
    },
    {
        .positionX = Q12(-28.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(18.4f),
    },
    {
        .positionX = Q12(-56.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(16.8f),
    },
    {
        .positionX = Q12(-102.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(23.7f),
    },
    {
        .positionX = Q12(-14.9f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 14,
        .positionZ = Q12(191.5f),
    },
    {
        .positionX = Q12(-34.1f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 14,
        .positionZ = Q12(191.5f),
    },
    {
        .positionX = Q12(-16.1f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(193.1f),
    },
    {
        .positionX = Q12(-28.9f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(193.1f),
    },
    {
        .positionX = Q12(-32.1f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(193.1f),
    },
    {
        .positionX = Q12(-97.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(136.8f),
    },
    {
        .positionX = Q12(-96.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(141.8f),
    },
    {
        .positionX = Q12(-63.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(96.8f),
    },
    {
        .positionX = Q12(-98.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(96.8f),
    },
    {
        .positionX = Q12(-51.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 14,
        .positionZ = Q12(49.1f),
    },
    {
        .positionX = Q12(-51.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 14,
        .positionZ = Q12(71.5f),
    },
    {
        .positionX = Q12(-48.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(48.7f),
    },
    {
        .positionX = Q12(-48.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(59.1f),
    },
    {
        .positionX = Q12(-48.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(61.5f),
    },
    {
        .positionX = Q12(-48.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(71.9f),
    },
    {
        .positionX = Q12(-50.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(73.1f),
    },
    {
        .positionX = Q12(-23.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(54.6f),
    },
    {
        .positionX = Q12(-23.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(65.4f),
    },
    {
        .positionX = Q12(-17.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(66.4f),
    },
    {
        .positionX = Q12(-23.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(94.6f),
    },
    {
        .positionX = Q12(-23.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(105.4f),
    },
    {
        .positionX = Q12(-17.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(93.6f),
    },
    {
        .positionX = Q12(-63.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(137.8f),
    },
    {
        .positionX = Q12(-64.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(142.8f),
    },
    {
        .positionX = Q12(-96.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 14,
        .positionZ = Q12(48.4f),
    },
    {
        .positionX = Q12(-96.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 14,
        .positionZ = Q12(70.8f),
    },
    {
        .positionX = Q12(-99.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(41.2f),
    },
    {
        .positionX = Q12(-99.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(44.4f),
    },
    {
        .positionX = Q12(-99.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(48.0f),
    },
    {
        .positionX = Q12(-99.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(58.4f),
    },
    {
        .positionX = Q12(-99.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(60.8f),
    },
    {
        .positionX = Q12(-99.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 9,
        .positionZ = Q12(71.3f),
    },
    {
        .positionX = Q12(-136.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(95.6f),
    },
    {
        .positionX = Q12(-136.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(106.4f),
    },
    {
        .positionX = Q12(-141.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 9,
        .positionZ = Q12(107.4f),
    },
    {
        .positionX = Q12(-136.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(134.6f),
    },
    {
        .positionX = Q12(-136.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 9,
        .positionZ = Q12(145.4f),
    },
    {
        .positionX = Q12(-142.2f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 9,
        .positionZ = Q12(133.6f),
    },
    {
        .positionX = Q12(-45.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 6,
        .positionZ = Q12(42.7f),
    },
    {
        .positionX = Q12(-103.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 6,
        .positionZ = Q12(77.3f),
    },
    {
        .positionX = Q12(-103.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 6,
        .positionZ = Q12(74.0f),
    },
    {
        .positionX = Q12(-57.6f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 38,
        .positionZ = Q12(19.2f),
    },
    {
        .positionX = Q12(-58.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 38,
        .positionZ = Q12(19.2f),
    },
    {
        .positionX = Q12(-61.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 51,
        .positionZ = Q12(20.0f),
    },
    {
        .positionX = Q12(-58.8f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 192,
        .triggerParam1 = 6,
        .positionZ = Q12(18.3f),
    },
    {
        .positionX = Q12(-60.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 16,
        .positionZ = Q12(19.7f),
    },
    {
        .positionX = Q12(-60.7f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 128,
        .triggerParam1 = 6,
        .positionZ = Q12(20.4f),
    },
    {
        .positionX = Q12(-60.7f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 6,
        .positionZ = Q12(21.0f),
    },
    {
        .positionX = Q12(-60.3f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 64,
        .triggerParam1 = 4,
        .positionZ = Q12(20.7f),
    },
    {
        .positionX = Q12(-60.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 6,
        .triggerParam1 = 6,
        .positionZ = Q12(18.4f),
    },
    {
        .positionX = Q12(-60.32f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(20.23f),
    },
    {
        .positionX = Q12(-20.0f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 44,
        .triggerParam1 = 24,
        .positionZ = Q12(-13.0f),
    },
    {
        .positionX = Q12(-137.4f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(98.2f),
    },
    {
        .positionX = Q12(-141.9f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(144.37f),
    },
    {
        .positionX = Q12(-21.9f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(62.8f),
    },
    {
        .positionX = Q12(-141.47f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(60.09f),
    },
    {
        .positionX = Q12(-141.3f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(60.58f),
    },
    {
        .positionX = Q12(-141.76f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(60.51f),
    },
    {
        .positionX = Q12(-58.58f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(140.07f),
    },
    {
        .positionX = Q12(-96.9f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(63.1f),
    },
    {
        .positionX = Q12(-48.5f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(56.8f),
    },
    {
        .positionX = Q12(-101.83f),
        .paperMapIdx = PaperMapIdx_OtherPlaces,
        .field_4_5 = 0,
        .loadingScreenId = LoadingScreenId_None,
        .field_4_12 = 0,
        .triggerParam0 = 0,
        .triggerParam1 = 0,
        .positionZ = Q12(138.62f),
    }

