#include "bodyprog/bodyprog.h"

s_EventParam D_800DD01C[104] = {
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S01_HandgunBullets0,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 96,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 3, // `func_800D7214`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S01_FirstAidKit,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 97,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 3, // `func_800D7214`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S01_HealthDrink,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 98,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 3, // `func_800D7214`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S01_HandgunBullets1,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 99,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 3, // `func_800D7214`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S01_HandgunBullets2,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 100,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 3, // `func_800D7214`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_M1S01_PianoPuzzleSolved,
        .disabledEventFlag_2  = EventFlag_M1S01_PickupSilverMedallion,
        .triggerType_4_0      = TriggerType_TouchFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 17,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 11, // `func_800D857C`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_M1S01_PianoPuzzleSolved,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 16,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 10, // `func_800D7EEC`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_71,
        .disabledEventFlag_2  = EventFlag_M1S01_PianoPuzzleSolved,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 16,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 9, // `func_800D7864`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 16,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 26,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 15,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 8, // `func_800D7830`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_74,
        .disabledEventFlag_2  = EventFlag_M1S01_PickupGoldMedallion,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 12,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 7, // `func_800D76F4`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_M1S01_PickupGoldMedallion,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 12,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 20,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 12,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 4, // `func_800D72B0`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_74,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Item,
        .pointOfInterestIdx_5 = 12,
        .requiredItemId_6     = InventoryItemId_Chemical,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 6, // `func_800D7308`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_M1S01_PickupChemical,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 13,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 19,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_M1S01_PickupChemical,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 13,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 5, // `func_800D72DC`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_77,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 14,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 12, // `func_800D8794`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_76,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 14,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 13, // `func_800D87C0`
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1229,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 51,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 36,
        .flags_8_13           = 0,
        .field_8_19           = 2,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1229,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 36,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 51,
        .flags_8_13           = 0,
        .field_8_19           = 2,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1231,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 52,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 42,
        .flags_8_13           = 0,
        .field_8_19           = 2,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1231,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 42,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 52,
        .flags_8_13           = 0,
        .field_8_19           = 2,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1241,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 53,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 58,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1241,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 58,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 53,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1239,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 54,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 59,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1239,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 59,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 54,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1237,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 55,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 61,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1237,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 61,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 55,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1235,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 56,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 62,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1235,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 62,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 56,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1233,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 57,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 64,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1233,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 64,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 57,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1243,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 60,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 63,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1243,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 63,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 60,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1227,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 38,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 40,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1227,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 40,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 38,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1225,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 39,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 41,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1225,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 41,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 39,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = 1223,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 66,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 37,
        .flags_8_13           = 0,
        .field_8_19           = 2,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = 1223,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 37,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 66,
        .flags_8_13           = 0,
        .field_8_19           = 2,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1223,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 66,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1222,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 37,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1251,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 67,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 43,
        .flags_8_13           = 0,
        .field_8_19           = 2,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1251,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 43,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 67,
        .flags_8_13           = 0,
        .field_8_19           = 2,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1265,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 68,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 3,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1265,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 3,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 68,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1263,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 69,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 4,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1263,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 4,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 69,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1259,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 70,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 74,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1259,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 74,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 70,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1257,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 71,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 75,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1257,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 75,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 71,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1255,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 72,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 77,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1255,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 77,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 72,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1253,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 73,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 78,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1253,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 78,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 73,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1261,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 76,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 79,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1261,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 79,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 76,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1267,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 65,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 48,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1267,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 48,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 65,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = 1245,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 44,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 47,
        .flags_8_13           = 0,
        .field_8_19           = 2,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = 1245,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 47,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 44,
        .flags_8_13           = 0,
        .field_8_19           = 2,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1245,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 47,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 2, // `MapEvent_DoorUnlocked`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1244,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 44,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 1, // `MapEvent_DoorLocked`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1247,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 45,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 49,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1247,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 49,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 45,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1249,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 46,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 50,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1249,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 50,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 46,
        .flags_8_13           = 0,
        .field_8_19           = 1,
        .field_8_24           = 1,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 82,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 11,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 10,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadRoom,
        .eventData_8_5        = 7,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1354,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 8,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventCallFunc,
        .eventData_8_5        = 0, // `MapEvent_DoorJammed`
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 80,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadOverlay,
        .eventData_8_5        = 5,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP1_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 81,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_LoadOverlay,
        .eventData_8_5        = 6,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP1_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1268,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 18,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventSetFlag,
        .eventData_8_5        = 0,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = 1270,
        .triggerType_4_0      = TriggerType_TouchAabb,
        .activationType_4_4   = TriggerActivationType_Exclusive,
        .pointOfInterestIdx_5 = 19,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_EventSetFlag,
        .eventData_8_5        = 0,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 21,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 34,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 22,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 35,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 23,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 35,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 24,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 35,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 25,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 36,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 26,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 37,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 27,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 37,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 28,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 38,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 29,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 39,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 30,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 41,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 31,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 41,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 32,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 42,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 33,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 42,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 34,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 42,
        .flags_8_13           = 1,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 35,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 36,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 94,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 36,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 95,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 36,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 83,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 44,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 84,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 44,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 85,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 45,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 86,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 45,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 87,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 46,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 88,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 44,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 89,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 45,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 90,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 45,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 91,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 44,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 92,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 46,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_TouchObbFacing,
        .activationType_4_4   = TriggerActivationType_Button,
        .pointOfInterestIdx_5 = 93,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_ReadMessage,
        .eventData_8_5        = 46,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
    {
        .requiredEventFlag_0  = EventFlag_None,
        .disabledEventFlag_2  = EventFlag_None,
        .triggerType_4_0      = TriggerType_EndOfArray,
        .activationType_4_4   = TriggerActivationType_None,
        .pointOfInterestIdx_5 = 0,
        .requiredItemId_6     = InventoryItemId_Unequipped,
        .unk_7                = { 0 },
        .sysState_8_0         = SysState_Gameplay,
        .eventData_8_5        = 0,
        .flags_8_13           = 0,
        .field_8_19           = 0,
        .field_8_24           = 0,
        .mapOverlayIdx_8_25   = MapOverlayId_MAP0_S00,
        .field_8_31           = 0,
    },
};
